#!/usr/bin/env bash
#
# SBOM — the software bill of materials face of the Master Security/Quality
# Gate (docs/25_CICD_DEVOPS.md §23 item 10 "container build/SBOM", and
# docs/40_OPEN_SOURCE_LICENSES.md:3 "实际版本与许可证在 bootstrap/CI 中生成
# SBOM 并核对").
#
#   bash tests/security/sbom.sh go       # Go modules    -> .sbom/go.cdx.json
#   bash tests/security/sbom.sh node     # npm workspace -> .sbom/node.cdx.json
#   bash tests/security/sbom.sh python   # pip/uv        -> .sbom/python.cdx.json
#
# Three rows of tests/security/master-security-gate.sh call this script. Each
# row GENERATES its document and then validates it in the same run, so a row
# cannot be green against an artifact that happens to be lying around: what it
# reports is what it just produced.
#
# WHAT MAKES A ROW HERE MEAN SOMETHING
# ------------------------------------
#  1. THE ARTIFACTS ARE NEVER COMMITTED. They are build output — machine
#     specific, reproducible from the lockfiles, and useless as source. They
#     live in .sbom/, which .gitignore excludes; a committed SBOM would go
#     stale silently, which is the failure docs/40 is written against.
#  2. THE GENERATOR IS PINNED, AND THE PIN IS CHECKED. cyclonedx-gomod's
#     version comes from ops/security/tool-versions.sh; pnpm from
#     package.json's packageManager, uv from its own `--version`. A manifest
#     produced by an unknown generator is an inventory of an unknown tree.
#  3. A GREEN ROW IS A VALIDATED DOCUMENT, NOT A FILE. tests/security/check-sbom.py
#     re-parses the JSON, applies the face's component floor, and resolves
#     every key component in tests/security/key-components.json — including
#     the entries whose answer is "this is here" and the ones whose answer is
#     "this is deliberately NOT here, and here is the witness that says so".
#  4. THE LICENCE DATA IS NOT INVENTED. The Go face reads the generator's own
#     licence detection (kept as CycloneDX *evidence*, not asserted as fact:
#     the generator documents that its detection may be wrong). The Node face
#     reads pnpm's, which comes from the installed workspace. The Python face
#     has none from `uv export`, so tests/security/sbom_python_licenses.py
#     copies each installed distribution's PEP 639 License-Expression out of
#     its dist-info METADATA and records the provenance per component.
#
# MUTATION HOOKS (how this row is shown to be able to fail)
# ---------------------------------------------------------
#   POST_SBOM_REUSE     validate the document already on disk instead of
#                       regenerating it. This is what lets a mutation run
#                       truncate an artifact and watch the row go red; a gate
#                       run never sets it. THE WORD LIST IS EXACT: only `1`,
#                       `true` or `yes` mean reuse. Everything else — unset,
#                       empty, `0`, `no`, `false`, anything misspelled —
#                       REGENERATES. The direction matters: `POST_SBOM_REUSE=0`
#                       reads as "do not reuse" to every human, and a hook
#                       whose off switch turns it on produces the opposite of
#                       what it says. (It used to: the test was
#                       `[ -z "$POST_SBOM_REUSE" ]`, and `0` is not empty.)
#   POST_SBOM_FACE_DIR  where the artifacts live (default .sbom).
#
# WHAT ELSE IS WRITTEN BESIDE EACH DOCUMENT
# -----------------------------------------
#   <face>.run          one line: the id of the run that produced the document
#                       next to it. The gate exports POST_GATE_RUN_ID to every
#                       row, so a gate run's three documents carry its id; a
#                       hand-run of this script stamps its own. The licence
#                       audit reads the stamp to tell "the sbom-* rows produced
#                       this a moment ago" from "this is what an earlier run
#                       left in .sbom/", which is the difference between a
#                       green row about this tree and a green row about a tree
#                       that no longer exists. Reuse mode deliberately does NOT
#                       refresh the stamp: the document on disk was not
#                       produced here, and saying otherwise would launder it.
#
# Exit codes
#   0  the document was generated by the pinned generator and validated
#   1  generation failed, or validation found the document unusable, too
#      small, or missing a key component
#   2  usage error, or a generator this row needs is missing
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

VERSIONS="$ROOT/ops/security/tool-versions.sh"
# shellcheck source=/dev/null
. "$VERSIONS" || { echo "sbom: cannot read $VERSIONS" >&2; exit 2; }

DEST="${POST_SBOM_FACE_DIR:-$ROOT/.sbom}"
MANIFEST="tests/security/key-components.json"

# Which run is writing here (see WHAT ELSE IS WRITTEN above). The gate exports
# POST_GATE_RUN_ID to every row it runs; a hand-run gets an id of its own, so
# a hand-run document is never mistaken for one this run produced.
RUN_ID="${POST_GATE_RUN_ID:-standalone-$(date -u +%Y%m%dT%H%M%SZ)-$$}"

have() { command -v "$1" >/dev/null 2>&1; }
die() { echo "sbom: $*" >&2; exit 1; }
usage() { sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//' | sed '/^$/q'; exit 2; }

# The exact word list, and nothing else (see MUTATION HOOKS above).
reuse_document() {
  case "${POST_SBOM_REUSE:-}" in
    1|true|yes) return 0;;
    *) return 1;;
  esac
}

stamp() { # stamp <face> — record the run that produced the document beside it
  printf '%s\n' "$RUN_ID" >"$DEST/$1.run"
}

reuse_note() { # reuse_note <face>
  # The wording has to say WHICH run wrote the document being validated: "reuse"
  # without that is a green line about an unknown tree. The stamp is the answer,
  # and its absence is itself information (a generator run by hand, or a
  # document written before this script stamped them) — so it is said, not left
  # as a blank where a run id would have been.
  local prior
  prior="$(cat "$DEST/$1.run" 2>/dev/null)" || prior=""
  if [ -n "$prior" ]; then
    echo "     reuse: validating $DEST/$1.cdx.json as it is (POST_SBOM_REUSE=${POST_SBOM_REUSE}) — written by $prior"
  else
    echo "     reuse: validating $DEST/$1.cdx.json as it is (POST_SBOM_REUSE=${POST_SBOM_REUSE}) — no \
run stamp beside it: written before this script stamped its documents, or by a generator run by hand. \
There is no record of which run produced the bytes being validated."
  fi
}

mkdir -p "$DEST"
[ -w "$DEST" ] || die "cannot write SBOM artifacts to $DEST"

check() { # check <face> <generator-description>
  python3 tests/security/check-sbom.py \
    --face "$1" --report "$DEST/$1.cdx.json" --manifest "$MANIFEST" \
    --id "sbom-$1" --generator "$2"
}

case "${1:-}" in
  go)
    have go || die "go is not on PATH (https://go.dev/dl)"
    if ! reuse_document; then
      BIN="$(command -v cyclonedx-gomod)" || die "cyclonedx-gomod is not on PATH — run 'make security-tools' (pins $CYCLONEDX_GOMOD_VERSION)"
      HAVE="$(cyclonedx-gomod version 2>/dev/null | awk '$1=="Version:" {print $2}')"
      [ "$HAVE" = "$CYCLONEDX_GOMOD_VERSION" ] || die "cyclonedx-gomod at $BIN is ${HAVE:-unknown}, the pin is \
$CYCLONEDX_GOMOD_VERSION (ops/security/tool-versions.sh). Run 'make security-tools'. A manifest from an \
unknown generator is an inventory of an unknown tree."
      # -licenses runs the tool's own detection. We deliberately do NOT add
      # -assert-licenses: its documentation says the detected licences are
      # reported as evidence "because it can not be guaranteed that the
      # detected licenses are in fact correct", and the license-audit row reads
      # both fields — so the document keeps that distinction instead of
      # flattening it into an assertion the generator does not make.
      cyclonedx-gomod mod -json -licenses -output "$DEST/go.cdx.json" . >"$DEST/go.log" 2>&1
      rc=$?
      [ "$rc" -eq 0 ] || { tail -20 "$DEST/go.log" | sed 's/^/     /'; die "sbom-go: cyclonedx-gomod exited $rc"; }
      stamp go
    else
      reuse_note go
    fi
    check go "cyclonedx-gomod $CYCLONEDX_GOMOD_VERSION (go.mod, license evidence included)" || exit 1
    ;;

  node)
    have pnpm || die "pnpm is not on PATH (the workspace pins it in package.json)"
    [ -d node_modules ] || die "node_modules is missing. pnpm's SBOM reads the INSTALLED workspace, and without \
it the document has no licence data at all (every component would read as unlicensed). Run \
'pnpm install --frozen-lockfile' first — 'make security-tools' does that for you."
    if ! reuse_document; then
      HAVE="$(pnpm --version)"
      PIN="$(node -p "require('./package.json').packageManager.replace(/^pnpm@/, '')" 2>/dev/null)"
      [ "$HAVE" = "$PIN" ] || die "pnpm at $(command -v pnpm) is $HAVE, package.json pins pnpm@$PIN. Install the \
workspace's own package manager rather than whichever pnpm happens to be on PATH."
      pnpm sbom --sbom-format cyclonedx --sbom-spec-version 1.5 --out "$DEST/node.cdx.json" >"$DEST/node.log" 2>&1
      rc=$?
      [ "$rc" -eq 0 ] || { tail -20 "$DEST/node.log" | sed 's/^/     /'; die "sbom-node: pnpm sbom exited $rc"; }
      stamp node
    else
      reuse_note node
    fi
    HAVE_PNPM="$(pnpm --version)"
    check node "pnpm $HAVE_PNPM sbom (pnpm-lock.yaml, CycloneDX 1.5)" || exit 1
    ;;

  python)
    have uv || die "uv is not on PATH (services/scientific-adapter pins it as its package manager)"
    ADAPTER="services/scientific-adapter"
    [ -f "$ADAPTER/uv.lock" ] || die "no $ADAPTER/uv.lock"
    VENV="$ADAPTER/.venv"
    [ -d "$VENV" ] || die "$VENV does not exist. The Python face's licence data comes from the installed \
distributions' METADATA, and 'uv export' alone carries no licence at all. Run 'uv sync --frozen' in \
$ADAPTER first — 'make security-tools' does that for you."
    HAVE="$(uv --version | awk '{print $2}')"
    if ! reuse_document; then
      # uv export resolves the project's own pyproject.toml, so it has to run
      # from the adapter's directory; the output path stays absolute.
      ( cd "$ADAPTER" && uv export --frozen --no-emit-project --format cyclonedx1.5 -o "$DEST/python.raw.json" ) \
        >"$DEST/python.log" 2>&1
      rc=$?
      [ "$rc" -eq 0 ] || { tail -20 "$DEST/python.log" | sed 's/^/     /'; die "sbom-python: uv export exited $rc"; }
      python3 tests/security/sbom_python_licenses.py \
        --raw "$DEST/python.raw.json" --venv "$VENV" --out "$DEST/python.cdx.json" || exit 1
      stamp python
    else
      reuse_note python
    fi
    check python "uv $HAVE export --format cyclonedx1.5 + licenses from $VENV dist-info METADATA" || exit 1
    ;;

  ""|-h|--help) usage;;
  *) echo "sbom: unknown face '$1' (expected go, node or python)" >&2; exit 2;;
esac
