#!/usr/bin/env bash
#
# SBOM — the software bill of materials face of the Master Security/Quality
# Gate (docs/25_CICD_DEVOPS.md §23 item 10 "container build/SBOM", and
# docs/40_OPEN_SOURCE_LICENSES.md:3 "实际版本与许可证在 bootstrap/CI 中生成
# SBOM 并核对").
#
#   bash tests/security/sbom.sh go       # Go modules    -> .sbom/go.cdx.json
#   bash tests/security/sbom.sh node     # npm workspace -> .sbom/node.cdx.json
#   bash tests/security/sbom.sh python   # pip/uv        -> .sbom/python.cdx.json
#
# Three rows of tests/security/master-security-gate.sh call this script. Each
# row GENERATES its document and then validates it in the same run, so a row
# cannot be green against an artifact that happens to be lying around: what it
# reports is what it just produced.
#
# WHAT MAKES A ROW HERE MEAN SOMETHING
# ------------------------------------
#  1. THE ARTIFACTS ARE NEVER COMMITTED. They are build output — machine
#     specific, reproducible from the lockfiles, and useless as source. They
#     live in .sbom/, which .gitignore excludes; a committed SBOM would go
#     stale silently, which is the failure docs/40 is written against.
#  2. THE GENERATOR IS PINNED, AND THE PIN IS CHECKED. cyclonedx-gomod's
#     version comes from ops/security/tool-versions.sh; pnpm from
#     package.json's packageManager, uv from its own `--version`. A manifest
#     produced by an unknown generator is an inventory of an unknown tree.
#  3. A GREEN ROW IS A VALIDATED DOCUMENT, NOT A FILE. tests/security/check-sbom.py
#     re-parses the JSON, applies the face's component floor, and resolves
#     every key component in tests/security/key-components.json — including
#     the entries whose answer is "this is here" and the ones whose answer is
#     "this is deliberately NOT here, and here is the witness that says so".
#  4. THE LICENCE DATA IS NOT INVENTED. The Go face reads the generator's own
#     licence detection (kept as CycloneDX *evidence*, not asserted as fact:
#     the generator documents that its detection may be wrong). The Node face
#     reads pnpm's, which comes from the installed workspace. The Python face
#     has none from `uv export`, so tests/security/sbom_python_licenses.py
#     copies each installed distribution's PEP 639 License-Expression out of
#     its dist-info METADATA and records the provenance per component.
#
# MUTATION HOOKS (how this row is shown to be able to fail)
# ---------------------------------------------------------
#   POST_SBOM_REUSE=1   validate the document already on disk instead of
#                       regenerating it. This is what lets the mutation check
#                       truncate an artifact and watch the row go red; a gate
#                       run never sets it.
#   POST_SBOM_FACE_DIR  where the artifacts live (default .sbom).
#
# Exit codes
#   0  the document was generated by the pinned generator and validated
#   1  generation failed, or validation found the document unusable, too
#      small, or missing a key component
#   2  usage error, or a generator this row needs is missing
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

VERSIONS="$ROOT/ops/security/tool-versions.sh"
# shellcheck source=/dev/null
. "$VERSIONS" || { echo "sbom: cannot read $VERSIONS" >&2; exit 2; }

DEST="${POST_SBOM_FACE_DIR:-$ROOT/.sbom}"
MANIFEST="tests/security/key-components.json"

have() { command -v "$1" >/dev/null 2>&1; }
die() { echo "sbom: $*" >&2; exit 1; }
usage() { sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//' | sed '/^$/q'; exit 2; }

mkdir -p "$DEST"
[ -w "$DEST" ] || die "cannot write SBOM artifacts to $DEST"

check() { # check <face> <generator-description>
  python3 tests/security/check-sbom.py \
    --face "$1" --report "$DEST/$1.cdx.json" --manifest "$MANIFEST" \
    --id "sbom-$1" --generator "$2"
}

case "${1:-}" in
  go)
    have go || die "go is not on PATH (https://go.dev/dl)"
    if [ -z "${POST_SBOM_REUSE:-}" ]; then
      BIN="$(command -v cyclonedx-gomod)" || die "cyclonedx-gomod is not on PATH — run 'make security-tools' (pins $CYCLONEDX_GOMOD_VERSION)"
      HAVE="$(cyclonedx-gomod version 2>/dev/null | awk '$1=="Version:" {print $2}')"
      [ "$HAVE" = "$CYCLONEDX_GOMOD_VERSION" ] || die "cyclonedx-gomod at $BIN is ${HAVE:-unknown}, the pin is \
$CYCLONEDX_GOMOD_VERSION (ops/security/tool-versions.sh). Run 'make security-tools'. A manifest from an \
unknown generator is an inventory of an unknown tree."
      # -licenses runs the tool's own detection. We deliberately do NOT add
      # -assert-licenses: its documentation says the detected licences are
      # reported as evidence "because it can not be guaranteed that the
      # detected licenses are in fact correct", and the license-audit row reads
      # both fields — so the document keeps that distinction instead of
      # flattening it into an assertion the generator does not make.
      cyclonedx-gomod mod -json -licenses -output "$DEST/go.cdx.json" . >"$DEST/go.log" 2>&1
      rc=$?
      [ "$rc" -eq 0 ] || { tail -20 "$DEST/go.log" | sed 's/^/     /'; die "sbom-go: cyclonedx-gomod exited $rc"; }
    else
      echo "     reuse: validating $DEST/go.cdx.json as it is (POST_SBOM_REUSE)"
    fi
    check go "cyclonedx-gomod $CYCLONEDX_GOMOD_VERSION (go.mod, license evidence included)" || exit 1
    ;;

  node)
    have pnpm || die "pnpm is not on PATH (the workspace pins it in package.json)"
    [ -d node_modules ] || die "node_modules is missing. pnpm's SBOM reads the INSTALLED workspace, and without \
it the document has no licence data at all (every component would read as unlicensed). Run \
'pnpm install --frozen-lockfile' first — 'make security-tools' does that for you."
    if [ -z "${POST_SBOM_REUSE:-}" ]; then
      HAVE="$(pnpm --version)"
      PIN="$(node -p "require('./package.json').packageManager.replace(/^pnpm@/, '')" 2>/dev/null)"
      [ "$HAVE" = "$PIN" ] || die "pnpm at $(command -v pnpm) is $HAVE, package.json pins pnpm@$PIN. Install the \
workspace's own package manager rather than whichever pnpm happens to be on PATH."
      pnpm sbom --sbom-format cyclonedx --sbom-spec-version 1.5 --out "$DEST/node.cdx.json" >"$DEST/node.log" 2>&1
      rc=$?
      [ "$rc" -eq 0 ] || { tail -20 "$DEST/node.log" | sed 's/^/     /'; die "sbom-node: pnpm sbom exited $rc"; }
    else
      echo "     reuse: validating $DEST/node.cdx.json as it is (POST_SBOM_REUSE)"
    fi
    HAVE_PNPM="$(pnpm --version)"
    check node "pnpm $HAVE_PNPM sbom (pnpm-lock.yaml, CycloneDX 1.5)" || exit 1
    ;;

  python)
    have uv || die "uv is not on PATH (services/scientific-adapter pins it as its package manager)"
    ADAPTER="services/scientific-adapter"
    [ -f "$ADAPTER/uv.lock" ] || die "no $ADAPTER/uv.lock"
    VENV="$ADAPTER/.venv"
    [ -d "$VENV" ] || die "$VENV does not exist. The Python face's licence data comes from the installed \
distributions' METADATA, and 'uv export' alone carries no licence at all. Run 'uv sync --frozen' in \
$ADAPTER first — 'make security-tools' does that for you."
    HAVE="$(uv --version | awk '{print $2}')"
    if [ -z "${POST_SBOM_REUSE:-}" ]; then
      # uv export resolves the project's own pyproject.toml, so it has to run
      # from the adapter's directory; the output path stays absolute.
      ( cd "$ADAPTER" && uv export --frozen --no-emit-project --format cyclonedx1.5 -o "$DEST/python.raw.json" ) \
        >"$DEST/python.log" 2>&1
      rc=$?
      [ "$rc" -eq 0 ] || { tail -20 "$DEST/python.log" | sed 's/^/     /'; die "sbom-python: uv export exited $rc"; }
      python3 tests/security/sbom_python_licenses.py \
        --raw "$DEST/python.raw.json" --venv "$VENV" --out "$DEST/python.cdx.json" || exit 1
    else
      echo "     reuse: validating $DEST/python.cdx.json as it is (POST_SBOM_REUSE)"
    fi
    check python "uv $HAVE export --format cyclonedx1.5 + licenses from $VENV dist-info METADATA" || exit 1
    ;;

  ""|-h|--help) usage;;
  *) echo "sbom: unknown face '$1' (expected go, node or python)" >&2; exit 2;;
esac
