package devorchestrator

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

// The guard layer is generated per spawn into the task's runtime dir: the
// canonical worker-guard.sh (embedded, drift-checked against
// .rddev.example/guard/worker-guard.sh), worker-settings.json (Claude Code
// permissions: dontAsk + deny list + the PreToolUse hook wiring) and
// run-worker.sh (the reaper wrapper that keeps the claude process alive past
// rddev's own exit and records its exit code).

//go:embed embed/worker-guard.sh
var guardScript string

// GuardScript returns the embedded canonical worker-guard.sh.
func GuardScript() string { return guardScript }

// GuardOpts parametrizes the generated guard files.
type GuardOpts struct {
	RepoRoot    string
	TaskID      string
	Worktree    string
	ResultDir   string
	DockerGrant bool
}

// denyRules is the blunt Claude Code permission layer (the hook is the
// precision layer, L1-20260912-9). Everything here is unconditionally
// control-plane; docker is NOT denied at this layer because the hook must be
// able to allow version queries (deny would block before the hook decides).
func denyRules() []string {
	return []string{
		"Bash(git commit:*)",
		"Bash(git push:*)",
		"Bash(git merge:*)",
		"Bash(git rebase:*)",
		"Bash(git tag:*)",
		"Bash(git cherry-pick:*)",
		"Bash(git branch -D:*)",
		"Bash(git branch --delete:*)",
		"Bash(git branch -m:*)",
		"Bash(git branch --move:*)",
		"Bash(git worktree:*)",
		"Bash(git remote add:*)",
		"Bash(git remote set-url:*)",
		"Bash(git remote prune:*)",
		"Bash(git config:*)",
		"Bash(git fetch:*)",
		"Bash(git pull:*)",
		"Bash(git init:*)",
		"Bash(git clone:*)",
		"Bash(git stash:*)",
		"Bash(git reset:*)",
		"Bash(git revert:*)",
		"Bash(git am:*)",
		"Bash(git submodule:*)",
		"Bash(gh:*)",
		"Bash(glab:*)",
		"Bash(tea:*)",
		"Bash(sudo:*)",
		"Bash(su:*)",
		"Bash(doas:*)",
		"Bash(pkexec:*)",
	}
}

// workerSettings is the generated worker-settings.json document.
type workerSettings struct {
	Permissions struct {
		DefaultMode string   `json:"defaultMode"`
		Allow       []string `json:"allow"`
		Deny        []string `json:"deny"`
		Ask         []string `json:"ask"`
	} `json:"permissions"`
	Hooks struct {
		PreToolUse []struct {
			Matcher string `json:"matcher"`
			Hooks   []struct {
				Type    string `json:"type"`
				Command string `json:"command"`
			} `json:"hooks"`
		} `json:"PreToolUse"`
	} `json:"hooks"`
}

// renderSettings builds the worker-settings.json content. Write/Edit are
// allowed bare, exactly like the dispatch harness this ports (its settings,
// observed live on this very session, let the Write tool write outside the
// worker cwd in dontAsk mode). That is deliberate: claude 2.1.269 does NOT
// honor path-scoped Write/Edit allow rules in dontAsk mode — two real-claude
// probes with absolute and env: rules (Write(/tmp/x/**),
// Write(env:POST_WORKER_RESULT_DIR/**)) denied every write, allowed path
// included. Path-scoped rules in the allow list would be dead rules that
// read as confinement without providing any (worse than none). The write
// envelope is enforced where it works: the guard hook, for shell writes and
// for the Write/Edit tools guardMatcher names, plus the collect-time
// allowed_scope diff for the worktree. A path-scoped entry must never
// reappear without re-proving it on the pinned claude version (test below).
func renderSettings(guardPath string) ([]byte, error) {
	var s workerSettings
	s.Permissions.DefaultMode = "dontAsk"
	s.Permissions.Allow = []string{"Bash", "Write", "Edit"}
	s.Permissions.Deny = denyRules()
	s.Permissions.Ask = []string{}
	s.Hooks.PreToolUse = []struct {
		Matcher string `json:"matcher"`
		Hooks   []struct {
			Type    string `json:"type"`
			Command string `json:"command"`
		} `json:"hooks"`
	}{{
		Matcher: guardMatcher,
		Hooks: []struct {
			Type    string `json:"type"`
			Command string `json:"command"`
		}{{
			Type:    "command",
			Command: "sh " + guardPath,
		}},
	}}
	out, err := json.MarshalIndent(&s, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encoding worker settings: %w", err)
	}
	return append(out, '\n'), nil
}

// renderReaper renders run-worker.sh: claude is backgrounded (under the
// caller-provided command line, optionally wrapped in `timeout`), claude.pid
// is written, the Worker's identity is printed for rddev to record, and
// exit.status is written twice — the task dir and the Supervisor-owned
// authoritative runtime dir (arg 5, T0012: the copy collect trusts must not
// live where the Worker can rewrite it). rddev launches it detached and never
// waits for it. The code is on disk BEFORE the cleanup and this script is the
// only writer, so readers wait on it stopping (#243, worker_exit_timing.go).
const reaperScript = `#!/bin/bash
# run-worker.sh — generated by rddev worker spawn. Reaper wrapper: keeps the
# claude process alive after rddev exits and records its exit code.
set -u
# Job control: the Worker becomes its own process group (its group id is its
# pid), so the collection at the end can signal exactly the Worker and
# everything it started, and never this wrapper (#166).
set -m
worktree=$1; log=$2; pidfile=$3; statusfile=$4; authstatus=${5:-}; shift 5
cd "$worktree" || { echo 125 > "$statusfile"; echo "run-worker: cannot cd to $worktree" >&2; exit 125; }
"$@" >"$log" 2>&1 &
pid=$!
echo "$pid" > "$pidfile"
echo "$pid $(awk '{sub(/^.*\)/,"");print $20}' "/proc/$pid/stat" 2>/dev/null)"
wait "$pid"
code=$?
# The authoritative copy is written FIRST: any observer that sees the
# task-dir copy already written is guaranteed to see the authoritative copy
# too (program order), so collect can never read a fresh task-dir copy next
# to a stale authoritative one (the rework false-tamper race, T0012).
if [ -n "$authstatus" ]; then
  mkdir -p "$(dirname "$authstatus")" 2>/dev/null || true
  echo "$code" > "$authstatus" 2>/dev/null || true
fi
echo "$code" > "$statusfile"
# Collect the Worker's whole group (negative pid = the group, whose id is the
# Worker's pid thanks to the job-control line above). The exit code is on
# disk BEFORE this runs, so a cleanup that fails can never cost the record of
# how the Worker ended.
#
# The session is rddev's own unit of collection — spawn sets Setsid for
# exactly that reason — but nothing ever collected it. The worker-stop path
# signals the recorded Worker pid, and a positive pid signals one process,
# never its group; a Worker that exits on its own got no signal at all.
# Anything it started therefore outlived it, silently: a runaway probe pinned
# a core for twelve minutes inside review collect (#166), and a Reviewer kept
# spinning on a cwd that had been deleted under it. Nothing is meant to
# outlive the Worker — the residue that motivated this was an accident of a
# Worker's own shell, never a service anyone asked to keep.
#
# TERM first, then KILL for whatever ignores it. The Worker itself has
# already exited, so this only reaches what it left behind.
kill -TERM -- "-$pid" 2>/dev/null || true
sleep 1
kill -KILL -- "-$pid" 2>/dev/null || true
`

// WriteGuardFiles writes guard/worker-guard.sh, worker-settings.json and
// run-worker.sh into dir (the per-task runtime dir).
func WriteGuardFiles(dir string, opts GuardOpts) (guardPath string, err error) {
	guardDir := filepath.Join(dir, "guard")
	if err := os.MkdirAll(guardDir, 0o755); err != nil {
		return "", err
	}
	guardPath = filepath.Join(guardDir, "worker-guard.sh")
	if err := os.WriteFile(guardPath, []byte(guardScript), 0o755); err != nil {
		return "", err
	}
	settings, err := renderSettings(guardPath)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(dir, "worker-settings.json"), settings, 0o644); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(dir, "run-worker.sh"), []byte(reaperScript), 0o755); err != nil {
		return "", err
	}
	return guardPath, nil
}

// claudeArgs assembles the claude command line from the spawn options. The
// prompt is passed as the -p argument (task packages are a few KB, far below
// ARG_MAX), and the stream-json log is what hang detection measures
// (L1-20260912-7). The RESULT contract is mechanically enforced from the
// start (T0011): --json-schema forces the Worker's final message through
// claude's StructuredOutput validation against worker-result.schema.json
// (live-probed on 2.1.269: the model is made to call a StructuredOutput tool
// whose payload the harness validates against the schema), instead of the
// contract being prose the Worker may ignore.
func claudeArgs(opts *SpawnOpts, sessionID, settingsPath, systemPath, prompt, resultSchema string) ([]string, error) {
	args := []string{
		"-p", prompt,
		"--name", "rddev-worker-" + opts.TaskID,
	}
	// --session-id names a session this invocation CREATES. Passing it
	// alongside --resume is contradictory, and real claude (2.1.269) refuses
	// the entire invocation:
	//   "Error: --session-id can only be used with --continue or --resume if
	//    --fork-session is also specified."
	// A rework resumes the Worker's own session rather than naming a new one,
	// and --resume carries the identity, so the flag is only added when no
	// resume is happening. Found by running `rddev worker rework` for real:
	// every rework died at startup with exit 1 and a 125-byte log, because the
	// path had only ever been exercised against a stubbed claude.
	if opts.ResumeSession == "" {
		args = append(args, "--session-id", sessionID)
	}
	args = append(args,
		"--permission-mode", "dontAsk",
		"--permission-prompts", "none",
		// T0011 Defect 1: without this, the Worker's claude loads
		// ~/.claude/settings.json, whose env block can re-inject credentials
		// BuildWorkerEnv just stripped (the live probe found
		// GITHUB_PERSONAL_ACCESS_TOKEN PRESENT in a Worker env). Project
		// settings only: the task's worker-settings.json (passed via
		// --settings, verified live) still loads — user/local settings cannot
		// inject env into a Worker.
		"--setting-sources", "project",
		// real claude (2.1.269) refuses -p + stream-json without --verbose:
		// "Error: When using --print, --output-format=stream-json requires
		// --verbose" (caught by the real-claude e2e run, exit 1)
		"--output-format", "stream-json",
		"--verbose",
		"--json-schema", resultSchema,
		"--append-system-prompt-file", systemPath,
		"--settings", settingsPath,
	)
	// A rework resumes the Worker's own session — the same Worker continues
	// with its context intact (T0012: first rejection = rework same Worker).
	if opts.ResumeSession != "" {
		args = append(args, "--resume", opts.ResumeSession)
	}
	if opts.Bare {
		// --bare skips CLAUDE.md auto-discovery; the task package + system.md
		// are the Worker's entire context.
		args = append(args, "--bare")
	}
	if opts.Model != "" {
		args = append(args, "--model", opts.Model)
	}
	if opts.Effort != "" {
		args = append(args, "--effort", opts.Effort)
	}
	if opts.MaxBudgetUSD != nil {
		args = append(args, "--max-budget-usd", strconv.FormatFloat(*opts.MaxBudgetUSD, 'f', -1, 64))
	}
	if opts.MaxTurns != nil {
		args = append(args, "--max-turns", strconv.Itoa(*opts.MaxTurns))
	}
	return args, nil
}

// wrapTimeout prefixes the full command (binary + args) with the timeout
// wrapper. It is applied by Spawn around the whole command the reaper starts
// — the wrapper must sit in front of the claude binary, not inside its args.
// resultSchemaForCLI returns the repo's worker-result.schema.json as the
// inline --json-schema argument. --json-schema takes inline JSON, not a
// path, and claude 2.1.269 rejects the draft-2020-12 $schema URI ("no schema
// with key or ref ..."), so the header metadata keys are stripped; every
// validation keyword is passed through untouched. The transform is
// deterministic (the schema is the repo's own), and a missing or unparseable
// schema fails spawn instead of spawning an unenforced Worker.
func resultSchemaForCLI(repoRoot string) (string, error) {
	return resultSchemaAtForCLI(filepath.Join(repoRoot, "specs", "orchestrator", "worker-result.schema.json"))
}

// resultSchemaAtForCLI is the same transform for an arbitrary schema path
// (the Review Worker enforces review-verdict.schema.json instead).
func resultSchemaAtForCLI(schemaPath string) (string, error) {
	data, err := os.ReadFile(schemaPath)
	if err != nil {
		return "", fmt.Errorf("reading the RESULT schema for --json-schema: %w", err)
	}
	var doc map[string]any
	if err := json.Unmarshal(data, &doc); err != nil {
		return "", fmt.Errorf("parsing %s: %w", schemaPath, err)
	}
	for _, k := range []string{"$schema", "$id", "title"} {
		delete(doc, k)
	}
	out, err := json.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("encoding the RESULT schema for --json-schema: %w", err)
	}
	return string(out), nil
}

func wrapTimeout(dur time.Duration, claudeBin string, args []string) []string {
	return append([]string{"timeout", "--signal=TERM", "--kill-after=15", formatDuration(dur), claudeBin}, args...)
}

func formatDuration(d time.Duration) string {
	if d%time.Hour == 0 {
		return fmt.Sprintf("%dh", d/time.Hour)
	}
	if d%time.Minute == 0 {
		return fmt.Sprintf("%dm", d/time.Minute)
	}
	return fmt.Sprintf("%ds", d/time.Second)
}

// guardMatcher is the PreToolUse matcher: the tool names that reach
// worker-guard.sh, wired into worker-settings.json by renderSettings above.
// It is the seam the whole hook hangs on — a tool absent from it is a tool
// the guard never sees, whatever the guard's own text says it enforces.
//
// It listed Bash|Read|Grep|Glob|NotebookRead until T1219, while
// permissions.allow carried Write and Edit. dontAsk therefore ran those two
// bare and the hook was never invoked for them, so the write envelope the
// guard documents (worktree / result dir / /tmp) did not hold for the two
// tools most likely to be used to leave it. Reproduced live before the fix: a
// real claude session driven by this exact generated settings file wrote
// .rddev/runtime/tasks/<TASK>/gate-inputs.json through the Write tool and
// reported CREATED-OK — the authoritative record collect reads allowed_scope
// from. The same probe against the fixed matcher is refused.
//
// Why this declaration sits at the END of the file rather than beside
// renderSettings: ops/ci/gosec-baseline.txt keys its entries by
// `path:line:column:RULE`, so inserting a line anywhere above a baselined
// finding in this file makes that finding unbaselined and reds the sast-go
// row (T1217 hit this). ops/** is Supervisor-owned, so the file that could
// re-number the baseline is not one this change may touch; the comment comes
// last instead of the baseline coming first.
//
// The list is derived, not remembered: every tool a Worker can point at a
// path must be here. TestWriteGuardFiles derives that requirement from
// permissions.allow itself, and TestGuardMatcherNamesExactlyTheKnownTools
// fixes the set in both directions — a future tool that becomes allowed
// without becoming visible fails a test instead of silently escaping the
// envelope the way Write and Edit did.
//
// Tools that are NOT here are not a second, quieter way around the guard:
//
//   - Read/Grep/Glob/NotebookRead are matched AND refused outright by the
//     permission layer (they are absent from allow, and dontAsk denies an
//     unlisted tool — probed live on 2.1.281: "Permission to use Read has
//     been denied because Claude Code is running in don't ask mode"). They
//     stay in the matcher so the read confinement holds at the hook too, and
//     so it survives them ever being allowed.
//   - NotebookEdit/MultiEdit are matched for the same reason: the permission
//     layer refuses them today, and matching them costs nothing while making
//     the envelope independent of that accident.
//   - Non-file tools (Task, TodoWrite, WebFetch, StructuredOutput, Skill, …)
//     name no path, so no path policy applies to them. An unknown tool name
//     exits the guard silently by design (see the hook-protocol note in
//     embed/worker-guard.sh).
//
// Route NOT taken (T1219): generating a path-scoped permissions.deny from the
// absolute worktree path, which spawn knows at generation time. Deny can only
// express the complement of an envelope, never the envelope: "worktree, result
// dir and /tmp" would have to be written as "everything else", an unbounded
// list that fails open on every path nobody enumerated. An allow-list is what
// this envelope needs, and path-scoped allow rules are the dead rule
// renderSettings documents above, so the hook is the only layer that can
// express it and one route is enough.
const guardMatcher = "Bash|Read|Grep|Glob|NotebookRead|Write|Edit|MultiEdit|NotebookEdit"
