package devorchestrator

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

// The guard layer is generated per spawn into the task's runtime dir: the
// canonical worker-guard.sh (embedded, drift-checked against
// .rddev.example/guard/worker-guard.sh), worker-settings.json (Claude Code
// permissions: dontAsk + deny list + the PreToolUse hook wiring) and
// run-worker.sh (the reaper wrapper that keeps the claude process alive past
// rddev's own exit and records its exit code).

//go:embed embed/worker-guard.sh
var guardScript string

// GuardScript returns the embedded canonical worker-guard.sh.
func GuardScript() string { return guardScript }

// GuardOpts parametrizes the generated guard files.
type GuardOpts struct {
	RepoRoot    string
	TaskID      string
	Worktree    string
	ResultDir   string
	DockerGrant bool
}

// denyRules is the blunt Claude Code permission layer (the hook is the
// precision layer, L1-20260912-9). Everything here is unconditionally
// control-plane; docker is NOT denied at this layer because the hook must be
// able to allow version queries (deny would block before the hook decides).
func denyRules() []string {
	return []string{
		"Bash(git commit:*)",
		"Bash(git push:*)",
		"Bash(git merge:*)",
		"Bash(git rebase:*)",
		"Bash(git tag:*)",
		"Bash(git cherry-pick:*)",
		"Bash(git branch -D:*)",
		"Bash(git branch --delete:*)",
		"Bash(git branch -m:*)",
		"Bash(git branch --move:*)",
		"Bash(git worktree:*)",
		"Bash(git remote add:*)",
		"Bash(git remote set-url:*)",
		"Bash(git remote prune:*)",
		"Bash(git config:*)",
		"Bash(git fetch:*)",
		"Bash(git pull:*)",
		"Bash(git init:*)",
		"Bash(git clone:*)",
		"Bash(git stash:*)",
		"Bash(git reset:*)",
		"Bash(git revert:*)",
		"Bash(git am:*)",
		"Bash(git submodule:*)",
		"Bash(gh:*)",
		"Bash(glab:*)",
		"Bash(tea:*)",
		"Bash(sudo:*)",
		"Bash(su:*)",
		"Bash(doas:*)",
		"Bash(pkexec:*)",
	}
}

// workerSettings is the generated worker-settings.json document.
type workerSettings struct {
	Permissions struct {
		DefaultMode string   `json:"defaultMode"`
		Allow       []string `json:"allow"`
		Deny        []string `json:"deny"`
		Ask         []string `json:"ask"`
	} `json:"permissions"`
	Hooks struct {
		PreToolUse []struct {
			Matcher string `json:"matcher"`
			Hooks   []struct {
				Type    string `json:"type"`
				Command string `json:"command"`
			} `json:"hooks"`
		} `json:"PreToolUse"`
	} `json:"hooks"`
}

// renderSettings builds the worker-settings.json content. Write/Edit are
// allowed bare, exactly like the dispatch harness this ports (its settings,
// observed live on this very session, let the Write tool write outside the
// worker cwd in dontAsk mode). That is deliberate: claude 2.1.269 does NOT
// honor path-scoped Write/Edit allow rules in dontAsk mode — two real-claude
// probes with absolute and env: rules (Write(/tmp/x/**),
// Write(env:POST_WORKER_RESULT_DIR/**)) denied every write, allowed path
// included. Path-scoped rules in the allow list would be dead rules that
// read as confinement without providing any (worse than none). The write
// envelope is enforced where it actually works: the guard hook for shell
// writes, and the collect-time allowed_scope diff for the worktree. A
// path-scoped entry must never reappear without re-proving it on the pinned
// claude version (test below asserts this).
func renderSettings(guardPath string) ([]byte, error) {
	var s workerSettings
	s.Permissions.DefaultMode = "dontAsk"
	s.Permissions.Allow = []string{"Bash", "Write", "Edit"}
	s.Permissions.Deny = denyRules()
	s.Permissions.Ask = []string{}
	s.Hooks.PreToolUse = []struct {
		Matcher string `json:"matcher"`
		Hooks   []struct {
			Type    string `json:"type"`
			Command string `json:"command"`
		} `json:"hooks"`
	}{{
		Matcher: "Bash|Read|Grep|Glob|NotebookRead",
		Hooks: []struct {
			Type    string `json:"type"`
			Command string `json:"command"`
		}{{
			Type:    "command",
			Command: "sh " + guardPath,
		}},
	}}
	out, err := json.MarshalIndent(&s, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encoding worker settings: %w", err)
	}
	return append(out, '\n'), nil
}

// renderReaper renders run-worker.sh. The script backgrounds claude (under
// the caller-provided command line, optionally wrapped in `timeout`), writes
// claude.pid, prints the pid to stdout for rddev to record, waits, and writes
// exit.status. rddev launches it detached (new session) and never waits for
// it, so the Worker survives a Supervisor-side rddev exit and the exit code
// is always recorded by the reaper itself.
const reaperScript = `#!/bin/bash
# run-worker.sh — generated by rddev worker spawn. Reaper wrapper: keeps the
# claude process alive after rddev exits and records its exit code.
set -u
worktree=$1; log=$2; pidfile=$3; statusfile=$4; shift 4
cd "$worktree" || { echo 125 > "$statusfile"; echo "run-worker: cannot cd to $worktree" >&2; exit 125; }
"$@" >"$log" 2>&1 &
pid=$!
echo "$pid" > "$pidfile"
echo "$pid"
wait "$pid"
echo "$?" > "$statusfile"
`

// WriteGuardFiles writes guard/worker-guard.sh, worker-settings.json and
// run-worker.sh into dir (the per-task runtime dir).
func WriteGuardFiles(dir string, opts GuardOpts) (guardPath string, err error) {
	guardDir := filepath.Join(dir, "guard")
	if err := os.MkdirAll(guardDir, 0o755); err != nil {
		return "", err
	}
	guardPath = filepath.Join(guardDir, "worker-guard.sh")
	if err := os.WriteFile(guardPath, []byte(guardScript), 0o755); err != nil {
		return "", err
	}
	settings, err := renderSettings(guardPath)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(dir, "worker-settings.json"), settings, 0o644); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(dir, "run-worker.sh"), []byte(reaperScript), 0o755); err != nil {
		return "", err
	}
	return guardPath, nil
}

// claudeArgs assembles the claude command line from the spawn options. The
// prompt is passed as the -p argument (task packages are a few KB, far below
// ARG_MAX), and the stream-json log is what hang detection measures
// (L1-20260912-7).
func claudeArgs(opts *SpawnOpts, sessionID, settingsPath, systemPath, prompt string) ([]string, error) {
	args := []string{
		"-p", prompt,
		"--name", "rddev-worker-" + opts.TaskID,
		"--session-id", sessionID,
		"--permission-mode", "dontAsk",
		"--permission-prompts", "none",
		// real claude (2.1.269) refuses -p + stream-json without --verbose:
		// "Error: When using --print, --output-format=stream-json requires
		// --verbose" (caught by the real-claude e2e run, exit 1)
		"--output-format", "stream-json",
		"--verbose",
		"--append-system-prompt-file", systemPath,
		"--settings", settingsPath,
	}
	if opts.Bare {
		// --bare skips CLAUDE.md auto-discovery; the task package + system.md
		// are the Worker's entire context.
		args = append(args, "--bare")
	}
	if opts.Model != "" {
		args = append(args, "--model", opts.Model)
	}
	if opts.Effort != "" {
		args = append(args, "--effort", opts.Effort)
	}
	if opts.MaxBudgetUSD != nil {
		args = append(args, "--max-budget-usd", strconv.FormatFloat(*opts.MaxBudgetUSD, 'f', -1, 64))
	}
	if opts.MaxTurns != nil {
		args = append(args, "--max-turns", strconv.Itoa(*opts.MaxTurns))
	}
	return args, nil
}

// wrapTimeout prefixes the full command (binary + args) with the timeout
// wrapper. It is applied by Spawn around the whole command the reaper starts
// — the wrapper must sit in front of the claude binary, not inside its args.
func wrapTimeout(dur time.Duration, claudeBin string, args []string) []string {
	return append([]string{"timeout", "--signal=TERM", "--kill-after=15", formatDuration(dur), claudeBin}, args...)
}

func formatDuration(d time.Duration) string {
	if d%time.Hour == 0 {
		return fmt.Sprintf("%dh", d/time.Hour)
	}
	if d%time.Minute == 0 {
		return fmt.Sprintf("%dm", d/time.Minute)
	}
	return fmt.Sprintf("%ds", d/time.Second)
}
