// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_publish.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetPublishCreation = `-- name: CreateAssetPublishCreation :one
INSERT INTO asset_publish_creations (project_id, idempotency_key, asset_version_id)
VALUES ($1, $2, $3)
RETURNING id, project_id, idempotency_key, asset_version_id, created_at
`

type CreateAssetPublishCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	AssetVersionID pgtype.UUID `json:"asset_version_id"`
}

// The ledger row, written in the same transaction as the version it
// names: a publish that rolled back leaves no key behind, and a key that
// committed names a version that exists.
func (q *Queries) CreateAssetPublishCreation(ctx context.Context, arg CreateAssetPublishCreationParams) (AssetPublishCreation, error) {
	row := q.db.QueryRow(ctx, createAssetPublishCreation, arg.ProjectID, arg.IdempotencyKey, arg.AssetVersionID)
	var i AssetPublishCreation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.AssetVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createResearchAssetWithPID = `-- name: CreateResearchAssetWithPID :one

INSERT INTO research_assets (asset_type, slug, title, origin_project_id, pid)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, asset_type, slug, title, origin_project_id, created_at, pid, description, keywords, contact, documentation, cover_blob_id
`

type CreateResearchAssetWithPIDParams struct {
	AssetType       string      `json:"asset_type"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	OriginProjectID pgtype.UUID `json:"origin_project_id"`
	Pid             string      `json:"pid"`
}

// Research asset publish governance (T0705): the writes and the ledger
// reads of the publish command, plus the one read a replay needs.
//
// The publish is the platform's highest-risk operation (docs/23 §4): it
// widens a private artifact into the network's view and its result is an
// immutable version row. Every write below happens inside ONE transaction
// (persistence.AssetPublishStore.Publish) together with the impact
// re-check that authorized it, the audit row and the domain event, so a
// refused publish writes nothing and an accepted one is one unit.
//
// The reads the impact preview is re-run over are NOT here: they are the
// preview's own canonical queries (asset_preview.sql), reused verbatim so
// that the preview a human saw and the preview the publish re-runs are
// answered by one SQL definition. What this file adds is the ledger
// (asset_publish_creations, migration 00072) and the two rows a publish
// writes.
// A publish that names no existing asset creates one, and the pid it is
// created with comes from the application (assets.NewPID, migration
// 00064's note: "the application-generated path ... arrives with T0705
// (publish)"): the column DEFAULT exists for rows written before the
// publish command could generate one, and a persistent identifier that
// two writers derive differently is not a persistent identity.
func (q *Queries) CreateResearchAssetWithPID(ctx context.Context, arg CreateResearchAssetWithPIDParams) (ResearchAsset, error) {
	row := q.db.QueryRow(ctx, createResearchAssetWithPID,
		arg.AssetType,
		arg.Slug,
		arg.Title,
		arg.OriginProjectID,
		arg.Pid,
	)
	var i ResearchAsset
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.Slug,
		&i.Title,
		&i.OriginProjectID,
		&i.CreatedAt,
		&i.Pid,
		&i.Description,
		&i.Keywords,
		&i.Contact,
		&i.Documentation,
		&i.CoverBlobID,
	)
	return i, err
}

const getAssetPublishCreation = `-- name: GetAssetPublishCreation :one
SELECT asset_version_id FROM asset_publish_creations
WHERE project_id = $1 AND idempotency_key = $2
`

type GetAssetPublishCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// The publish ledger lookup: the version an Idempotency-Key already
// created, or no row (pgx.ErrNoRows) when the key is new. UNIQUE(project
// _id, idempotency_key) makes this at most one row by construction.
func (q *Queries) GetAssetPublishCreation(ctx context.Context, arg GetAssetPublishCreationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAssetPublishCreation, arg.ProjectID, arg.IdempotencyKey)
	var asset_version_id pgtype.UUID
	err := row.Scan(&asset_version_id)
	return asset_version_id, err
}

const getPublishedAssetVersion = `-- name: GetPublishedAssetVersion :one
SELECT rav.id,
       rav.asset_id,
       ra.pid AS asset_pid,
       rav.version,
       rav.source_release_id,
       rav.manifest,
       rav.rights_json,
       rav.visibility,
       rav.integrity_hash,
       rav.published_by,
       rav.published_at,
       rav.origin_refs
FROM research_asset_versions rav
JOIN research_assets ra ON ra.id = rav.asset_id
WHERE rav.id = $1
`

type GetPublishedAssetVersionRow struct {
	ID              pgtype.UUID        `json:"id"`
	AssetID         pgtype.UUID        `json:"asset_id"`
	AssetPid        string             `json:"asset_pid"`
	Version         string             `json:"version"`
	SourceReleaseID pgtype.UUID        `json:"source_release_id"`
	Manifest        []byte             `json:"manifest"`
	RightsJson      []byte             `json:"rights_json"`
	Visibility      string             `json:"visibility"`
	IntegrityHash   string             `json:"integrity_hash"`
	PublishedBy     pgtype.UUID        `json:"published_by"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	OriginRefs      []string           `json:"origin_refs"`
}

// One stored version WITH the persistent identity of its asset. A replay
// answers the version the key created, and the caller of a publish needs
// the asset's pid to say which asset was published — it is not derivable
// from the version row, whose asset_id is the internal uuid.
//
// The join is an inner one on a NOT NULL foreign key: every version row
// has exactly one asset row.
func (q *Queries) GetPublishedAssetVersion(ctx context.Context, id pgtype.UUID) (GetPublishedAssetVersionRow, error) {
	row := q.db.QueryRow(ctx, getPublishedAssetVersion, id)
	var i GetPublishedAssetVersionRow
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.AssetPid,
		&i.Version,
		&i.SourceReleaseID,
		&i.Manifest,
		&i.RightsJson,
		&i.Visibility,
		&i.IntegrityHash,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.OriginRefs,
	)
	return i, err
}

const getResearchAssetByPIDRow = `-- name: GetResearchAssetByPIDRow :one
SELECT id, asset_type, slug, title, origin_project_id, created_at, pid, description, keywords, contact, documentation, cover_blob_id FROM research_assets WHERE pid = $1
`

// The asset row behind a pid, in full. GetPreviewAssetByPID (the
// preview's own read) answers the three fields the preview checks; the
// publish also needs the row's id to write the version's foreign key and
// its slug to tell a create from a continuation.
func (q *Queries) GetResearchAssetByPIDRow(ctx context.Context, pid string) (ResearchAsset, error) {
	row := q.db.QueryRow(ctx, getResearchAssetByPIDRow, pid)
	var i ResearchAsset
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.Slug,
		&i.Title,
		&i.OriginProjectID,
		&i.CreatedAt,
		&i.Pid,
		&i.Description,
		&i.Keywords,
		&i.Contact,
		&i.Documentation,
		&i.CoverBlobID,
	)
	return i, err
}
