// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachBlob = `-- name: AttachBlob :exec
INSERT INTO blob_attachments (blob_id, scientific_object_version_id, attachment_role, access_level, state_id)
VALUES ($1, $2, $3, $4, $5)
`

type AttachBlobParams struct {
	BlobID                    pgtype.UUID `json:"blob_id"`
	ScientificObjectVersionID pgtype.UUID `json:"scientific_object_version_id"`
	AttachmentRole            string      `json:"attachment_role"`
	AccessLevel               string      `json:"access_level"`
	StateID                   pgtype.UUID `json:"state_id"`
}

// The attachment records the state it was created in (00035): the caller
// (a state commit's write function) passes the state being committed, so
// a state's manifest enumerates its blob attachments from the state id
// alone (internal/domain/state.go).
func (q *Queries) AttachBlob(ctx context.Context, arg AttachBlobParams) error {
	_, err := q.db.Exec(ctx, attachBlob,
		arg.BlobID,
		arg.ScientificObjectVersionID,
		arg.AttachmentRole,
		arg.AccessLevel,
		arg.StateID,
	)
	return err
}

const createBlob = `-- name: CreateBlob :one

INSERT INTO blobs (content_hash, size_bytes, media_type, storage_key, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, content_hash, size_bytes, media_type, storage_key, integrity_state, created_by, created_at
`

type CreateBlobParams struct {
	ContentHash string      `json:"content_hash"`
	SizeBytes   int64       `json:"size_bytes"`
	MediaType   *string     `json:"media_type"`
	StorageKey  string      `json:"storage_key"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

// Blobs and their attachments (canonical tables: blobs, blob_attachments).
// Blob rows are metadata only; bytes live in S3/MinIO (invariant 7: knowledge
// visibility != blob accessibility).
func (q *Queries) CreateBlob(ctx context.Context, arg CreateBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, createBlob,
		arg.ContentHash,
		arg.SizeBytes,
		arg.MediaType,
		arg.StorageKey,
		arg.CreatedBy,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.SizeBytes,
		&i.MediaType,
		&i.StorageKey,
		&i.IntegrityState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBlobByContentHash = `-- name: GetBlobByContentHash :one
SELECT id, content_hash, size_bytes, media_type, storage_key, integrity_state, created_by, created_at FROM blobs
WHERE content_hash = $1 AND size_bytes = $2
`

type GetBlobByContentHashParams struct {
	ContentHash string `json:"content_hash"`
	SizeBytes   int64  `json:"size_bytes"`
}

func (q *Queries) GetBlobByContentHash(ctx context.Context, arg GetBlobByContentHashParams) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlobByContentHash, arg.ContentHash, arg.SizeBytes)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.SizeBytes,
		&i.MediaType,
		&i.StorageKey,
		&i.IntegrityState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const markBlobIntegrity = `-- name: MarkBlobIntegrity :exec
UPDATE blobs SET integrity_state = $1
WHERE id = $2
`

type MarkBlobIntegrityParams struct {
	IntegrityState string      `json:"integrity_state"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) MarkBlobIntegrity(ctx context.Context, arg MarkBlobIntegrityParams) error {
	_, err := q.db.Exec(ctx, markBlobIntegrity, arg.IntegrityState, arg.ID)
	return err
}
