// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discussions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscussionComment = `-- name: CreateDiscussionComment :one
INSERT INTO discussion_comments (thread_id, project_id, body, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, thread_id, project_id, body, created_by, created_at, deleted_at, deleted_by
`

type CreateDiscussionCommentParams struct {
	ThreadID  pgtype.UUID `json:"thread_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Body      string      `json:"body"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDiscussionComment(ctx context.Context, arg CreateDiscussionCommentParams) (DiscussionComment, error) {
	row := q.db.QueryRow(ctx, createDiscussionComment,
		arg.ThreadID,
		arg.ProjectID,
		arg.Body,
		arg.CreatedBy,
	)
	var i DiscussionComment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ProjectID,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createDiscussionPromotion = `-- name: CreateDiscussionPromotion :one
INSERT INTO discussion_promotions
    (project_id, thread_id, comment_id, promoted_kind, promoted_ref, promoted_by)
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, thread_id, comment_id, promoted_kind, promoted_ref, promoted_by, promoted_at
`

type CreateDiscussionPromotionParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	ThreadID     pgtype.UUID `json:"thread_id"`
	CommentID    pgtype.UUID `json:"comment_id"`
	PromotedKind string      `json:"promoted_kind"`
	PromotedRef  string      `json:"promoted_ref"`
	PromotedBy   pgtype.UUID `json:"promoted_by"`
}

// One promotion record: the comment that was proposed, what it became,
// who promoted it. promoted_ref is "<kind>:<uuid>" — the CHECK in 00104
// derives the prefix from promoted_kind, so the pair cannot disagree.
func (q *Queries) CreateDiscussionPromotion(ctx context.Context, arg CreateDiscussionPromotionParams) (DiscussionPromotion, error) {
	row := q.db.QueryRow(ctx, createDiscussionPromotion,
		arg.ProjectID,
		arg.ThreadID,
		arg.CommentID,
		arg.PromotedKind,
		arg.PromotedRef,
		arg.PromotedBy,
	)
	var i DiscussionPromotion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ThreadID,
		&i.CommentID,
		&i.PromotedKind,
		&i.PromotedRef,
		&i.PromotedBy,
		&i.PromotedAt,
	)
	return i, err
}

const createDiscussionThread = `-- name: CreateDiscussionThread :one

INSERT INTO discussion_threads (project_id, target_type, target_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, target_type, target_id, created_by, created_at
`

type CreateDiscussionThreadParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	TargetType string      `json:"target_type"`
	TargetID   string      `json:"target_id"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

// Discussion threads, comments and promotions (T0811; canonical tables
// discussion_threads, discussion_comments, discussion_promotions,
// migration 00104).
//
// Every query here touches those three tables and nothing else: no
// statement in this file names scientific_object_versions, relation_versions
// or contribution_events, which is the SQL half of "a comment does not
// change scientific state" (the Go half is that the discussions command
// has no state-commit port at all).
func (q *Queries) CreateDiscussionThread(ctx context.Context, arg CreateDiscussionThreadParams) (DiscussionThread, error) {
	row := q.db.QueryRow(ctx, createDiscussionThread,
		arg.ProjectID,
		arg.TargetType,
		arg.TargetID,
		arg.CreatedBy,
	)
	var i DiscussionThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TargetType,
		&i.TargetID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDiscussionComment = `-- name: GetDiscussionComment :one
SELECT id, thread_id, project_id, body, created_by, created_at, deleted_at, deleted_by FROM discussion_comments
WHERE project_id = $1 AND id = $2
`

type GetDiscussionCommentParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// One comment of one project (same boundary rule as GetDiscussionThread).
func (q *Queries) GetDiscussionComment(ctx context.Context, arg GetDiscussionCommentParams) (DiscussionComment, error) {
	row := q.db.QueryRow(ctx, getDiscussionComment, arg.ProjectID, arg.ID)
	var i DiscussionComment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ProjectID,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getDiscussionKnowledgeTargetProject = `-- name: GetDiscussionKnowledgeTargetProject :one
SELECT so.project_id
FROM knowledge_publications kp
JOIN scientific_object_versions sov ON sov.id = kp.object_version_id
JOIN scientific_objects so ON so.id = sov.object_id
WHERE kp.pid = $1
`

// The project that owns the object a publication pid names (T0811's
// knowledge target check): a thread's knowledge target must be a
// publication OF THE THREAD'S PROJECT, and this resolves the one fact that
// decides it. It is a read of the publication, its version and the object
// that carries it — no visibility predicate: the command's project gate
// has already run the caller's read rule, and a second SQL-shaped copy of
// it is how two answers to "who may see this" start to disagree (the same
// rule knowledgepublish.AudienceFor owns).
func (q *Queries) GetDiscussionKnowledgeTargetProject(ctx context.Context, pid string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDiscussionKnowledgeTargetProject, pid)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const getDiscussionPromotion = `-- name: GetDiscussionPromotion :one
SELECT id, project_id, thread_id, comment_id, promoted_kind, promoted_ref, promoted_by, promoted_at FROM discussion_promotions
WHERE project_id = $1 AND id = $2
`

type GetDiscussionPromotionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetDiscussionPromotion(ctx context.Context, arg GetDiscussionPromotionParams) (DiscussionPromotion, error) {
	row := q.db.QueryRow(ctx, getDiscussionPromotion, arg.ProjectID, arg.ID)
	var i DiscussionPromotion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ThreadID,
		&i.CommentID,
		&i.PromotedKind,
		&i.PromotedRef,
		&i.PromotedBy,
		&i.PromotedAt,
	)
	return i, err
}

const getDiscussionThread = `-- name: GetDiscussionThread :one
SELECT id, project_id, target_type, target_id, created_by, created_at FROM discussion_threads
WHERE project_id = $1 AND id = $2
`

type GetDiscussionThreadParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// One thread of one project. project_id is in the predicate, not a filter
// applied afterwards: a thread id of another project is not-found, never a
// foreign thread (existence hiding, docs/45).
func (q *Queries) GetDiscussionThread(ctx context.Context, arg GetDiscussionThreadParams) (DiscussionThread, error) {
	row := q.db.QueryRow(ctx, getDiscussionThread, arg.ProjectID, arg.ID)
	var i DiscussionThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TargetType,
		&i.TargetID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDiscussionComments = `-- name: ListDiscussionComments :many
SELECT id, thread_id, project_id, body, created_by, created_at, deleted_at, deleted_by FROM discussion_comments
WHERE thread_id = $1
ORDER BY created_at, id
`

// One thread's comments in creation order. Deleted comments are RETURNED:
// the row is never removed (CLAUDE.md §9.8) and the transport renders the
// tombstone; only the body stops being served.
func (q *Queries) ListDiscussionComments(ctx context.Context, threadID pgtype.UUID) ([]DiscussionComment, error) {
	rows, err := q.db.Query(ctx, listDiscussionComments, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscussionComment
	for rows.Next() {
		var i DiscussionComment
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.ProjectID,
			&i.Body,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscussionPromotionsByRef = `-- name: ListDiscussionPromotionsByRef :many
SELECT id, project_id, thread_id, comment_id, promoted_kind, promoted_ref, promoted_by, promoted_at FROM discussion_promotions
WHERE project_id = $1
  AND promoted_kind = $2
  AND promoted_ref = $3
ORDER BY promoted_at, id
`

type ListDiscussionPromotionsByRefParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	PromotedKind string      `json:"promoted_kind"`
	PromotedRef  string      `json:"promoted_ref"`
}

// The reverse read: every promotion that produced the object a ref names,
// oldest first. The promoted object does not carry its origin — a
// scientific object, an issue row and an evidence assertion all have their
// own tables — so this is the query that answers "where did this come
// from", joined by the caller to discussion_comments (the author) and
// discussion_threads (the target).
func (q *Queries) ListDiscussionPromotionsByRef(ctx context.Context, arg ListDiscussionPromotionsByRefParams) ([]DiscussionPromotion, error) {
	rows, err := q.db.Query(ctx, listDiscussionPromotionsByRef, arg.ProjectID, arg.PromotedKind, arg.PromotedRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscussionPromotion
	for rows.Next() {
		var i DiscussionPromotion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ThreadID,
			&i.CommentID,
			&i.PromotedKind,
			&i.PromotedRef,
			&i.PromotedBy,
			&i.PromotedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscussionThreads = `-- name: ListDiscussionThreads :many
SELECT t.id, t.project_id, t.target_type, t.target_id, t.created_by, t.created_at,
       (SELECT count(*) FROM discussion_comments c
         WHERE c.thread_id = t.id AND c.deleted_at IS NULL)::bigint AS comment_count,
       (SELECT max(c.created_at) FROM discussion_comments c
         WHERE c.thread_id = t.id AND c.deleted_at IS NULL)::timestamptz AS last_comment_at
FROM discussion_threads t
WHERE t.project_id = $1
  AND t.target_type = $2
  AND t.target_id = $3
ORDER BY t.created_at, t.id
`

type ListDiscussionThreadsParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	TargetType string      `json:"target_type"`
	TargetID   string      `json:"target_id"`
}

type ListDiscussionThreadsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	TargetType    string             `json:"target_type"`
	TargetID      string             `json:"target_id"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CommentCount  int64              `json:"comment_count"`
	LastCommentAt pgtype.Timestamptz `json:"last_comment_at"`
}

// The threads of one target, oldest first (created_at, id — a total
// order). comment_count counts the comments that still stand (a deleted
// comment is retained but no longer part of the conversation, which is
// what the list renders), and last_comment_at is the newest one's time —
// NULL for a thread whose opening comment was deleted.
func (q *Queries) ListDiscussionThreads(ctx context.Context, arg ListDiscussionThreadsParams) ([]ListDiscussionThreadsRow, error) {
	rows, err := q.db.Query(ctx, listDiscussionThreads, arg.ProjectID, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscussionThreadsRow
	for rows.Next() {
		var i ListDiscussionThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CommentCount,
			&i.LastCommentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDiscussionComment = `-- name: SoftDeleteDiscussionComment :one
UPDATE discussion_comments
SET deleted_at = now(), deleted_by = $1
WHERE project_id = $2 AND id = $3 AND deleted_at IS NULL
RETURNING id, thread_id, project_id, body, created_by, created_at, deleted_at, deleted_by
`

type SoftDeleteDiscussionCommentParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// The delete surface's only write: a tombstone (when, by whom), never a
// DELETE. The `deleted_at IS NULL` predicate is the compare-and-swap — a
// second delete of the same comment matches nothing and is reported as
// not-found rather than overwriting the first tombstone's author.
func (q *Queries) SoftDeleteDiscussionComment(ctx context.Context, arg SoftDeleteDiscussionCommentParams) (DiscussionComment, error) {
	row := q.db.QueryRow(ctx, softDeleteDiscussionComment, arg.DeletedBy, arg.ProjectID, arg.ID)
	var i DiscussionComment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ProjectID,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
