// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events_audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :one
INSERT INTO outbox_events (event_type, payload, correlation_id)
VALUES ($1, $2, $3)
RETURNING id, event_type, payload, correlation_id, created_at, published_at, attempts
`

type EnqueueOutboxEventParams struct {
	EventType     string `json:"event_type"`
	Payload       []byte `json:"payload"`
	CorrelationID string `json:"correlation_id"`
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueOutboxEvent, arg.EventType, arg.Payload, arg.CorrelationID)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Attempts,
	)
	return i, err
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, event_type, payload, correlation_id, created_at, published_at, attempts FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at, id
LIMIT $1
`

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, batchSize int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = now(), attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const recordAuditLogEntry = `-- name: RecordAuditLogEntry :one
INSERT INTO audit_log
    (actor_id, via, action, target_ref, project_id, correlation_id,
     before_summary, after_summary, metadata)
VALUES
    ($1, $2, $3, $4, $5, $6,
     $7, $8, $9)
RETURNING id, actor_id, via, action, target_ref, project_id, correlation_id, before_summary, after_summary, metadata, occurred_at
`

type RecordAuditLogEntryParams struct {
	ActorID       pgtype.UUID `json:"actor_id"`
	Via           string      `json:"via"`
	Action        string      `json:"action"`
	TargetRef     *string     `json:"target_ref"`
	ProjectID     pgtype.UUID `json:"project_id"`
	CorrelationID string      `json:"correlation_id"`
	BeforeSummary []byte      `json:"before_summary"`
	AfterSummary  []byte      `json:"after_summary"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) RecordAuditLogEntry(ctx context.Context, arg RecordAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, recordAuditLogEntry,
		arg.ActorID,
		arg.Via,
		arg.Action,
		arg.TargetRef,
		arg.ProjectID,
		arg.CorrelationID,
		arg.BeforeSummary,
		arg.AfterSummary,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Via,
		&i.Action,
		&i.TargetRef,
		&i.ProjectID,
		&i.CorrelationID,
		&i.BeforeSummary,
		&i.AfterSummary,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const recordResearchEvent = `-- name: RecordResearchEvent :one

INSERT INTO research_events (event_type, actor_id, project_id, visibility, payload, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_type, actor_id, project_id, visibility, payload, correlation_id, occurred_at
`

type RecordResearchEventParams struct {
	EventType     string      `json:"event_type"`
	ActorID       pgtype.UUID `json:"actor_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	Visibility    string      `json:"visibility"`
	Payload       []byte      `json:"payload"`
	CorrelationID string      `json:"correlation_id"`
}

// Domain events, transactional outbox, audit log (canonical tables:
// research_events, outbox_events, audit_log). Outbox rows are written in the
// same transaction as the state change (docs/53).
func (q *Queries) RecordResearchEvent(ctx context.Context, arg RecordResearchEventParams) (ResearchEvent, error) {
	row := q.db.QueryRow(ctx, recordResearchEvent,
		arg.EventType,
		arg.ActorID,
		arg.ProjectID,
		arg.Visibility,
		arg.Payload,
		arg.CorrelationID,
	)
	var i ResearchEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ActorID,
		&i.ProjectID,
		&i.Visibility,
		&i.Payload,
		&i.CorrelationID,
		&i.OccurredAt,
	)
	return i, err
}
