// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvidenceAssertion = `-- name: CreateEvidenceAssertion :one

INSERT INTO evidence_assertions
    (id, project_id, state_id, target_object_version_id, evidence_object_version_id,
     relation_type, evidence_type, scope, directness, inference_nature,
     reasoning_note, created_by, evidence_origin, visibility)
VALUES
    ($1, $2, $3, $4, $5,
     $6, $7, $8, $9, $10,
     $11, $12, $13, $14)
RETURNING id, project_id, state_id, target_object_version_id, evidence_object_version_id, relation_type, evidence_type, scope, directness, inference_nature, reasoning_note, review_state, created_by, created_at, evidence_origin, visibility
`

type CreateEvidenceAssertionParams struct {
	ID                      pgtype.UUID `json:"id"`
	ProjectID               pgtype.UUID `json:"project_id"`
	StateID                 pgtype.UUID `json:"state_id"`
	TargetObjectVersionID   pgtype.UUID `json:"target_object_version_id"`
	EvidenceObjectVersionID pgtype.UUID `json:"evidence_object_version_id"`
	RelationType            string      `json:"relation_type"`
	EvidenceType            string      `json:"evidence_type"`
	Scope                   []byte      `json:"scope"`
	Directness              string      `json:"directness"`
	InferenceNature         string      `json:"inference_nature"`
	ReasoningNote           *string     `json:"reasoning_note"`
	CreatedBy               pgtype.UUID `json:"created_by"`
	EvidenceOrigin          string      `json:"evidence_origin"`
	Visibility              string      `json:"visibility"`
}

// Evidence assertions (canonical table: evidence_assertions). Evidence is a
// directed, typed relation between object versions — separate from the RSG
// relation graph (invariant 10: Provenance Graph != Evidence Graph).
//
// T0806 adds the network-evidence read and the two columns 00091 adds:
// evidence_origin (docs/10 §3's external/internal) and visibility.
//
// # Who decides what, here
//
// The three read classes (Origin / Reviewed External / Unreviewed External,
// docs/10 §7) are NOT spelled in SQL. ListPublishedEvidenceForTarget returns
// the two FACTS the classification is computed from — the asserting
// project's id (compared by the caller against the published version's
// owning project) and the assertion's review_state — and
// internal/domain.ClassifyEvidenceNetwork decides.
//
// The predicates below ARE spelled here, and they are the read STRATEGY that
// keeps the fail-closed rule cheap; the caller re-checks each row before
// rendering it (the same split feeds.sql's header describes, and the same
// reason: a predicate is never a substitute for the rule). Two things are
// filtered:
//
//	ea.visibility = 'public'          the assertion's own visibility axis:
//	                                  an assertion nothing made public is
//	                                  not rendered on the public read, and
//	                                  'private' is the column DEFAULT.
//	(origin OR asserting project public)
//	                                  the asserting project's own visibility.
//	                                  A public assertion can only be written
//	                                  by a public project through the write
//	                                  path; this half is the structural
//	                                  refusal for a row written any OTHER
//	                                  way (a private project's work is not
//	                                  published by asserting it somewhere
//	                                  else, docs/12 §2 发布不等于公开), and
//	                                  the origin half is why an assertion in
//	                                  the published object's OWN project is
//	                                  judged by the publication read gate
//	                                  the caller already passed rather than
//	                                  by the project's preset again.
//
// The assertion row, written inside a state commit (states.WriteFunc): the
// state_id the commit assigns is the transition the assertion was created
// in (docs/10 §3's "created transition"), so the assertion is traceable to
// the commit that carries it, like every other member row.
//
// The id is supplied by the caller (the column's default is for writers
// that have no commit to name the row in): the commit's operation summary
// carries the same id, which is what makes the assertion findable from the
// transition and the transition findable from the assertion.
//
// evidence_origin and visibility are SERVER-DERIVED inputs of this query,
// never client input: the caller resolves the project comparison and the
// visibility axes before it gets here (see 00091's header).
func (q *Queries) CreateEvidenceAssertion(ctx context.Context, arg CreateEvidenceAssertionParams) (EvidenceAssertion, error) {
	row := q.db.QueryRow(ctx, createEvidenceAssertion,
		arg.ID,
		arg.ProjectID,
		arg.StateID,
		arg.TargetObjectVersionID,
		arg.EvidenceObjectVersionID,
		arg.RelationType,
		arg.EvidenceType,
		arg.Scope,
		arg.Directness,
		arg.InferenceNature,
		arg.ReasoningNote,
		arg.CreatedBy,
		arg.EvidenceOrigin,
		arg.Visibility,
	)
	var i EvidenceAssertion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateID,
		&i.TargetObjectVersionID,
		&i.EvidenceObjectVersionID,
		&i.RelationType,
		&i.EvidenceType,
		&i.Scope,
		&i.Directness,
		&i.InferenceNature,
		&i.ReasoningNote,
		&i.ReviewState,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EvidenceOrigin,
		&i.Visibility,
	)
	return i, err
}

const getKnowledgePublicationForVersion = `-- name: GetKnowledgePublicationForVersion :one
SELECT kp.id::text AS id,
       kp.pid,
       kp.public_version,
       kp.rights_json,
       kp.object_version_id::text AS object_version_id,
       sov.visibility_policy_id,
       so.project_id::text AS project_id,
       p.visibility::text AS project_visibility
FROM knowledge_publications kp
JOIN scientific_object_versions sov ON sov.id = kp.object_version_id
JOIN scientific_objects so ON so.id = sov.object_id
JOIN projects p ON p.id = so.project_id
WHERE kp.object_version_id = $1::uuid
ORDER BY kp.published_at, kp.id
LIMIT 1
`

type GetKnowledgePublicationForVersionRow struct {
	ID                 string      `json:"id"`
	Pid                string      `json:"pid"`
	PublicVersion      string      `json:"public_version"`
	RightsJson         []byte      `json:"rights_json"`
	ObjectVersionID    string      `json:"object_version_id"`
	VisibilityPolicyID pgtype.UUID `json:"visibility_policy_id"`
	ProjectID          string      `json:"project_id"`
	ProjectVisibility  string      `json:"project_visibility"`
}

// The publication a version carries, with the inputs the audience rule
// decides with (knowledgepublish.AudienceFor): the project's preset, the
// version's own visibility axis, and the rights document read RAW — the
// rights token is a Go parse, never a JSON predicate (feeds.sql's header
// makes the same argument). The row is fetched whatever the audience turns
// out to be; the caller refuses rather than the query filtering, so there
// is one definition of who may read a publication.
func (q *Queries) GetKnowledgePublicationForVersion(ctx context.Context, objectVersionID pgtype.UUID) (GetKnowledgePublicationForVersionRow, error) {
	row := q.db.QueryRow(ctx, getKnowledgePublicationForVersion, objectVersionID)
	var i GetKnowledgePublicationForVersionRow
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.PublicVersion,
		&i.RightsJson,
		&i.ObjectVersionID,
		&i.VisibilityPolicyID,
		&i.ProjectID,
		&i.ProjectVisibility,
	)
	return i, err
}

const getVersionProjectFacts = `-- name: GetVersionProjectFacts :one
SELECT sov.id::text AS object_version_id,
       sov.object_id::text AS object_id,
       sov.visibility_policy_id,
       so.object_type,
       so.project_id::text AS project_id,
       p.visibility::text AS project_visibility
FROM scientific_object_versions sov
JOIN scientific_objects so ON so.id = sov.object_id
JOIN projects p ON p.id = so.project_id
WHERE sov.id = $1::uuid
`

type GetVersionProjectFactsRow struct {
	ObjectVersionID    string      `json:"object_version_id"`
	ObjectID           string      `json:"object_id"`
	VisibilityPolicyID pgtype.UUID `json:"visibility_policy_id"`
	ObjectType         string      `json:"object_type"`
	ProjectID          string      `json:"project_id"`
	ProjectVisibility  string      `json:"project_visibility"`
}

// One version's owning project, resolved through the object it belongs to
// (scientific_object_versions -> scientific_objects -> projects), with the
// version's own visibility axis.
//
// Both ends of an assertion are resolved with this query, because both
// answers come from the same chain: the TARGET end decides origin vs
// external (is this project the one the published version belongs to?), and
// the EVIDENCE end answers the same question about the cited version.
func (q *Queries) GetVersionProjectFacts(ctx context.Context, objectVersionID pgtype.UUID) (GetVersionProjectFactsRow, error) {
	row := q.db.QueryRow(ctx, getVersionProjectFacts, objectVersionID)
	var i GetVersionProjectFactsRow
	err := row.Scan(
		&i.ObjectVersionID,
		&i.ObjectID,
		&i.VisibilityPolicyID,
		&i.ObjectType,
		&i.ProjectID,
		&i.ProjectVisibility,
	)
	return i, err
}

const listEvidenceAssertionsForTarget = `-- name: ListEvidenceAssertionsForTarget :many
SELECT id, project_id, state_id, target_object_version_id, evidence_object_version_id, relation_type, evidence_type, scope, directness, inference_nature, reasoning_note, review_state, created_by, created_at, evidence_origin, visibility FROM evidence_assertions
WHERE target_object_version_id = $1
ORDER BY created_at, id
`

// Every assertion against one target version, oldest first. Rows are
// returned unfiltered by visibility: this is the owning project's read.
func (q *Queries) ListEvidenceAssertionsForTarget(ctx context.Context, objectVersionID pgtype.UUID) ([]EvidenceAssertion, error) {
	rows, err := q.db.Query(ctx, listEvidenceAssertionsForTarget, objectVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceAssertion
	for rows.Next() {
		var i EvidenceAssertion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StateID,
			&i.TargetObjectVersionID,
			&i.EvidenceObjectVersionID,
			&i.RelationType,
			&i.EvidenceType,
			&i.Scope,
			&i.Directness,
			&i.InferenceNature,
			&i.ReasoningNote,
			&i.ReviewState,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EvidenceOrigin,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEvidenceForTarget = `-- name: ListPublishedEvidenceForTarget :many
SELECT ea.id::text AS id,
       ea.project_id::text AS project_id,
       ea.target_object_version_id::text AS target_object_version_id,
       ea.evidence_object_version_id::text AS evidence_object_version_id,
       ea.relation_type,
       ea.evidence_type,
       ea.scope,
       ea.directness,
       ea.inference_nature,
       COALESCE(ea.reasoning_note, '')::text AS reasoning_note,
       ea.review_state,
       ea.created_at,
       sp.visibility::text AS source_project_visibility
FROM evidence_assertions ea
JOIN projects sp ON sp.id = ea.project_id
WHERE ea.target_object_version_id = $1::uuid
  AND ea.visibility = 'public'
  AND (ea.project_id = $2::uuid OR sp.visibility = 'public')
ORDER BY ea.created_at DESC, ea.id DESC
LIMIT $3
`

type ListPublishedEvidenceForTargetParams struct {
	ObjectVersionID pgtype.UUID `json:"object_version_id"`
	TargetProjectID pgtype.UUID `json:"target_project_id"`
	RowLimit        int32       `json:"row_limit"`
}

type ListPublishedEvidenceForTargetRow struct {
	ID                      string             `json:"id"`
	ProjectID               string             `json:"project_id"`
	TargetObjectVersionID   string             `json:"target_object_version_id"`
	EvidenceObjectVersionID string             `json:"evidence_object_version_id"`
	RelationType            string             `json:"relation_type"`
	EvidenceType            string             `json:"evidence_type"`
	Scope                   []byte             `json:"scope"`
	Directness              string             `json:"directness"`
	InferenceNature         string             `json:"inference_nature"`
	ReasoningNote           string             `json:"reasoning_note"`
	ReviewState             string             `json:"review_state"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SourceProjectVisibility string             `json:"source_project_visibility"`
}

// The evidence section of GET /knowledge/{knowledgeId}: the assertions
// against one PUBLISHED object version that the network read may render.
//
// The asserting project travels with each row because the caller needs BOTH
// ends of the origin/external axis to classify the row (see the file
// header); source_project_visibility is the strategy half of the predicate
// above and is re-checked by the caller.
//
// Newest first, bounded by @row_limit: the evidence on a popular published
// object is unbounded, and an unbounded read is a resource a writer can
// exhaust. The bound cuts the OLDEST rows — a reader of network evidence is
// looking for what the network has to say, and silently dropping the newest
// counter-evidence would be the one truncation this feature must not make
// (docs/24: external evidence 不可被 origin maintainer 静默删除). The
// caller fetches one row beyond the limit and reports whether the section
// was truncated rather than presenting a short list as complete.
//
// The order is total ((created_at, id) DESC), so one database state renders
// one document.
func (q *Queries) ListPublishedEvidenceForTarget(ctx context.Context, arg ListPublishedEvidenceForTargetParams) ([]ListPublishedEvidenceForTargetRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEvidenceForTarget, arg.ObjectVersionID, arg.TargetProjectID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEvidenceForTargetRow
	for rows.Next() {
		var i ListPublishedEvidenceForTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetObjectVersionID,
			&i.EvidenceObjectVersionID,
			&i.RelationType,
			&i.EvidenceType,
			&i.Scope,
			&i.Directness,
			&i.InferenceNature,
			&i.ReasoningNote,
			&i.ReviewState,
			&i.CreatedAt,
			&i.SourceProjectVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
