// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFeedAsset = `-- name: GetFeedAsset :one
SELECT ra.pid,
       ra.title,
       ra.asset_type,
       ra.created_at,
       p.visibility AS project_visibility,
       p.name AS project_name
FROM research_assets ra
JOIN projects p ON p.id = ra.origin_project_id
WHERE ra.pid = $1
`

type GetFeedAssetRow struct {
	Pid               string             `json:"pid"`
	Title             string             `json:"title"`
	AssetType         string             `json:"asset_type"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ProjectVisibility string             `json:"project_visibility"`
	ProjectName       string             `json:"project_name"`
}

// The asset an asset feed is about, addressed by its pid — the persistent
// identity every asset URL is built from (migration 00064,
// internal/assets/url.go), never the slug or the owning organization.
//
// The origin project's visibility comes back with it because that project
// is what decides whether the feed exists at all (the same rule the asset
// page's read gate applies and the same one the subscription audience
// resolution uses, T1002). An INNER join on a NOT NULL foreign key, so a
// row exists here exactly when the asset does.
func (q *Queries) GetFeedAsset(ctx context.Context, pid string) (GetFeedAssetRow, error) {
	row := q.db.QueryRow(ctx, getFeedAsset, pid)
	var i GetFeedAssetRow
	err := row.Scan(
		&i.Pid,
		&i.Title,
		&i.AssetType,
		&i.CreatedAt,
		&i.ProjectVisibility,
		&i.ProjectName,
	)
	return i, err
}

const getFeedKnowledgeObject = `-- name: GetFeedKnowledgeObject :one
SELECT so.id::text AS id,
       so.object_type,
       so.created_at,
       p.visibility AS project_visibility,
       p.name AS project_name,
       COALESCE((
         SELECT sov.title
         FROM knowledge_publications kp
         JOIN scientific_object_versions sov ON sov.id = kp.object_version_id
         WHERE sov.object_id = so.id
         ORDER BY kp.published_at DESC, kp.id DESC
         LIMIT 1
       ), '')::text AS title
FROM scientific_objects so
JOIN projects p ON p.id = so.project_id
WHERE so.id = $1::uuid
`

type GetFeedKnowledgeObjectRow struct {
	ID                string             `json:"id"`
	ObjectType        string             `json:"object_type"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ProjectVisibility string             `json:"project_visibility"`
	ProjectName       string             `json:"project_name"`
	Title             string             `json:"title"`
}

// The scientific object a knowledge feed is about, addressed by its uuid.
//
// A knowledge object has no title of its own — the title lives on each
// version (scientific_object_versions.title) — so the feed's title is the
// one the object is published under: the newest publication's version
// title, coerced to ” when the object has never been published. That empty
// string is a state the model renders as "no feed" (a knowledge feed needs
// at least one publication to exist at all), never as a nameless feed.
//
// The owning project travels with the row for the same reason it does on
// the asset: its visibility is what the feed's existence is decided from.
func (q *Queries) GetFeedKnowledgeObject(ctx context.Context, objectID pgtype.UUID) (GetFeedKnowledgeObjectRow, error) {
	row := q.db.QueryRow(ctx, getFeedKnowledgeObject, objectID)
	var i GetFeedKnowledgeObjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.CreatedAt,
		&i.ProjectVisibility,
		&i.ProjectName,
		&i.Title,
	)
	return i, err
}

const getFeedProject = `-- name: GetFeedProject :one

SELECT p.id::text AS id,
       p.name,
       p.purpose,
       p.visibility,
       p.created_at
FROM projects p
WHERE p.id = $1::uuid
`

type GetFeedProjectRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Purpose    string             `json:"purpose"`
	Visibility string             `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Public feed reads (T1004, docs/18 §4 "RSS/Atom（公开对象/项目）").
//
// The read behind the three anonymous feed routes: a public project's
// published output, one asset's published versions, one knowledge object's
// publications. Every query here is a READ: nothing in this file writes a
// row or takes a lock.
//
// # What the visibility predicates here are, and are not
//
// The entry lists filter by visibility, and that filter is a READ STRATEGY,
// not the disclosure rule. The lists are BOUNDED (LIMIT @row_limit), and a
// bounded window read raw is a resource a writer can exhaust: more than
// @row_limit newer PRIVATE versions of a public asset push its public ones
// out of the window, and the feed of a public, published asset answers as if
// there were nothing to subscribe to (tests/integration
// TestPrivateVersionsDoNotSuppressPublicOnes). Filtering here makes the LIMIT
// mean "the newest @row_limit rows a public feed may RENDER", which is the
// question the caller is actually asking.
//
// The disclosure rule itself stays in internal/application/feeds (BuildFeed),
// where it is a pure function with unit tests that name the criteria they
// come from, and where it applies to EVERY entry regardless of what a query
// returned. Dropping the predicates above would cost entries, not
// correctness: the model would render exactly the same document from the
// rows that survived its own filter. That is the property this split is for —
// a query change cannot by itself publish a private row, which is
// internal/assets' arrangement too (see the header of asset_page.sql).
//
// What IS decided here is what a row MEANS: `visibility` comes from the row
// that has one (research_asset_versions) or from the project that owns the
// row for publications, which have no visibility column of their own —
// publishing IS the public act (docs/12 §2) and the owning project is what
// decides whether anyone outside it may reach the publication. The knowledge
// halves need no predicate of their own: a publication's visibility IS its
// project's, so within one target every knowledge row shares one value, and
// the model's project gate settles all of them at once.
// The project a project feed is about. An index lookup on the primary key:
// a feed's target id is the project's uuid, not its slug (a slug is
// revisable; a feed's identity must not be — internal/application/feeds.
// feedID).
//
// purpose travels with the row because it is the project's own one-line
// description and the feed's subtitle (a project's purpose is public
// whenever the project is: the public project read renders it).
func (q *Queries) GetFeedProject(ctx context.Context, projectID pgtype.UUID) (GetFeedProjectRow, error) {
	row := q.db.QueryRow(ctx, getFeedProject, projectID)
	var i GetFeedProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Purpose,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedAssetEntries = `-- name: ListFeedAssetEntries :many
SELECT av.id::text AS entry_id,
       av.version,
       ra.pid AS asset_pid,
       ra.title,
       ra.asset_type AS subject_type,
       av.visibility,
       av.published_at,
       COALESCE(u.handle, '')::text AS publisher
FROM research_asset_versions av
JOIN research_assets ra ON ra.id = av.asset_id
LEFT JOIN users u ON u.id = av.published_by
WHERE ra.pid = $1
  AND av.visibility = 'public'
ORDER BY av.published_at DESC, av.id DESC
LIMIT $2
`

type ListFeedAssetEntriesParams struct {
	Pid      string `json:"pid"`
	RowLimit int32  `json:"row_limit"`
}

type ListFeedAssetEntriesRow struct {
	EntryID     string             `json:"entry_id"`
	Version     string             `json:"version"`
	AssetPid    string             `json:"asset_pid"`
	Title       string             `json:"title"`
	SubjectType string             `json:"subject_type"`
	Visibility  string             `json:"visibility"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Publisher   string             `json:"publisher"`
}

// One asset's PUBLIC versions, newest first — the rows this feed exists for,
// which is why the predicate above and migration 00080's partial index have
// the same shape. Indexed by (asset_id, published_at DESC, id DESC).
func (q *Queries) ListFeedAssetEntries(ctx context.Context, arg ListFeedAssetEntriesParams) ([]ListFeedAssetEntriesRow, error) {
	rows, err := q.db.Query(ctx, listFeedAssetEntries, arg.Pid, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedAssetEntriesRow
	for rows.Next() {
		var i ListFeedAssetEntriesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.Version,
			&i.AssetPid,
			&i.Title,
			&i.SubjectType,
			&i.Visibility,
			&i.PublishedAt,
			&i.Publisher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedKnowledgeEntries = `-- name: ListFeedKnowledgeEntries :many
SELECT kp.id::text AS entry_id,
       kp.public_version AS version,
       sov.title,
       so.object_type AS subject_type,
       p.visibility,
       kp.published_at,
       COALESCE(u.handle, '')::text AS publisher
FROM knowledge_publications kp
JOIN scientific_object_versions sov ON sov.id = kp.object_version_id
JOIN scientific_objects so ON so.id = sov.object_id
JOIN projects p ON p.id = so.project_id
LEFT JOIN users u ON u.id = kp.published_by
WHERE so.id = $1::uuid
ORDER BY kp.published_at DESC, kp.id DESC
LIMIT $2
`

type ListFeedKnowledgeEntriesParams struct {
	ObjectID pgtype.UUID `json:"object_id"`
	RowLimit int32       `json:"row_limit"`
}

type ListFeedKnowledgeEntriesRow struct {
	EntryID     string             `json:"entry_id"`
	Version     string             `json:"version"`
	Title       string             `json:"title"`
	SubjectType string             `json:"subject_type"`
	Visibility  string             `json:"visibility"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Publisher   string             `json:"publisher"`
}

// One knowledge object's publications, newest first.
//
// A publication has no visibility column: publishing a version onto the
// network IS the public act (docs/12 §2), and the owning project's
// visibility is what decides whether anyone outside it may reach it — so
// that is the value this query reports as the entry's visibility, exactly
// as the subscription audience resolution does for the same target type
// (internal/events/subscription_store.go).
func (q *Queries) ListFeedKnowledgeEntries(ctx context.Context, arg ListFeedKnowledgeEntriesParams) ([]ListFeedKnowledgeEntriesRow, error) {
	rows, err := q.db.Query(ctx, listFeedKnowledgeEntries, arg.ObjectID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedKnowledgeEntriesRow
	for rows.Next() {
		var i ListFeedKnowledgeEntriesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.Version,
			&i.Title,
			&i.SubjectType,
			&i.Visibility,
			&i.PublishedAt,
			&i.Publisher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedProjectEntries = `-- name: ListFeedProjectEntries :many
SELECT 'asset_version'::text AS entry_kind,
       av.id::text AS entry_id,
       av.version,
       ra.pid AS asset_pid,
       ra.asset_type AS subject_type,
       ra.title,
       av.visibility,
       av.published_at,
       COALESCE(u.handle, '')::text AS publisher
FROM research_asset_versions av
JOIN research_assets ra ON ra.id = av.asset_id
LEFT JOIN users u ON u.id = av.published_by
WHERE ra.origin_project_id = $2::uuid
  AND av.visibility = 'public'
UNION ALL
SELECT 'knowledge_publication'::text,
       kp.id::text,
       kp.public_version,
       ''::text,
       so.object_type,
       sov.title,
       p.visibility,
       kp.published_at,
       COALESCE(u.handle, '')::text
FROM knowledge_publications kp
JOIN scientific_object_versions sov ON sov.id = kp.object_version_id
JOIN scientific_objects so ON so.id = sov.object_id
JOIN projects p ON p.id = so.project_id
LEFT JOIN users u ON u.id = kp.published_by
WHERE so.project_id = $2::uuid
ORDER BY published_at DESC, entry_id DESC
LIMIT $1
`

type ListFeedProjectEntriesParams struct {
	RowLimit  int32       `json:"row_limit"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type ListFeedProjectEntriesRow struct {
	EntryKind   string             `json:"entry_kind"`
	EntryID     string             `json:"entry_id"`
	Version     string             `json:"version"`
	AssetPid    string             `json:"asset_pid"`
	SubjectType string             `json:"subject_type"`
	Title       string             `json:"title"`
	Visibility  string             `json:"visibility"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Publisher   string             `json:"publisher"`
}

// The newest versions of one project that a public feed may render — its
// assets' public versions and its objects' knowledge publications — newest
// first. Private asset versions are filtered out by the read strategy above;
// the knowledge half needs no predicate because a publication's visibility
// IS its owning project's.
//
// The two halves are UNION ALL'd rather than merged in Go so that ONE
// ordering and ONE limit apply to the union: taking the newest N of each
// half separately and merging them would have to read 2N rows to answer a
// question about N, and would silently mis-order the boundary between the
// halves if the two queries disagreed about ties.
//
// Ordering is (published_at DESC, entry_id DESC): the id tiebreak makes the
// order total, so one database state renders one document — the property
// the transport's ETag depends on.
//
// The publisher's handle is LEFT JOINed for the entry's author. A handle is
// public identity (a live profile is a public read, T0102); a missing user
// row renders as no author rather than as an error, because the feed's
// subject is the version, not the account.
func (q *Queries) ListFeedProjectEntries(ctx context.Context, arg ListFeedProjectEntriesParams) ([]ListFeedProjectEntriesRow, error) {
	rows, err := q.db.Query(ctx, listFeedProjectEntries, arg.RowLimit, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedProjectEntriesRow
	for rows.Next() {
		var i ListFeedProjectEntriesRow
		if err := rows.Scan(
			&i.EntryKind,
			&i.EntryID,
			&i.Version,
			&i.AssetPid,
			&i.SubjectType,
			&i.Title,
			&i.Visibility,
			&i.PublishedAt,
			&i.Publisher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
