// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMergeCreation = `-- name: CreateMergeCreation :one
INSERT INTO merge_creations (project_id, idempotency_key, merge_id)
VALUES ($1, $2, $3)
RETURNING id, project_id, idempotency_key, merge_id, created_at
`

type CreateMergeCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	MergeID        pgtype.UUID `json:"merge_id"`
}

func (q *Queries) CreateMergeCreation(ctx context.Context, arg CreateMergeCreationParams) (MergeCreation, error) {
	row := q.db.QueryRow(ctx, createMergeCreation, arg.ProjectID, arg.IdempotencyKey, arg.MergeID)
	var i MergeCreation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.MergeID,
		&i.CreatedAt,
	)
	return i, err
}

const getMergeCreation = `-- name: GetMergeCreation :one

SELECT merge_id FROM merge_creations
WHERE project_id = $1 AND idempotency_key = $2
`

type GetMergeCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// Research PR merge governance (canonical table: merge_creations). The
// Idempotency-Key ledger of the merge endpoint (docs/22 §3): the same key
// replays the merge it created, forever.
func (q *Queries) GetMergeCreation(ctx context.Context, arg GetMergeCreationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMergeCreation, arg.ProjectID, arg.IdempotencyKey)
	var merge_id pgtype.UUID
	err := row.Scan(&merge_id)
	return merge_id, err
}
