// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMilestone = `-- name: CreateMilestone :one

INSERT INTO project_milestones (project_id, kind, label, occurred_at, release_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, kind, label, occurred_at, release_id, created_by, created_at
`

type CreateMilestoneParams struct {
	ProjectID  pgtype.UUID        `json:"project_id"`
	Kind       string             `json:"kind"`
	Label      *string            `json:"label"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ReleaseID  pgtype.UUID        `json:"release_id"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
}

// Project milestones (T0609): research-timeline markers, separate from
// releases (canonical tables project_milestones,
// project_milestone_creations, migration 00063). A milestone may name a
// release; it never requires one.
func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.ProjectID,
		arg.Kind,
		arg.Label,
		arg.OccurredAt,
		arg.ReleaseID,
		arg.CreatedBy,
	)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.OccurredAt,
		&i.ReleaseID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createMilestoneCreation = `-- name: CreateMilestoneCreation :one
INSERT INTO project_milestone_creations (project_id, idempotency_key, milestone_id)
VALUES ($1, $2, $3)
RETURNING id, project_id, idempotency_key, milestone_id, created_at
`

type CreateMilestoneCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	MilestoneID    pgtype.UUID `json:"milestone_id"`
}

func (q *Queries) CreateMilestoneCreation(ctx context.Context, arg CreateMilestoneCreationParams) (ProjectMilestoneCreation, error) {
	row := q.db.QueryRow(ctx, createMilestoneCreation, arg.ProjectID, arg.IdempotencyKey, arg.MilestoneID)
	var i ProjectMilestoneCreation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.MilestoneID,
		&i.CreatedAt,
	)
	return i, err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, project_id, kind, label, occurred_at, release_id, created_by, created_at FROM project_milestones
WHERE project_id = $1 AND id = $2
`

type GetMilestoneParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetMilestone(ctx context.Context, arg GetMilestoneParams) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, getMilestone, arg.ProjectID, arg.ID)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.OccurredAt,
		&i.ReleaseID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getMilestoneCreation = `-- name: GetMilestoneCreation :one
SELECT milestone_id FROM project_milestone_creations
WHERE project_id = $1 AND idempotency_key = $2
`

type GetMilestoneCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetMilestoneCreation(ctx context.Context, arg GetMilestoneCreationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMilestoneCreation, arg.ProjectID, arg.IdempotencyKey)
	var milestone_id pgtype.UUID
	err := row.Scan(&milestone_id)
	return milestone_id, err
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, project_id, kind, label, occurred_at, release_id, created_by, created_at FROM project_milestones
WHERE project_id = $1
ORDER BY occurred_at, created_at, id
`

// The timeline: one project's milestones in research order — occurred_at
// first (the event's date, the canonical kinds' natural progression),
// then creation order (created_at, id) so same-date ties are a total,
// deterministic order no matter which order the rows were inserted.
func (q *Queries) ListMilestones(ctx context.Context, projectID pgtype.UUID) ([]ProjectMilestone, error) {
	rows, err := q.db.Query(ctx, listMilestones, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMilestone
	for rows.Next() {
		var i ProjectMilestone
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Label,
			&i.OccurredAt,
			&i.ReleaseID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
