// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetDeriveCreation struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	IdempotencyKey       string             `json:"idempotency_key"`
	AssetVersionID       pgtype.UUID        `json:"asset_version_id"`
	ParentAssetVersionID pgtype.UUID        `json:"parent_asset_version_id"`
	RelationType         string             `json:"relation_type"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type AssetLineage struct {
	ParentAssetVersionID pgtype.UUID `json:"parent_asset_version_id"`
	ChildAssetVersionID  pgtype.UUID `json:"child_asset_version_id"`
	RelationType         string      `json:"relation_type"`
}

type AssetPublishCreation struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	AssetVersionID pgtype.UUID        `json:"asset_version_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// The append-only chain of rights-holder designations and transfers for one research asset (docs/11 §6: "Ownership transfer 是 append-only governance event"; docs/26 §5 lists ownership transfer among the highest-risk audited actions). Each row is one event: the holder it names, the holder it supersedes (NULL for the first), who asked and when. The current holder is the row with the greatest ordinal; every earlier holder remains readable, which is the acceptance "转移之后，转移之前的持有关系仍要读得出来". Nothing here is updated or deleted — a later transfer appends.
type AssetRightsHolderEvent struct {
	ID                 pgtype.UUID        `json:"id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	Ordinal            int32              `json:"ordinal"`
	HolderKind         string             `json:"holder_kind"`
	HolderID           pgtype.UUID        `json:"holder_id"`
	PreviousHolderKind *string            `json:"previous_holder_kind"`
	PreviousHolderID   pgtype.UUID        `json:"previous_holder_id"`
	RecordedBy         pgtype.UUID        `json:"recorded_by"`
	RecordedAt         pgtype.Timestamptz `json:"recorded_at"`
}

// The parties one published asset version credits, per docs/11 §6 roles (creator, contributor, custodian, maintainer). Append-only: a credit is part of the immutable version record and is never revised — "Creator/history 永久保留". Written by the publish path (T0711) inside the publish transaction, so a version either carries its declared credits or does not exist.
type AssetVersionParty struct {
	ID             pgtype.UUID        `json:"id"`
	AssetVersionID pgtype.UUID        `json:"asset_version_id"`
	Role           string             `json:"role"`
	PartyKind      string             `json:"party_kind"`
	PartyID        pgtype.UUID        `json:"party_id"`
	Position       int32              `json:"position"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
}

type Attestation struct {
	ID                      pgtype.UUID        `json:"id"`
	Pid                     string             `json:"pid"`
	TargetObjectVersionID   pgtype.UUID        `json:"target_object_version_id"`
	TargetAssetVersionID    pgtype.UUID        `json:"target_asset_version_id"`
	AttestingProjectID      pgtype.UUID        `json:"attesting_project_id"`
	AttestingOrganizationID pgtype.UUID        `json:"attesting_organization_id"`
	BasisStateID            pgtype.UUID        `json:"basis_state_id"`
	InternalReviewID        pgtype.UUID        `json:"internal_review_id"`
	ValidationType          string             `json:"validation_type"`
	ValidationResult        string             `json:"validation_result"`
	OrgVisibility           string             `json:"org_visibility"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	Via            string             `json:"via"`
	Action         string             `json:"action"`
	TargetRef      *string            `json:"target_ref"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	CorrelationID  string             `json:"correlation_id"`
	BeforeSummary  []byte             `json:"before_summary"`
	AfterSummary   []byte             `json:"after_summary"`
	Metadata       []byte             `json:"metadata"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

type Blob struct {
	ID             pgtype.UUID        `json:"id"`
	ContentHash    string             `json:"content_hash"`
	SizeBytes      int64              `json:"size_bytes"`
	MediaType      *string            `json:"media_type"`
	StorageKey     string             `json:"storage_key"`
	IntegrityState string             `json:"integrity_state"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Name           string             `json:"name"`
	Visibility     string             `json:"visibility"`
	Purpose        *string            `json:"purpose"`
	GitRef         string             `json:"git_ref"`
	BaseStateID    pgtype.UUID        `json:"base_state_id"`
	LifecycleState string             `json:"lifecycle_state"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DiscussionComment struct {
	ID        pgtype.UUID        `json:"id"`
	ThreadID  pgtype.UUID        `json:"thread_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Body      string             `json:"body"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
}

type DiscussionPromotion struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ThreadID     pgtype.UUID        `json:"thread_id"`
	CommentID    pgtype.UUID        `json:"comment_id"`
	PromotedKind string             `json:"promoted_kind"`
	PromotedRef  string             `json:"promoted_ref"`
	PromotedBy   pgtype.UUID        `json:"promoted_by"`
	PromotedAt   pgtype.Timestamptz `json:"promoted_at"`
}

type DiscussionThread struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EvidenceAssertion struct {
	ID                      pgtype.UUID        `json:"id"`
	ProjectID               pgtype.UUID        `json:"project_id"`
	StateID                 pgtype.UUID        `json:"state_id"`
	TargetObjectVersionID   pgtype.UUID        `json:"target_object_version_id"`
	EvidenceObjectVersionID pgtype.UUID        `json:"evidence_object_version_id"`
	RelationType            string             `json:"relation_type"`
	EvidenceType            string             `json:"evidence_type"`
	Scope                   []byte             `json:"scope"`
	Directness              string             `json:"directness"`
	InferenceNature         string             `json:"inference_nature"`
	ReasoningNote           *string            `json:"reasoning_note"`
	ReviewState             string             `json:"review_state"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	EvidenceOrigin          string             `json:"evidence_origin"`
	Visibility              string             `json:"visibility"`
}

type Issue struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Number    int64              `json:"number"`
	IssueType string             `json:"issue_type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	State     string             `json:"state"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type KnowledgePublication struct {
	ID              pgtype.UUID        `json:"id"`
	ObjectVersionID pgtype.UUID        `json:"object_version_id"`
	PublicVersion   string             `json:"public_version"`
	RightsJson      []byte             `json:"rights_json"`
	PublishedBy     pgtype.UUID        `json:"published_by"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	Pid             string             `json:"pid"`
}

type KnowledgePublicationCreation struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MergeCreation struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	MergeID        pgtype.UUID        `json:"merge_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	// soft-delete marker: set when the organization is deactivated by its owner; NULL = active
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	// standing answer to "may this organization be named on an attestation it issues": anonymous (default) or named. The attestation records its own org_visibility as well; the public projection names the organization only when both say named (migration 00120, T0812)
	AttestationAttribution string `json:"attestation_attribution"`
}

type OrganizationMembership struct {
	OrganizationID   pgtype.UUID `json:"organization_id"`
	UserID           pgtype.UUID `json:"user_id"`
	Role             string      `json:"role"`
	AffiliationStart pgtype.Date `json:"affiliation_start"`
	AffiliationEnd   pgtype.Date `json:"affiliation_end"`
	Verified         bool        `json:"verified"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	CorrelationID string             `json:"correlation_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempts      int32              `json:"attempts"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	// The event's visibility preset, copied verbatim into the published research_event: public or private (docs/12 — an event is never more visible than its subject). 'private' is the fail-closed default for rows written before this migration; the outbox recorder always sets an explicit value.
	Visibility string `json:"visibility"`
	// Why the last publish attempt failed, when it did (T1001): a row whose publish fails is retried forever, and this column is the operator's window onto a stuck row (docs/26 §2 outbox backlog alerting). NULL while never attempted or after a successful publish.
	LastError *string `json:"last_error"`
	// The webhook fan-out cursor (T1006): set in the same transaction that inserts the delivery rows, so the fan-out is exactly-once per published row — a crash between insert and mark re-runs it as a no-op under webhook_deliveries_endpoint_event_uniq.
	WebhookFannedOutAt pgtype.Timestamptz `json:"webhook_fanned_out_at"`
	// The channel the write that produced this event arrived through, in the state_commits.via vocabulary (00004) — the envelope column the publisher copies verbatim into research_events.via (00046: envelope columns are copied from the outbox row, never re-derived from the payload). NULL means the writing path did not record a channel; the outbox recorder (internal/events) is the path that sets it.
	Via *string `json:"via"`
}

type PolicyVersion struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Version        string             `json:"version"`
	PolicyJson     []byte             `json:"policy_json"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Program struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                      pgtype.UUID        `json:"id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	ProgramID               pgtype.UUID        `json:"program_id"`
	Slug                    string             `json:"slug"`
	Name                    string             `json:"name"`
	Purpose                 string             `json:"purpose"`
	ActivityStatus          string             `json:"activity_status"`
	Visibility              string             `json:"visibility"`
	MainFrozen              bool               `json:"main_frozen"`
	GitRepositoryExternalID *string            `json:"git_repository_external_id"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	// GitProvider provisioning state: pending (created, repo not provisioned yet), provisioned (T0301), failed
	ProvisionStatus string `json:"provision_status"`
}

type ProjectMembership struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectMilestone struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Kind       string             `json:"kind"`
	Label      *string            `json:"label"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ReleaseID  pgtype.UUID        `json:"release_id"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProjectMilestoneCreation struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	MilestoneID    pgtype.UUID        `json:"milestone_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ProjectSchemaProfile struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	SchemaID          string             `json:"schema_id"`
	Version           string             `json:"version"`
	BaseSchemaID      string             `json:"base_schema_id"`
	BaseSchemaVersion string             `json:"base_schema_version"`
	Content           string             `json:"content"`
	ContentHash       string             `json:"content_hash"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ProjectState struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	ParentStateID   pgtype.UUID        `json:"parent_state_id"`
	StateHash       string             `json:"state_hash"`
	GitCommitSha    *string            `json:"git_commit_sha"`
	ManifestVersion string             `json:"manifest_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ProjectTemplateInstantiation struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	TemplateID      string             `json:"template_id"`
	TemplateVersion string             `json:"template_version"`
	TemplateName    string             `json:"template_name"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PullRequest struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Number          int64              `json:"number"`
	SourceBranchID  pgtype.UUID        `json:"source_branch_id"`
	TargetBranchID  pgtype.UUID        `json:"target_branch_id"`
	BaseStateID     pgtype.UUID        `json:"base_state_id"`
	ProposedStateID pgtype.UUID        `json:"proposed_state_id"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	State           string             `json:"state"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
	// The Idempotency-Key the creation request carried (specs/api/openapi.yaml components.parameters.IdempotencyKey); empty when the request sent none. UNIQUE per project among non-empty keys: a repeated request returns the proposal the first one opened instead of opening a second.
	CreationKey string `json:"creation_key"`
}

type Relation struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CurrentVersionNo int32              `json:"current_version_no"`
}

type RelationVersion struct {
	ID                    pgtype.UUID        `json:"id"`
	RelationID            pgtype.UUID        `json:"relation_id"`
	VersionNo             int32              `json:"version_no"`
	StateID               pgtype.UUID        `json:"state_id"`
	RelationType          string             `json:"relation_type"`
	SourceObjectVersionID pgtype.UUID        `json:"source_object_version_id"`
	TargetObjectVersionID pgtype.UUID        `json:"target_object_version_id"`
	Payload               []byte             `json:"payload"`
	IntegrityHash         string             `json:"integrity_hash"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type Release struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Version            string             `json:"version"`
	Title              string             `json:"title"`
	StateID            pgtype.UUID        `json:"state_id"`
	PolicyVersionID    pgtype.UUID        `json:"policy_version_id"`
	Manifest           string             `json:"manifest"`
	ManifestHash       string             `json:"manifest_hash"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrgPolicyVersionID pgtype.UUID        `json:"org_policy_version_id"`
}

type ReleaseCreation struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	ReleaseID      pgtype.UUID        `json:"release_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ResearchAsset struct {
	ID              pgtype.UUID        `json:"id"`
	AssetType       string             `json:"asset_type"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	OriginProjectID pgtype.UUID        `json:"origin_project_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Pid             string             `json:"pid"`
	// T0706. The asset's description — revisable asset metadata (docs/11 §4), NOT part of any scientific version. Revised in place by internal/application/assetmetadata, in the same transaction as the audit_log row recording the revision. Empty string means "no description recorded"; NULL is never stored.
	Description string `json:"description"`
	// T0706. The asset's keyword list — revisable asset metadata (docs/11 §4). An array because it is stored as a list; the count/length bounds live in internal/assets (MaxKeywords, MaxKeywordLen) and are enforced on the write path, not as a CHECK here.
	Keywords []string `json:"keywords"`
	// T0706. How to reach whoever is responsible for the asset — revisable asset metadata (docs/11 §4). Plain strings, not a structured party reference: docs/11 §6 already gives the responsible parties their own roles (Rights Holder, Custodian, Maintainer, Creator, Contributor) in their own tables, and a second structured copy here would be a second answer to "who is responsible".
	Contact []string `json:"contact"`
	// T0706. Where the asset is documented — revisable asset metadata (docs/11 §4). Plain strings: this build stores the reference the publisher declared and does not dereference it, so no URL shape is asserted here (a DOI, a repository path and an https link are all references).
	Documentation []string `json:"documentation"`
	// T0706. The blob that would be the asset's cover — RESERVED, and written by nothing in this build. docs/11 §4 lists cover among the revisable metadata, so the slot exists; the blob surface has no upload/download route and no signed-URL/TTL mechanism, so a cover set today is an image no reader could fetch. The revision command refuses a cover change by name (assetmetadata.ErrCoverNotSupported) rather than dropping it, and the channel that would fill this column belongs to the blob-transfer task. NULL is the state of every asset today.
	CoverBlobID pgtype.UUID `json:"cover_blob_id"`
}

type ResearchAssetVersion struct {
	ID              pgtype.UUID        `json:"id"`
	AssetID         pgtype.UUID        `json:"asset_id"`
	Version         string             `json:"version"`
	SourceReleaseID pgtype.UUID        `json:"source_release_id"`
	Manifest        []byte             `json:"manifest"`
	RightsJson      []byte             `json:"rights_json"`
	Visibility      string             `json:"visibility"`
	IntegrityHash   string             `json:"integrity_hash"`
	PublishedBy     pgtype.UUID        `json:"published_by"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	OriginRefs      []string           `json:"origin_refs"`
}

// Draft Research Context (T0908, docs/14:25): the candidate — research question, referenced knowledge, dependencies, candidate materials, uncertainties and agent-suggested hypotheses — that a search answer becomes when the reader clicks "Start Research Project". It is NOT an RSG node: the project's initial state forms only on confirmation, so a project with a draft and no confirmation has no branch, no state and no scientific object.
type ResearchContextDraft struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	// The answered search the draft was built from (search_records, 00121). Its selected_refs are the only refs the draft may carry (research_context_draft_refs_guard), so the draft cannot name a source the answer did not have.
	SearchID         pgtype.UUID `json:"search_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
	ResearchQuestion string      `json:"research_question"`
	ReferencedRefs   []string    `json:"referenced_refs"`
	DependencyRefs   []string    `json:"dependency_refs"`
	CandidateRefs    []string    `json:"candidate_refs"`
	Uncertainties    []string    `json:"uncertainties"`
	Hypotheses       []string    `json:"hypotheses"`
	Status           string      `json:"status"`
	IdempotencyKey   string      `json:"idempotency_key"`
	// The confirm route's Idempotency-Key, written once at confirmation. A repeat of the same key answers the confirmation it names; a different key on an already-confirmed draft is refused (the draft is not in a state that can be confirmed).
	ConfirmIdempotencyKey *string            `json:"confirm_idempotency_key"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	ConfirmedBy           pgtype.UUID        `json:"confirmed_by"`
	InitialBranchID       pgtype.UUID        `json:"initial_branch_id"`
	InitialStateID        pgtype.UUID        `json:"initial_state_id"`
	// The state commit that names the confirmation's transition (docs/09 §2). From it a reader reaches the initial branch, the initial state and the research_question object version the transition created — the traceability the confirmation owes.
	InitialCommitID  pgtype.UUID `json:"initial_commit_id"`
	QuestionObjectID pgtype.UUID `json:"question_object_id"`
	// The research_question object version the confirmation created (version 1 of a new object, through the ordinary RSG write path). The object is created at confirmation and never before: an unanswered question is a draft, a question in the project's state is a decision.
	QuestionVersionID pgtype.UUID        `json:"question_version_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ResearchEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Visibility    string             `json:"visibility"`
	Payload       []byte             `json:"payload"`
	CorrelationID string             `json:"correlation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	// The outbox row this event was published from (T1001). The partial unique index research_events_outbox_event_uniq makes the publish step idempotent: a retried publish after a crash between the insert and the published-mark is a no-op. NULL for research events written directly, bypassing the outbox.
	OutboxEventID pgtype.UUID `json:"outbox_event_id"`
	// The channel the write that produced this event arrived through, in the state_commits.via vocabulary (00004), copied verbatim from the outbox row it was published from (00046). Read by the Contribution Ledger projection (T0807) into contribution_events.via — the ledger never re-derives a channel from an event payload. NULL means no channel was carried.
	Via *string `json:"via"`
}

type ResearchOwnerRule struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MatchKind      string             `json:"match_kind"`
	MatchValue     string             `json:"match_value"`
	Responsibility string             `json:"responsibility"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ResponsibilityAssignment struct {
	ProjectID      pgtype.UUID        `json:"project_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Responsibility string             `json:"responsibility"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID              pgtype.UUID        `json:"id"`
	PullRequestID   pgtype.UUID        `json:"pull_request_id"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	ReviewKind      string             `json:"review_kind"`
	Decision        string             `json:"decision"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ReviewedStateID pgtype.UUID        `json:"reviewed_state_id"`
	Responsibility  string             `json:"responsibility"`
}

type ScientificObject struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	ObjectType       string             `json:"object_type"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CurrentVersionNo int32              `json:"current_version_no"`
}

type ScientificObjectVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	ObjectID           pgtype.UUID        `json:"object_id"`
	VersionNo          int32              `json:"version_no"`
	StateID            pgtype.UUID        `json:"state_id"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	SchemaID           string             `json:"schema_id"`
	SchemaVersion      string             `json:"schema_version"`
	Title              string             `json:"title"`
	LifecycleState     string             `json:"lifecycle_state"`
	Payload            []byte             `json:"payload"`
	VisibilityPolicyID pgtype.UUID        `json:"visibility_policy_id"`
	IntegrityHash      string             `json:"integrity_hash"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	// The abort's reason code (docs/46:7). An OPEN caller-supplied token in V1 — no vocabulary is defined by any spec, and this platform does not invent one; the column CHECKs the shape (^[a-z0-9_]{1,64}$) and records the value as given.
	AbortReasonCode *string `json:"abort_reason_code"`
	// The human explanation the abort recorded (docs/46:7) — the part no machine can reconstruct. Non-blank when the record exists.
	AbortExplanation *string `json:"abort_explanation"`
	// The optional replacement/superseding ref (docs/46:7). NULL means none was given; it is never stored as an empty string.
	AbortReplacementRef *string `json:"abort_replacement_ref"`
	// The actor who decided the abort (docs/46:7 "actor"). Not the row's created_by: after a Research PR merge materializes the abort onto main, created_by is the merging actor while this stays the aborting one.
	AbortedBy pgtype.UUID `json:"aborted_by"`
	// Server-derived time of the abort decision (docs/46:7 "time"); never caller-supplied. Travels with the record when a merge materializes the abort onto main.
	AbortedAt pgtype.Timestamptz `json:"aborted_at"`
	// The Idempotency-Key the abort request carried (specs/api/openapi.yaml components.parameters.IdempotencyKey); NULL when none. UNIQUE per object among non-NULL keys, so a repeated request reads the row the first one wrote instead of appending a second (the migration-00089 pattern). Not carried onto main by a merge: it names a request, not history.
	AbortRequestKey *string `json:"abort_request_key"`
	// The reopen's reason code, in the shape 00100 gave the abort record. An OPEN caller-supplied token in V1 — no spec names reopen reason codes at all, and this platform does not invent a vocabulary; the column CHECKs the shape (^[a-z0-9_]{1,64}$) and records the value as given.
	ReopenReasonCode *string `json:"reopen_reason_code"`
	// The human explanation the reopen recorded — the part no machine can reconstruct. Non-blank when the record exists.
	ReopenExplanation *string `json:"reopen_explanation"`
	// The actor who decided the reopen (not the row's created_by: after a Research PR merge materializes the reopen onto main, created_by is the merging actor while this stays the reopening one).
	ReopenedBy pgtype.UUID `json:"reopened_by"`
	// Server-derived time of the reopen decision; never caller-supplied. Travels with the record when a merge materializes the reopen onto main.
	ReopenedAt pgtype.Timestamptz `json:"reopened_at"`
	// The Idempotency-Key the reopen request carried (specs/api/openapi.yaml components.parameters.IdempotencyKey); NULL when none. UNIQUE per object among non-NULL keys, so a repeated request reads the row the first one wrote instead of appending a second (the migration-00100 pattern). Not carried onto main by a merge: it names a request, not history.
	ReopenRequestKey *string `json:"reopen_request_key"`
}

type StateCommit struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	BranchID         pgtype.UUID        `json:"branch_id"`
	BaseStateID      pgtype.UUID        `json:"base_state_id"`
	ResultStateID    pgtype.UUID        `json:"result_state_id"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	Via              string             `json:"via"`
	Message          string             `json:"message"`
	OperationSummary []byte             `json:"operation_summary"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Handle      string             `json:"handle"`
	Email       *string            `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	// argon2id PHC encoding ($argon2id$v=19$m=65536,t=3,p=2$...); NULL = OIDC-only account
	PasswordHash *string `json:"password_hash"`
}

type ValidationResult struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	StateID    pgtype.UUID        `json:"state_id"`
	Gate       string             `json:"gate"`
	Status     string             `json:"status"`
	ResultJson []byte             `json:"result_json"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
