// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID            pgtype.UUID        `json:"id"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	Via           string             `json:"via"`
	Action        string             `json:"action"`
	TargetRef     *string            `json:"target_ref"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	CorrelationID string             `json:"correlation_id"`
	BeforeSummary []byte             `json:"before_summary"`
	AfterSummary  []byte             `json:"after_summary"`
	Metadata      []byte             `json:"metadata"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type Blob struct {
	ID             pgtype.UUID        `json:"id"`
	ContentHash    string             `json:"content_hash"`
	SizeBytes      int64              `json:"size_bytes"`
	MediaType      *string            `json:"media_type"`
	StorageKey     string             `json:"storage_key"`
	IntegrityState string             `json:"integrity_state"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Name           string             `json:"name"`
	Visibility     string             `json:"visibility"`
	Purpose        *string            `json:"purpose"`
	GitRef         string             `json:"git_ref"`
	BaseStateID    pgtype.UUID        `json:"base_state_id"`
	LifecycleState string             `json:"lifecycle_state"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type EvidenceAssertion struct {
	ID                      pgtype.UUID        `json:"id"`
	ProjectID               pgtype.UUID        `json:"project_id"`
	StateID                 pgtype.UUID        `json:"state_id"`
	TargetObjectVersionID   pgtype.UUID        `json:"target_object_version_id"`
	EvidenceObjectVersionID pgtype.UUID        `json:"evidence_object_version_id"`
	RelationType            string             `json:"relation_type"`
	EvidenceType            string             `json:"evidence_type"`
	Scope                   []byte             `json:"scope"`
	Directness              string             `json:"directness"`
	InferenceNature         string             `json:"inference_nature"`
	ReasoningNote           *string            `json:"reasoning_note"`
	ReviewState             string             `json:"review_state"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Number    int64              `json:"number"`
	IssueType string             `json:"issue_type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	State     string             `json:"state"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type KnowledgePublication struct {
	ID              pgtype.UUID        `json:"id"`
	ObjectVersionID pgtype.UUID        `json:"object_version_id"`
	PublicVersion   string             `json:"public_version"`
	RightsJson      []byte             `json:"rights_json"`
	PublishedBy     pgtype.UUID        `json:"published_by"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type Organization struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	CorrelationID string             `json:"correlation_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempts      int32              `json:"attempts"`
}

type Program struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                      pgtype.UUID        `json:"id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	ProgramID               pgtype.UUID        `json:"program_id"`
	Slug                    string             `json:"slug"`
	Name                    string             `json:"name"`
	Purpose                 string             `json:"purpose"`
	ActivityStatus          string             `json:"activity_status"`
	Visibility              string             `json:"visibility"`
	MainFrozen              bool               `json:"main_frozen"`
	GitRepositoryExternalID *string            `json:"git_repository_external_id"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type ProjectState struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	ParentStateID   pgtype.UUID        `json:"parent_state_id"`
	StateHash       string             `json:"state_hash"`
	GitCommitSha    *string            `json:"git_commit_sha"`
	ManifestVersion string             `json:"manifest_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PullRequest struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Number          int64              `json:"number"`
	SourceBranchID  pgtype.UUID        `json:"source_branch_id"`
	TargetBranchID  pgtype.UUID        `json:"target_branch_id"`
	BaseStateID     pgtype.UUID        `json:"base_state_id"`
	ProposedStateID pgtype.UUID        `json:"proposed_state_id"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	State           string             `json:"state"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
}

type Relation struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RelationVersion struct {
	ID                    pgtype.UUID        `json:"id"`
	RelationID            pgtype.UUID        `json:"relation_id"`
	VersionNo             int32              `json:"version_no"`
	StateID               pgtype.UUID        `json:"state_id"`
	RelationType          string             `json:"relation_type"`
	SourceObjectVersionID pgtype.UUID        `json:"source_object_version_id"`
	TargetObjectVersionID pgtype.UUID        `json:"target_object_version_id"`
	Payload               []byte             `json:"payload"`
	IntegrityHash         string             `json:"integrity_hash"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type Release struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Version         string             `json:"version"`
	Title           string             `json:"title"`
	StateID         pgtype.UUID        `json:"state_id"`
	PolicyVersionID pgtype.UUID        `json:"policy_version_id"`
	Manifest        []byte             `json:"manifest"`
	ManifestHash    string             `json:"manifest_hash"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ResearchAsset struct {
	ID              pgtype.UUID        `json:"id"`
	AssetType       string             `json:"asset_type"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	OriginProjectID pgtype.UUID        `json:"origin_project_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ResearchAssetVersion struct {
	ID              pgtype.UUID        `json:"id"`
	AssetID         pgtype.UUID        `json:"asset_id"`
	Version         string             `json:"version"`
	SourceReleaseID pgtype.UUID        `json:"source_release_id"`
	Manifest        []byte             `json:"manifest"`
	RightsJson      []byte             `json:"rights_json"`
	Visibility      string             `json:"visibility"`
	IntegrityHash   string             `json:"integrity_hash"`
	PublishedBy     pgtype.UUID        `json:"published_by"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type ResearchEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Visibility    string             `json:"visibility"`
	Payload       []byte             `json:"payload"`
	CorrelationID string             `json:"correlation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type Review struct {
	ID            pgtype.UUID        `json:"id"`
	PullRequestID pgtype.UUID        `json:"pull_request_id"`
	ReviewerID    pgtype.UUID        `json:"reviewer_id"`
	ReviewKind    string             `json:"review_kind"`
	Decision      string             `json:"decision"`
	Body          string             `json:"body"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ScientificObject struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	ObjectType string             `json:"object_type"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ScientificObjectVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	ObjectID           pgtype.UUID        `json:"object_id"`
	VersionNo          int32              `json:"version_no"`
	StateID            pgtype.UUID        `json:"state_id"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	SchemaID           string             `json:"schema_id"`
	SchemaVersion      string             `json:"schema_version"`
	Title              string             `json:"title"`
	LifecycleState     string             `json:"lifecycle_state"`
	Payload            []byte             `json:"payload"`
	VisibilityPolicyID pgtype.UUID        `json:"visibility_policy_id"`
	IntegrityHash      string             `json:"integrity_hash"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type StateCommit struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	BranchID         pgtype.UUID        `json:"branch_id"`
	BaseStateID      pgtype.UUID        `json:"base_state_id"`
	ResultStateID    pgtype.UUID        `json:"result_state_id"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	Via              string             `json:"via"`
	Message          string             `json:"message"`
	OperationSummary []byte             `json:"operation_summary"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Handle      string             `json:"handle"`
	Email       *string            `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
}

type ValidationResult struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	StateID    pgtype.UUID        `json:"state_id"`
	Gate       string             `json:"gate"`
	Status     string             `json:"status"`
	ResultJson []byte             `json:"result_json"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
