// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicyVersion = `-- name: CreatePolicyVersion :one

INSERT INTO policy_versions (organization_id, project_id, version, policy_json, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, project_id, version, policy_json, created_by, created_at
`

type CreatePolicyVersionParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Version        string      `json:"version"`
	PolicyJson     []byte      `json:"policy_json"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

// Policy versions (canonical table policy_versions; 00033 adds the
// per-scope version uniqueness and the version shape check). The table is
// append-only (00014/00015): these queries INSERT and SELECT only — a
// policy change is a new version row, never an UPDATE.
func (q *Queries) CreatePolicyVersion(ctx context.Context, arg CreatePolicyVersionParams) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, createPolicyVersion,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Version,
		arg.PolicyJson,
		arg.CreatedBy,
	)
	var i PolicyVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Version,
		&i.PolicyJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyVersion = `-- name: GetPolicyVersion :one
SELECT id, organization_id, project_id, version, policy_json, created_by, created_at FROM policy_versions WHERE id = $1
`

// One version by id — any age: old versions stay queryable forever
// (T0603 acceptance).
func (q *Queries) GetPolicyVersion(ctx context.Context, id pgtype.UUID) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, getPolicyVersion, id)
	var i PolicyVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Version,
		&i.PolicyJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestPolicyVersionByOrg = `-- name: LatestPolicyVersionByOrg :one
SELECT id, organization_id, project_id, version, policy_json, created_by, created_at FROM policy_versions
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The organization's current policy (the project lower bound).
func (q *Queries) LatestPolicyVersionByOrg(ctx context.Context, organizationID pgtype.UUID) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, latestPolicyVersionByOrg, organizationID)
	var i PolicyVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Version,
		&i.PolicyJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestPolicyVersionByProject = `-- name: LatestPolicyVersionByProject :one
SELECT id, organization_id, project_id, version, policy_json, created_by, created_at FROM policy_versions
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) LatestPolicyVersionByProject(ctx context.Context, projectID pgtype.UUID) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, latestPolicyVersionByProject, projectID)
	var i PolicyVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Version,
		&i.PolicyJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPolicyVersionsByOrg = `-- name: ListPolicyVersionsByOrg :many
SELECT id, organization_id, project_id, version, policy_json, created_by, created_at FROM policy_versions
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
`

// Every version of the organization, newest first (created_at, then id
// as a deterministic tie-break).
func (q *Queries) ListPolicyVersionsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]PolicyVersion, error) {
	rows, err := q.db.Query(ctx, listPolicyVersionsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyVersion
	for rows.Next() {
		var i PolicyVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Version,
			&i.PolicyJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyVersionsByProject = `-- name: ListPolicyVersionsByProject :many
SELECT id, organization_id, project_id, version, policy_json, created_by, created_at FROM policy_versions
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPolicyVersionsByProject(ctx context.Context, projectID pgtype.UUID) ([]PolicyVersion, error) {
	rows, err := q.db.Query(ctx, listPolicyVersionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyVersion
	for rows.Next() {
		var i PolicyVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Version,
			&i.PolicyJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
