// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMembership = `-- name: AddProjectMembership :exec
INSERT INTO project_memberships (project_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddProjectMembershipParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) AddProjectMembership(ctx context.Context, arg AddProjectMembershipParams) error {
	_, err := q.db.Exec(ctx, addProjectMembership, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const createProgram = `-- name: CreateProgram :one

INSERT INTO programs (organization_id, slug, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, slug, name, description, created_at
`

type CreateProgramParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Description    *string     `json:"description"`
}

// Projects, programs, memberships (canonical tables: programs, projects,
// project_memberships).
func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.Description,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, program_id, slug, name, purpose, visibility, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at
`

type CreateProjectParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProgramID      pgtype.UUID `json:"program_id"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Purpose        string      `json:"purpose"`
	Visibility     string      `json:"visibility"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.ProgramID,
		arg.Slug,
		arg.Name,
		arg.Purpose,
		arg.Visibility,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at FROM projects WHERE organization_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Slug           string      `json:"slug"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OrganizationID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id AS user_id, u.handle, u.display_name, pm.role, pm.created_at AS joined_at
FROM project_memberships pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.created_at, u.id
`

type ListProjectMembersRow struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Handle      string             `json:"handle"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Handle,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrganization = `-- name: ListProjectsByOrganization :many
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at FROM projects
WHERE organization_id = $1
ORDER BY created_at, id
LIMIT $3 OFFSET $2
`

type ListProjectsByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PageOffset     int32       `json:"page_offset"`
	PageSize       int32       `json:"page_size"`
}

func (q *Queries) ListProjectsByOrganization(ctx context.Context, arg ListProjectsByOrganizationParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrganization, arg.OrganizationID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProgramID,
			&i.Slug,
			&i.Name,
			&i.Purpose,
			&i.ActivityStatus,
			&i.Visibility,
			&i.MainFrozen,
			&i.GitRepositoryExternalID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectActivityStatus = `-- name: UpdateProjectActivityStatus :one
UPDATE projects
SET activity_status = $1
WHERE id = $2
RETURNING id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at
`

type UpdateProjectActivityStatusParams struct {
	ActivityStatus string      `json:"activity_status"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProjectActivityStatus(ctx context.Context, arg UpdateProjectActivityStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectActivityStatus, arg.ActivityStatus, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
