// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMembership = `-- name: AddProjectMembership :one
INSERT INTO project_memberships (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, role, created_at
`

type AddProjectMembershipParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) AddProjectMembership(ctx context.Context, arg AddProjectMembershipParams) (ProjectMembership, error) {
	row := q.db.QueryRow(ctx, addProjectMembership, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMembership
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countProjectOwners = `-- name: CountProjectOwners :one
SELECT count(*)::integer AS owner_count FROM project_memberships
WHERE project_id = $1 AND role = 'owner'
`

func (q *Queries) CountProjectOwners(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProjectOwners, projectID)
	var owner_count int32
	err := row.Scan(&owner_count)
	return owner_count, err
}

const createProgram = `-- name: CreateProgram :one

INSERT INTO programs (organization_id, slug, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, slug, name, description, created_at
`

type CreateProgramParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Description    *string     `json:"description"`
}

// Projects, programs, memberships (canonical tables: programs, projects,
// project_memberships).
func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.Description,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, program_id, slug, name, purpose, visibility, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status
`

type CreateProjectParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProgramID      pgtype.UUID `json:"program_id"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Purpose        string      `json:"purpose"`
	Visibility     string      `json:"visibility"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.ProgramID,
		arg.Slug,
		arg.Name,
		arg.Purpose,
		arg.Visibility,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProvisionStatus,
	)
	return i, err
}

const freezeProjectMain = `-- name: FreezeProjectMain :one
UPDATE projects
SET main_frozen = true
WHERE id = $1 AND main_frozen = false
RETURNING id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status
`

// FreezeProjectMain is the freeze governance action's write (T0601). It is
// a compare-and-swap, not a read-then-write: the flag moves from false to
// true only while it is still false, so of two concurrent freezes of one
// project exactly ONE finds a row here and the loser finds zero — and only
// the winner's audit row and domain event are written (the task's
// concurrency criterion; the same CAS discipline
// scientific_objects.current_version_no follows).
//
// Zero rows mean either the project does not exist or main is already
// frozen; the adapter distinguishes them with one read, exactly the way
// UpdateBranchBaseState's zero-row outcome is resolved (state_store.go).
//
// There is deliberately no statement in this file that CLEARS the flag:
// V1 provides no unfreeze (docs/09 §3: "Emergency unfreeze 不在 V1 提供，
// 避免形成绕过路径"; specs/api/openapi.yaml carries no :unfreeze). Adding
// one here would be the bypass the specification forbids.
func (q *Queries) FreezeProjectMain(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, freezeProjectMain, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProvisionStatus,
	)
	return i, err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, organization_id, slug, name, description, created_at FROM programs WHERE id = $1
`

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProvisionStatus,
	)
	return i, err
}

const getProjectByIDForUpdate = `-- name: GetProjectByIDForUpdate :one
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status FROM projects WHERE id = $1 FOR UPDATE
`

// The project-scoped lock serializing membership writes: role changes run
// inside a transaction and lock the project row first, so the last-owner
// count can never race a concurrent demotion.
func (q *Queries) GetProjectByIDForUpdate(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDForUpdate, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProvisionStatus,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status FROM projects WHERE organization_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Slug           string      `json:"slug"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OrganizationID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProvisionStatus,
	)
	return i, err
}

const getProjectMembership = `-- name: GetProjectMembership :one
SELECT project_id, user_id, role, created_at FROM project_memberships
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMembershipParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (ProjectMembership, error) {
	row := q.db.QueryRow(ctx, getProjectMembership, arg.ProjectID, arg.UserID)
	var i ProjectMembership
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id AS user_id, u.handle, u.display_name, pm.role, pm.created_at AS joined_at
FROM project_memberships pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.created_at, u.id
`

type ListProjectMembersRow struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Handle      string             `json:"handle"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Handle,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrganization = `-- name: ListProjectsByOrganization :many
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status FROM projects
WHERE organization_id = $1
ORDER BY created_at, id
LIMIT $3 OFFSET $2
`

type ListProjectsByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PageOffset     int32       `json:"page_offset"`
	PageSize       int32       `json:"page_size"`
}

func (q *Queries) ListProjectsByOrganization(ctx context.Context, arg ListProjectsByOrganizationParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrganization, arg.OrganizationID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProgramID,
			&i.Slug,
			&i.Name,
			&i.Purpose,
			&i.ActivityStatus,
			&i.Visibility,
			&i.MainFrozen,
			&i.GitRepositoryExternalID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ProvisionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.organization_id, p.program_id, p.slug, p.name, p.purpose, p.activity_status, p.visibility, p.main_frozen, p.git_repository_external_id, p.created_by, p.created_at, p.provision_status
FROM projects p
JOIN project_memberships m ON m.project_id = p.id
WHERE m.user_id = $1
ORDER BY p.created_at DESC, p.id
`

// Projects the user belongs to (any project membership), most recently
// created first.
func (q *Queries) ListProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProgramID,
			&i.Slug,
			&i.Name,
			&i.Purpose,
			&i.ActivityStatus,
			&i.Visibility,
			&i.MainFrozen,
			&i.GitRepositoryExternalID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ProvisionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProjects = `-- name: ListPublicProjects :many
SELECT id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status FROM projects
WHERE visibility = 'public'
ORDER BY created_at DESC, id
`

// Public projects readable by every matrix class (read_public_project,
// T0106 — anonymous included), most recently created first. The
// visibility predicate is the read policy: a private row can never reach
// this result set.
func (q *Queries) ListPublicProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listPublicProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProgramID,
			&i.Slug,
			&i.Name,
			&i.Purpose,
			&i.ActivityStatus,
			&i.Visibility,
			&i.MainFrozen,
			&i.GitRepositoryExternalID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ProvisionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectActivityStatus = `-- name: UpdateProjectActivityStatus :one
UPDATE projects
SET activity_status = $1
WHERE id = $2
RETURNING id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status
`

type UpdateProjectActivityStatusParams struct {
	ActivityStatus string      `json:"activity_status"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProjectActivityStatus(ctx context.Context, arg UpdateProjectActivityStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectActivityStatus, arg.ActivityStatus, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProvisionStatus,
	)
	return i, err
}

const updateProjectMembershipRole = `-- name: UpdateProjectMembershipRole :one
UPDATE project_memberships
SET role = $1
WHERE project_id = $2 AND user_id = $3
RETURNING project_id, user_id, role, created_at
`

type UpdateProjectMembershipRoleParams struct {
	Role      string      `json:"role"`
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateProjectMembershipRole(ctx context.Context, arg UpdateProjectMembershipRoleParams) (ProjectMembership, error) {
	row := q.db.QueryRow(ctx, updateProjectMembershipRole, arg.Role, arg.ProjectID, arg.UserID)
	var i ProjectMembership
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectSettings = `-- name: UpdateProjectSettings :one
UPDATE projects
SET purpose = $1,
    activity_status = $2
WHERE id = $3
RETURNING id, organization_id, program_id, slug, name, purpose, activity_status, visibility, main_frozen, git_repository_external_id, created_by, created_at, provision_status
`

type UpdateProjectSettingsParams struct {
	Purpose        string      `json:"purpose"`
	ActivityStatus string      `json:"activity_status"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProjectSettings(ctx context.Context, arg UpdateProjectSettingsParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectSettings, arg.Purpose, arg.ActivityStatus, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProgramID,
		&i.Slug,
		&i.Name,
		&i.Purpose,
		&i.ActivityStatus,
		&i.Visibility,
		&i.MainFrozen,
		&i.GitRepositoryExternalID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProvisionStatus,
	)
	return i, err
}
