// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases_assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (project_id, version, title, state_id, policy_version_id, org_policy_version_id, manifest, manifest_hash, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, version, title, state_id, policy_version_id, manifest, manifest_hash, created_by, created_at, org_policy_version_id
`

type CreateReleaseParams struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	Version            string      `json:"version"`
	Title              string      `json:"title"`
	StateID            pgtype.UUID `json:"state_id"`
	PolicyVersionID    pgtype.UUID `json:"policy_version_id"`
	OrgPolicyVersionID pgtype.UUID `json:"org_policy_version_id"`
	Manifest           string      `json:"manifest"`
	ManifestHash       string      `json:"manifest_hash"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, createRelease,
		arg.ProjectID,
		arg.Version,
		arg.Title,
		arg.StateID,
		arg.PolicyVersionID,
		arg.OrgPolicyVersionID,
		arg.Manifest,
		arg.ManifestHash,
		arg.CreatedBy,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.StateID,
		&i.PolicyVersionID,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OrgPolicyVersionID,
	)
	return i, err
}

const createReleaseCreation = `-- name: CreateReleaseCreation :one
INSERT INTO release_creations (project_id, idempotency_key, release_id)
VALUES ($1, $2, $3)
RETURNING id, project_id, idempotency_key, release_id, created_at
`

type CreateReleaseCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	ReleaseID      pgtype.UUID `json:"release_id"`
}

func (q *Queries) CreateReleaseCreation(ctx context.Context, arg CreateReleaseCreationParams) (ReleaseCreation, error) {
	row := q.db.QueryRow(ctx, createReleaseCreation, arg.ProjectID, arg.IdempotencyKey, arg.ReleaseID)
	var i ReleaseCreation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.ReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const createResearchAsset = `-- name: CreateResearchAsset :one
INSERT INTO research_assets (asset_type, slug, title, origin_project_id)
VALUES ($1, $2, $3, $4)
RETURNING id, asset_type, slug, title, origin_project_id, created_at, pid
`

type CreateResearchAssetParams struct {
	AssetType       string      `json:"asset_type"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	OriginProjectID pgtype.UUID `json:"origin_project_id"`
}

func (q *Queries) CreateResearchAsset(ctx context.Context, arg CreateResearchAssetParams) (ResearchAsset, error) {
	row := q.db.QueryRow(ctx, createResearchAsset,
		arg.AssetType,
		arg.Slug,
		arg.Title,
		arg.OriginProjectID,
	)
	var i ResearchAsset
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.Slug,
		&i.Title,
		&i.OriginProjectID,
		&i.CreatedAt,
		&i.Pid,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, project_id, version, title, state_id, policy_version_id, manifest, manifest_hash, created_by, created_at, org_policy_version_id FROM releases
WHERE project_id = $1 AND id = $2
`

type GetReleaseParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetRelease(ctx context.Context, arg GetReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, getRelease, arg.ProjectID, arg.ID)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.StateID,
		&i.PolicyVersionID,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OrgPolicyVersionID,
	)
	return i, err
}

const getReleaseByProjectAndVersion = `-- name: GetReleaseByProjectAndVersion :one
SELECT id, project_id, version, title, state_id, policy_version_id, manifest, manifest_hash, created_by, created_at, org_policy_version_id FROM releases
WHERE project_id = $1 AND version = $2
`

type GetReleaseByProjectAndVersionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Version   string      `json:"version"`
}

func (q *Queries) GetReleaseByProjectAndVersion(ctx context.Context, arg GetReleaseByProjectAndVersionParams) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByProjectAndVersion, arg.ProjectID, arg.Version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.StateID,
		&i.PolicyVersionID,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OrgPolicyVersionID,
	)
	return i, err
}

const getReleaseCreation = `-- name: GetReleaseCreation :one
SELECT release_id FROM release_creations
WHERE project_id = $1 AND idempotency_key = $2
`

type GetReleaseCreationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetReleaseCreation(ctx context.Context, arg GetReleaseCreationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getReleaseCreation, arg.ProjectID, arg.IdempotencyKey)
	var release_id pgtype.UUID
	err := row.Scan(&release_id)
	return release_id, err
}

const getResearchAssetVersion = `-- name: GetResearchAssetVersion :one
SELECT id, asset_id, version, source_release_id, manifest, rights_json, visibility, integrity_hash, published_by, published_at, origin_refs FROM research_asset_versions
WHERE asset_id = $1 AND version = $2
`

type GetResearchAssetVersionParams struct {
	AssetID pgtype.UUID `json:"asset_id"`
	Version string      `json:"version"`
}

func (q *Queries) GetResearchAssetVersion(ctx context.Context, arg GetResearchAssetVersionParams) (ResearchAssetVersion, error) {
	row := q.db.QueryRow(ctx, getResearchAssetVersion, arg.AssetID, arg.Version)
	var i ResearchAssetVersion
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Version,
		&i.SourceReleaseID,
		&i.Manifest,
		&i.RightsJson,
		&i.Visibility,
		&i.IntegrityHash,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.OriginRefs,
	)
	return i, err
}

const listReleaseReviews = `-- name: ListReleaseReviews :many
WITH RECURSIVE lineage(id) AS (
  SELECT project_states.id FROM project_states WHERE project_states.id = $2
  UNION
  SELECT ps.parent_state_id FROM project_states ps
  JOIN lineage l ON ps.id = l.id
  WHERE ps.parent_state_id IS NOT NULL
)
SELECT pr.number AS pull_request_number,
       pr.proposed_state_id,
       r.id,
       r.reviewer_id,
       r.review_kind,
       r.decision,
       r.body,
       r.created_at
FROM reviews r
JOIN pull_requests pr ON pr.id = r.pull_request_id
WHERE pr.target_branch_id = $1
  AND (pr.proposed_state_id IN (SELECT id FROM lineage)
       OR EXISTS (
         SELECT 1 FROM semantic_merges sm
         WHERE sm.pull_request_id = pr.id
           AND sm.result_state_id IN (SELECT id FROM lineage)
       ))
ORDER BY pr.number, r.created_at, r.id
`

type ListReleaseReviewsParams struct {
	MainBranchID pgtype.UUID `json:"main_branch_id"`
	StateID      pgtype.UUID `json:"state_id"`
}

type ListReleaseReviewsRow struct {
	PullRequestNumber int64              `json:"pull_request_number"`
	ProposedStateID   pgtype.UUID        `json:"proposed_state_id"`
	ID                pgtype.UUID        `json:"id"`
	ReviewerID        pgtype.UUID        `json:"reviewer_id"`
	ReviewKind        string             `json:"review_kind"`
	Decision          string             `json:"decision"`
	Body              string             `json:"body"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

// The review/approval record of one release (T0605, extended by T0611):
// every review row of the research PRs targeting main that either
//
//  1. proposed a state which is the released state or one of its
//     ancestors (the T0605 edge), or
//  2. were merged into the lineage — the merge row that accepted the
//     proposal recorded a result state inside that lineage
//     (semantic_merges.result_state_id, the T0611 edge).
//
// Edge 2 is what makes the states that entered main the ONE way docs/09
// §3 allows readable at all. A merge commits a NEW state whose parent is
// the target head it ran on — not the proposal (migration 00069 pins the
// triple; internal/application/merge commits BaseStateID = target head) —
// so the proposal state is never an ancestor of the accepted state, and
// edge 1 alone answers EMPTY for exactly the lineage that got there by
// being merged. Both edges stay: a proposal inside the lineage is part of
// the record whether or not it was ever merged, and dropping edge 1 would
// lose those states' reviews.
//
// The two edges are ONE predicate over ONE select, so a PR that matches
// both (its proposed state is an ancestor AND its merge result is in the
// lineage) is still one group of rows, each review row counted once: the
// union is of PRs, and a union spelled as two selects would emit that
// PR's reviews twice.
//
// No target filter is repeated on edge 2. It does not need one: the merge
// row's target branch is the branch its result state was committed on
// (00069 says so in as many words), so a result state inside the lineage
// — which is main's own chain by construction — is a merge ONTO main. The
// target filter outside names main explicitly for edge 1, where it is
// needed: a duplicate proposal of the same state against another branch is
// not part of main's acceptance record.
//
// Ordered by PR number then review time then row id (a total order — the
// release manifest's canonical sorting is the releases package's rule,
// not the store's).
func (q *Queries) ListReleaseReviews(ctx context.Context, arg ListReleaseReviewsParams) ([]ListReleaseReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReleaseReviews, arg.MainBranchID, arg.StateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleaseReviewsRow
	for rows.Next() {
		var i ListReleaseReviewsRow
		if err := rows.Scan(
			&i.PullRequestNumber,
			&i.ProposedStateID,
			&i.ID,
			&i.ReviewerID,
			&i.ReviewKind,
			&i.Decision,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, project_id, version, title, state_id, policy_version_id, manifest, manifest_hash, created_by, created_at, org_policy_version_id FROM releases
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListReleases(ctx context.Context, projectID pgtype.UUID) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Title,
			&i.StateID,
			&i.PolicyVersionID,
			&i.Manifest,
			&i.ManifestHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.OrgPolicyVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishKnowledgePublication = `-- name: PublishKnowledgePublication :one
INSERT INTO knowledge_publications (object_version_id, public_version, rights_json, published_by, pid)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, object_version_id, public_version, rights_json, published_by, published_at, pid
`

type PublishKnowledgePublicationParams struct {
	ObjectVersionID pgtype.UUID `json:"object_version_id"`
	PublicVersion   string      `json:"public_version"`
	RightsJson      []byte      `json:"rights_json"`
	PublishedBy     pgtype.UUID `json:"published_by"`
	Pid             string      `json:"pid"`
}

// The publish command's insert (T0805). This query had no producer before
// it — knowledge_publications has had no writer since migration 00010 —
// so extending it with the pid column (migration 00083) is not a change
// to a shipped writer, the way PublishResearchAssetVersion's origin_refs
// was not one for T0705.
//
// The pid is passed in and never left to the column DEFAULT: migration
// 00064 records the same decision for assets ("the application-generated
// path ... arrives with T0705 (publish)"), and a persistent identifier
// that two writers derive differently is not a persistent identity. The
// DEFAULT stays for rows written before the publish command could
// generate one.
func (q *Queries) PublishKnowledgePublication(ctx context.Context, arg PublishKnowledgePublicationParams) (KnowledgePublication, error) {
	row := q.db.QueryRow(ctx, publishKnowledgePublication,
		arg.ObjectVersionID,
		arg.PublicVersion,
		arg.RightsJson,
		arg.PublishedBy,
		arg.Pid,
	)
	var i KnowledgePublication
	err := row.Scan(
		&i.ID,
		&i.ObjectVersionID,
		&i.PublicVersion,
		&i.RightsJson,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.Pid,
	)
	return i, err
}

const publishResearchAssetVersion = `-- name: PublishResearchAssetVersion :one
INSERT INTO research_asset_versions
    (asset_id, version, source_release_id, manifest, rights_json, visibility, integrity_hash, published_by, origin_refs)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, asset_id, version, source_release_id, manifest, rights_json, visibility, integrity_hash, published_by, published_at, origin_refs
`

type PublishResearchAssetVersionParams struct {
	AssetID         pgtype.UUID `json:"asset_id"`
	Version         string      `json:"version"`
	SourceReleaseID pgtype.UUID `json:"source_release_id"`
	Manifest        []byte      `json:"manifest"`
	RightsJson      []byte      `json:"rights_json"`
	Visibility      string      `json:"visibility"`
	IntegrityHash   string      `json:"integrity_hash"`
	PublishedBy     pgtype.UUID `json:"published_by"`
	OriginRefs      []string    `json:"origin_refs"`
}

// The publish command's version insert (T0705). origin_refs is written
// here because it is NOT NULL with two CHECKs since 00064 (at least one
// element, no NULL element) and the version's provenance is exactly what
// that column is: a publish that left it to a default could not store a
// row at all. This query had no producer before T0705 — the preview
// (T0704) only reads — so extending it is not a change to a shipped
// writer; issue #225 recorded the gap when the column was added.
func (q *Queries) PublishResearchAssetVersion(ctx context.Context, arg PublishResearchAssetVersionParams) (ResearchAssetVersion, error) {
	row := q.db.QueryRow(ctx, publishResearchAssetVersion,
		arg.AssetID,
		arg.Version,
		arg.SourceReleaseID,
		arg.Manifest,
		arg.RightsJson,
		arg.Visibility,
		arg.IntegrityHash,
		arg.PublishedBy,
		arg.OriginRefs,
	)
	var i ResearchAssetVersion
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Version,
		&i.SourceReleaseID,
		&i.Manifest,
		&i.RightsJson,
		&i.Visibility,
		&i.IntegrityHash,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.OriginRefs,
	)
	return i, err
}

const recordValidationResult = `-- name: RecordValidationResult :one

INSERT INTO validation_results (project_id, state_id, gate, status, result_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, state_id, gate, status, result_json, created_at
`

type RecordValidationResultParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	StateID    pgtype.UUID `json:"state_id"`
	Gate       string      `json:"gate"`
	Status     string      `json:"status"`
	ResultJson []byte      `json:"result_json"`
}

// Releases, research assets, publications (canonical tables:
// validation_results, releases, research_assets, research_asset_versions,
// knowledge_publications). Release/asset versions are immutable (invariant 5).
func (q *Queries) RecordValidationResult(ctx context.Context, arg RecordValidationResultParams) (ValidationResult, error) {
	row := q.db.QueryRow(ctx, recordValidationResult,
		arg.ProjectID,
		arg.StateID,
		arg.Gate,
		arg.Status,
		arg.ResultJson,
	)
	var i ValidationResult
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateID,
		&i.Gate,
		&i.Status,
		&i.ResultJson,
		&i.CreatedAt,
	)
	return i, err
}
