// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases_assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (project_id, version, title, state_id, policy_version_id, manifest, manifest_hash, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, version, title, state_id, policy_version_id, manifest, manifest_hash, created_by, created_at
`

type CreateReleaseParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	Version         string      `json:"version"`
	Title           string      `json:"title"`
	StateID         pgtype.UUID `json:"state_id"`
	PolicyVersionID pgtype.UUID `json:"policy_version_id"`
	Manifest        []byte      `json:"manifest"`
	ManifestHash    string      `json:"manifest_hash"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, createRelease,
		arg.ProjectID,
		arg.Version,
		arg.Title,
		arg.StateID,
		arg.PolicyVersionID,
		arg.Manifest,
		arg.ManifestHash,
		arg.CreatedBy,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.StateID,
		&i.PolicyVersionID,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createResearchAsset = `-- name: CreateResearchAsset :one
INSERT INTO research_assets (asset_type, slug, title, origin_project_id)
VALUES ($1, $2, $3, $4)
RETURNING id, asset_type, slug, title, origin_project_id, created_at
`

type CreateResearchAssetParams struct {
	AssetType       string      `json:"asset_type"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	OriginProjectID pgtype.UUID `json:"origin_project_id"`
}

func (q *Queries) CreateResearchAsset(ctx context.Context, arg CreateResearchAssetParams) (ResearchAsset, error) {
	row := q.db.QueryRow(ctx, createResearchAsset,
		arg.AssetType,
		arg.Slug,
		arg.Title,
		arg.OriginProjectID,
	)
	var i ResearchAsset
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.Slug,
		&i.Title,
		&i.OriginProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseByProjectAndVersion = `-- name: GetReleaseByProjectAndVersion :one
SELECT id, project_id, version, title, state_id, policy_version_id, manifest, manifest_hash, created_by, created_at FROM releases
WHERE project_id = $1 AND version = $2
`

type GetReleaseByProjectAndVersionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Version   string      `json:"version"`
}

func (q *Queries) GetReleaseByProjectAndVersion(ctx context.Context, arg GetReleaseByProjectAndVersionParams) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByProjectAndVersion, arg.ProjectID, arg.Version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.StateID,
		&i.PolicyVersionID,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getResearchAssetVersion = `-- name: GetResearchAssetVersion :one
SELECT id, asset_id, version, source_release_id, manifest, rights_json, visibility, integrity_hash, published_by, published_at FROM research_asset_versions
WHERE asset_id = $1 AND version = $2
`

type GetResearchAssetVersionParams struct {
	AssetID pgtype.UUID `json:"asset_id"`
	Version string      `json:"version"`
}

func (q *Queries) GetResearchAssetVersion(ctx context.Context, arg GetResearchAssetVersionParams) (ResearchAssetVersion, error) {
	row := q.db.QueryRow(ctx, getResearchAssetVersion, arg.AssetID, arg.Version)
	var i ResearchAssetVersion
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Version,
		&i.SourceReleaseID,
		&i.Manifest,
		&i.RightsJson,
		&i.Visibility,
		&i.IntegrityHash,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const publishKnowledgePublication = `-- name: PublishKnowledgePublication :one
INSERT INTO knowledge_publications (object_version_id, public_version, rights_json, published_by)
VALUES ($1, $2, $3, $4)
RETURNING id, object_version_id, public_version, rights_json, published_by, published_at
`

type PublishKnowledgePublicationParams struct {
	ObjectVersionID pgtype.UUID `json:"object_version_id"`
	PublicVersion   string      `json:"public_version"`
	RightsJson      []byte      `json:"rights_json"`
	PublishedBy     pgtype.UUID `json:"published_by"`
}

func (q *Queries) PublishKnowledgePublication(ctx context.Context, arg PublishKnowledgePublicationParams) (KnowledgePublication, error) {
	row := q.db.QueryRow(ctx, publishKnowledgePublication,
		arg.ObjectVersionID,
		arg.PublicVersion,
		arg.RightsJson,
		arg.PublishedBy,
	)
	var i KnowledgePublication
	err := row.Scan(
		&i.ID,
		&i.ObjectVersionID,
		&i.PublicVersion,
		&i.RightsJson,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const publishResearchAssetVersion = `-- name: PublishResearchAssetVersion :one
INSERT INTO research_asset_versions
    (asset_id, version, source_release_id, manifest, rights_json, visibility, integrity_hash, published_by)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, asset_id, version, source_release_id, manifest, rights_json, visibility, integrity_hash, published_by, published_at
`

type PublishResearchAssetVersionParams struct {
	AssetID         pgtype.UUID `json:"asset_id"`
	Version         string      `json:"version"`
	SourceReleaseID pgtype.UUID `json:"source_release_id"`
	Manifest        []byte      `json:"manifest"`
	RightsJson      []byte      `json:"rights_json"`
	Visibility      string      `json:"visibility"`
	IntegrityHash   string      `json:"integrity_hash"`
	PublishedBy     pgtype.UUID `json:"published_by"`
}

func (q *Queries) PublishResearchAssetVersion(ctx context.Context, arg PublishResearchAssetVersionParams) (ResearchAssetVersion, error) {
	row := q.db.QueryRow(ctx, publishResearchAssetVersion,
		arg.AssetID,
		arg.Version,
		arg.SourceReleaseID,
		arg.Manifest,
		arg.RightsJson,
		arg.Visibility,
		arg.IntegrityHash,
		arg.PublishedBy,
	)
	var i ResearchAssetVersion
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Version,
		&i.SourceReleaseID,
		&i.Manifest,
		&i.RightsJson,
		&i.Visibility,
		&i.IntegrityHash,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const recordValidationResult = `-- name: RecordValidationResult :one

INSERT INTO validation_results (project_id, state_id, gate, status, result_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, state_id, gate, status, result_json, created_at
`

type RecordValidationResultParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	StateID    pgtype.UUID `json:"state_id"`
	Gate       string      `json:"gate"`
	Status     string      `json:"status"`
	ResultJson []byte      `json:"result_json"`
}

// Releases, research assets, publications (canonical tables:
// validation_results, releases, research_assets, research_asset_versions,
// knowledge_publications). Release/asset versions are immutable (invariant 5).
func (q *Queries) RecordValidationResult(ctx context.Context, arg RecordValidationResultParams) (ValidationResult, error) {
	row := q.db.QueryRow(ctx, recordValidationResult,
		arg.ProjectID,
		arg.StateID,
		arg.Gate,
		arg.Status,
		arg.ResultJson,
	)
	var i ValidationResult
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateID,
		&i.Gate,
		&i.Status,
		&i.ResultJson,
		&i.CreatedAt,
	)
	return i, err
}
