// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rsg.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :one

INSERT INTO branches (project_id, name, visibility, purpose, git_ref, base_state_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at
`

type CreateBranchParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Name        string      `json:"name"`
	Visibility  string      `json:"visibility"`
	Purpose     *string     `json:"purpose"`
	GitRef      string      `json:"git_ref"`
	BaseStateID pgtype.UUID `json:"base_state_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

// RSG state model (canonical tables: branches, project_states, state_commits).
// Branch = research state evolution path; commit = state transition
// (docs/03_GLOSSARY_DOMAIN_MODEL.md, invariants 2-4).
// CreateBranch is the raw, unguarded insert: seeding fixtures and the
// canonical headless form (base_state_id NULL — a branch before its first
// state). The domain creation path is CreateBranchFromState below, which
// re-checks the fork point's project inside the insert.
func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.ProjectID,
		arg.Name,
		arg.Visibility,
		arg.Purpose,
		arg.GitRef,
		arg.BaseStateID,
		arg.CreatedBy,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Visibility,
		&i.Purpose,
		&i.GitRef,
		&i.BaseStateID,
		&i.LifecycleState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createBranchFromState = `-- name: CreateBranchFromState :one
INSERT INTO branches (project_id, name, visibility, purpose, git_ref, base_state_id, created_by)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (
  SELECT 1 FROM project_states
  WHERE id = $6 AND project_id = $1
)
RETURNING id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at
`

type CreateBranchFromStateParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Name        string      `json:"name"`
	Visibility  string      `json:"visibility"`
	Purpose     *string     `json:"purpose"`
	GitRef      string      `json:"git_ref"`
	BaseStateID pgtype.UUID `json:"base_state_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

// Guarded insert (T0205): a branch always forks a state of the SAME
// project — the EXISTS re-checks the fork point inside the insert, so a
// base state of another project (or a missing one) yields zero rows
// instead of a row, and the adapter reports ErrBaseStateNotFound for
// both without leaking which state exists where. The project row itself is
// read (and visibility-defaulted against) in the same transaction by the
// adapter.
func (q *Queries) CreateBranchFromState(ctx context.Context, arg CreateBranchFromStateParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranchFromState,
		arg.ProjectID,
		arg.Name,
		arg.Visibility,
		arg.Purpose,
		arg.GitRef,
		arg.BaseStateID,
		arg.CreatedBy,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Visibility,
		&i.Purpose,
		&i.GitRef,
		&i.BaseStateID,
		&i.LifecycleState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectState = `-- name: CreateProjectState :one
INSERT INTO project_states (project_id, branch_id, parent_state_id, state_hash, git_commit_sha, manifest_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, branch_id, parent_state_id, state_hash, git_commit_sha, manifest_version, created_at
`

type CreateProjectStateParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	BranchID        pgtype.UUID `json:"branch_id"`
	ParentStateID   pgtype.UUID `json:"parent_state_id"`
	StateHash       string      `json:"state_hash"`
	GitCommitSha    *string     `json:"git_commit_sha"`
	ManifestVersion string      `json:"manifest_version"`
}

func (q *Queries) CreateProjectState(ctx context.Context, arg CreateProjectStateParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, createProjectState,
		arg.ProjectID,
		arg.BranchID,
		arg.ParentStateID,
		arg.StateHash,
		arg.GitCommitSha,
		arg.ManifestVersion,
	)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.ParentStateID,
		&i.StateHash,
		&i.GitCommitSha,
		&i.ManifestVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createStateCommit = `-- name: CreateStateCommit :one
INSERT INTO state_commits
    (project_id, branch_id, base_state_id, result_state_id, actor_id, via, message, operation_summary)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, branch_id, base_state_id, result_state_id, actor_id, via, message, operation_summary, created_at
`

type CreateStateCommitParams struct {
	ProjectID        pgtype.UUID `json:"project_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	BaseStateID      pgtype.UUID `json:"base_state_id"`
	ResultStateID    pgtype.UUID `json:"result_state_id"`
	ActorID          pgtype.UUID `json:"actor_id"`
	Via              string      `json:"via"`
	Message          string      `json:"message"`
	OperationSummary []byte      `json:"operation_summary"`
}

func (q *Queries) CreateStateCommit(ctx context.Context, arg CreateStateCommitParams) (StateCommit, error) {
	row := q.db.QueryRow(ctx, createStateCommit,
		arg.ProjectID,
		arg.BranchID,
		arg.BaseStateID,
		arg.ResultStateID,
		arg.ActorID,
		arg.Via,
		arg.Message,
		arg.OperationSummary,
	)
	var i StateCommit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.BaseStateID,
		&i.ResultStateID,
		&i.ActorID,
		&i.Via,
		&i.Message,
		&i.OperationSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at FROM branches WHERE id = $1
`

func (q *Queries) GetBranchByID(ctx context.Context, id pgtype.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Visibility,
		&i.Purpose,
		&i.GitRef,
		&i.BaseStateID,
		&i.LifecycleState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchByProjectAndID = `-- name: GetBranchByProjectAndID :one
SELECT id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at FROM branches WHERE id = $1 AND project_id = $2
`

type GetBranchByProjectAndIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// Project-scoped read: a branch id of another project matches nothing and
// reports the same "not found" outcome (never leak another project's
// entity existence, docs/45).
func (q *Queries) GetBranchByProjectAndID(ctx context.Context, arg GetBranchByProjectAndIDParams) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByProjectAndID, arg.ID, arg.ProjectID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Visibility,
		&i.Purpose,
		&i.GitRef,
		&i.BaseStateID,
		&i.LifecycleState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchByProjectAndIDForUpdate = `-- name: GetBranchByProjectAndIDForUpdate :one
SELECT id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at FROM branches
WHERE id = $1 AND project_id = $2
FOR UPDATE
`

type GetBranchByProjectAndIDForUpdateParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// The locked branch read (T0406, from the T0402 review): the merge reads
// both branches' lifecycle and head inside one transaction and must not
// have a concurrent merge commit between that read and its own write.
// Locking the rows here makes the pair of readers serialize on the
// branches themselves; the states commit's head CAS (UpdateBranchBaseState)
// is the second layer, and both fail closed.
func (q *Queries) GetBranchByProjectAndIDForUpdate(ctx context.Context, arg GetBranchByProjectAndIDForUpdateParams) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByProjectAndIDForUpdate, arg.ID, arg.ProjectID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Visibility,
		&i.Purpose,
		&i.GitRef,
		&i.BaseStateID,
		&i.LifecycleState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestProjectState = `-- name: GetLatestProjectState :one
SELECT id, project_id, branch_id, parent_state_id, state_hash, git_commit_sha, manifest_version, created_at FROM project_states
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The project's most recent state (T0208): the default fork point for a
// branch created without an explicit base_ref. Deterministic on (created_at,
// id): states created in one transaction share a timestamp, the id breaks
// the tie.
func (q *Queries) GetLatestProjectState(ctx context.Context, projectID pgtype.UUID) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getLatestProjectState, projectID)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.ParentStateID,
		&i.StateHash,
		&i.GitCommitSha,
		&i.ManifestVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectStateByHash = `-- name: GetProjectStateByHash :one
SELECT id, project_id, branch_id, parent_state_id, state_hash, git_commit_sha, manifest_version, created_at FROM project_states WHERE project_id = $1 AND state_hash = $2
`

type GetProjectStateByHashParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	StateHash string      `json:"state_hash"`
}

func (q *Queries) GetProjectStateByHash(ctx context.Context, arg GetProjectStateByHashParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getProjectStateByHash, arg.ProjectID, arg.StateHash)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.ParentStateID,
		&i.StateHash,
		&i.GitCommitSha,
		&i.ManifestVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectStateByID = `-- name: GetProjectStateByID :one
SELECT id, project_id, branch_id, parent_state_id, state_hash, git_commit_sha, manifest_version, created_at FROM project_states WHERE id = $1
`

func (q *Queries) GetProjectStateByID(ctx context.Context, id pgtype.UUID) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getProjectStateByID, id)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.ParentStateID,
		&i.StateHash,
		&i.GitCommitSha,
		&i.ManifestVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getStateCommitByID = `-- name: GetStateCommitByID :one
SELECT id, project_id, branch_id, base_state_id, result_state_id, actor_id, via, message, operation_summary, created_at FROM state_commits WHERE id = $1
`

func (q *Queries) GetStateCommitByID(ctx context.Context, id pgtype.UUID) (StateCommit, error) {
	row := q.db.QueryRow(ctx, getStateCommitByID, id)
	var i StateCommit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.BaseStateID,
		&i.ResultStateID,
		&i.ActorID,
		&i.Via,
		&i.Message,
		&i.OperationSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listBranchesByProject = `-- name: ListBranchesByProject :many
SELECT id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at FROM branches
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListBranchesByProject(ctx context.Context, projectID pgtype.UUID) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranchesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Visibility,
			&i.Purpose,
			&i.GitRef,
			&i.BaseStateID,
			&i.LifecycleState,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStatesByBranch = `-- name: ListProjectStatesByBranch :many
SELECT id, project_id, branch_id, parent_state_id, state_hash, git_commit_sha, manifest_version, created_at FROM project_states
WHERE branch_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListProjectStatesByBranch(ctx context.Context, branchID pgtype.UUID) ([]ProjectState, error) {
	rows, err := q.db.Query(ctx, listProjectStatesByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectState
	for rows.Next() {
		var i ProjectState
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BranchID,
			&i.ParentStateID,
			&i.StateHash,
			&i.GitCommitSha,
			&i.ManifestVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateCommitsByBranch = `-- name: ListStateCommitsByBranch :many
SELECT id, project_id, branch_id, base_state_id, result_state_id, actor_id, via, message, operation_summary, created_at FROM state_commits
WHERE branch_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListStateCommitsByBranch(ctx context.Context, branchID pgtype.UUID) ([]StateCommit, error) {
	rows, err := q.db.Query(ctx, listStateCommitsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StateCommit
	for rows.Next() {
		var i StateCommit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BranchID,
			&i.BaseStateID,
			&i.ResultStateID,
			&i.ActorID,
			&i.Via,
			&i.Message,
			&i.OperationSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateObjectVersionsByState = `-- name: ListStateObjectVersionsByState :many

SELECT id, object_id, version_no, state_id, branch_id, schema_id, schema_version, title, lifecycle_state, payload, visibility_policy_id, integrity_hash, created_by, created_at FROM scientific_object_versions
WHERE state_id = $1
ORDER BY created_at, id
`

// The state snapshot projections (docs/21 §5, docs/07 §7): a state's
// direct members are the version rows whose state_id equals it — the
// transition each row was created in. Rebuildable from the canonical
// history by construction.
func (q *Queries) ListStateObjectVersionsByState(ctx context.Context, stateID pgtype.UUID) ([]ScientificObjectVersion, error) {
	rows, err := q.db.Query(ctx, listStateObjectVersionsByState, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScientificObjectVersion
	for rows.Next() {
		var i ScientificObjectVersion
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.VersionNo,
			&i.StateID,
			&i.BranchID,
			&i.SchemaID,
			&i.SchemaVersion,
			&i.Title,
			&i.LifecycleState,
			&i.Payload,
			&i.VisibilityPolicyID,
			&i.IntegrityHash,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateRelationVersionsByState = `-- name: ListStateRelationVersionsByState :many
SELECT id, relation_id, version_no, state_id, relation_type, source_object_version_id, target_object_version_id, payload, integrity_hash, created_by, created_at FROM relation_versions
WHERE state_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListStateRelationVersionsByState(ctx context.Context, stateID pgtype.UUID) ([]RelationVersion, error) {
	rows, err := q.db.Query(ctx, listStateRelationVersionsByState, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationVersion
	for rows.Next() {
		var i RelationVersion
		if err := rows.Scan(
			&i.ID,
			&i.RelationID,
			&i.VersionNo,
			&i.StateID,
			&i.RelationType,
			&i.SourceObjectVersionID,
			&i.TargetObjectVersionID,
			&i.Payload,
			&i.IntegrityHash,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBranchLifecycle = `-- name: SetBranchLifecycle :one
UPDATE branches
SET lifecycle_state = $1
WHERE id = $2
  AND project_id = $3
  AND name <> 'main'
  AND lifecycle_state = 'active'
RETURNING id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at
`

type SetBranchLifecycleParams struct {
	LifecycleState string      `json:"lifecycle_state"`
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// The lifecycle compare-and-swap (T0205): active → merged | aborted is
// the only transition (docs/43), terminal once made. Zero rows mean
// either the branch is not in the project, it is main (protected — its
// lifecycle is the project's), or it already closed; the adapter
// distinguishes by one read.
func (q *Queries) SetBranchLifecycle(ctx context.Context, arg SetBranchLifecycleParams) (Branch, error) {
	row := q.db.QueryRow(ctx, setBranchLifecycle, arg.LifecycleState, arg.ID, arg.ProjectID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Visibility,
		&i.Purpose,
		&i.GitRef,
		&i.BaseStateID,
		&i.LifecycleState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateBranchBaseState = `-- name: UpdateBranchBaseState :one
UPDATE branches
SET base_state_id = $1
WHERE id = $2
  AND project_id = $3
  AND lifecycle_state = 'active'
  AND base_state_id IS NOT DISTINCT FROM $4
RETURNING id, project_id, name, visibility, purpose, git_ref, base_state_id, lifecycle_state, created_by, created_at
`

type UpdateBranchBaseStateParams struct {
	BaseStateID         pgtype.UUID `json:"base_state_id"`
	ID                  pgtype.UUID `json:"id"`
	ProjectID           pgtype.UUID `json:"project_id"`
	ExpectedBaseStateID pgtype.UUID `json:"expected_base_state_id"`
}

// UpdateBranchBaseState is the branch head compare-and-swap behind
// CommitState (T0204): the head pointer advances to the new state only
// while it still equals the base the commit was built on, so the branch
// chain stays linear and concurrent commits serialize into one winner and
// stable BRANCH_STATE_CONFLICT losers. project_id is part of the guard: a
// branch of another project never matches, and the caller-side read after
// zero rows reports the same "not found" outcome for it (never leak
// another project's entity existence).
//
// T0205 adds the lifecycle guard: a merged/aborted branch's head never
// moves (docs/43: history immutable), so the CAS also requires the branch
// to be active. The adapter's read after zero rows reports that case as
// *states.BranchNotActiveError instead of a conflict.
func (q *Queries) UpdateBranchBaseState(ctx context.Context, arg UpdateBranchBaseStateParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranchBaseState,
		arg.BaseStateID,
		arg.ID,
		arg.ProjectID,
		arg.ExpectedBaseStateID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Visibility,
		&i.Purpose,
		&i.GitRef,
		&i.BaseStateID,
		&i.LifecycleState,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
