// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchDocuments = `-- name: SearchDocuments :many
SELECT entity_ref, entity_type, visibility, project_id, title, content, structured, updated_at,
       ts_rank(to_tsvector('simple', title || ' ' || content), plainto_tsquery('simple', $1)) AS rank
FROM search_documents
WHERE to_tsvector('simple', title || ' ' || content) @@ plainto_tsquery('simple', $1)
  AND (visibility = 'public' OR project_id = ANY($2::uuid[]))
ORDER BY rank DESC, entity_ref
LIMIT $4 OFFSET $3
`

type SearchDocumentsParams struct {
	Query             string        `json:"query"`
	AllowedProjectIds []pgtype.UUID `json:"allowed_project_ids"`
	PageOffset        int32         `json:"page_offset"`
	PageSize          int32         `json:"page_size"`
}

type SearchDocumentsRow struct {
	EntityRef  string             `json:"entity_ref"`
	EntityType string             `json:"entity_type"`
	Visibility string             `json:"visibility"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Structured []byte             `json:"structured"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Rank       float32            `json:"rank"`
}

// Access control is enforced HERE, not delegated to a caller.
//
// The query returns a row only if it is public, or if its project is
// explicitly listed in allowed_project_ids. Passing an empty array therefore
// yields public rows only — never the whole table. That property is the point:
// a query that cannot even accept an actor's scope cannot enforce one, and the
// previous unfiltered form returned every matching row regardless of
// visibility.
//
// docs/54 ranks "private project/branch content appearing in Search" as its
// top-severity scenario, and docs/23 §5 requires tenant/project/object policy
// filtering on every query, search, export and download. Master Gate E ("Search
// 无 private leakage") holds this invariant too.
func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments,
		arg.Query,
		arg.AllowedProjectIds,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentsRow
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.EntityRef,
			&i.EntityType,
			&i.Visibility,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Structured,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchDocument = `-- name: UpsertSearchDocument :exec

INSERT INTO search_documents (entity_ref, entity_type, visibility, project_id, title, content, structured)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (entity_ref) DO UPDATE SET
    entity_type = EXCLUDED.entity_type,
    visibility  = EXCLUDED.visibility,
    project_id  = EXCLUDED.project_id,
    title       = EXCLUDED.title,
    content     = EXCLUDED.content,
    structured  = EXCLUDED.structured,
    updated_at  = now()
`

type UpsertSearchDocumentParams struct {
	EntityRef  string      `json:"entity_ref"`
	EntityType string      `json:"entity_type"`
	Visibility string      `json:"visibility"`
	ProjectID  pgtype.UUID `json:"project_id"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	Structured []byte      `json:"structured"`
}

// Search projection (canonical table: search_documents). Rebuildable by
// construction (docs/14: Postgres FTS + structured filters; embeddings are a
// later concern, OpenSearch explicitly post-V1).
func (q *Queries) UpsertSearchDocument(ctx context.Context, arg UpsertSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertSearchDocument,
		arg.EntityRef,
		arg.EntityType,
		arg.Visibility,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.Structured,
	)
	return err
}
