// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (handle, email, display_name)
VALUES ($1, $2, $3)
RETURNING id, handle, email, display_name, created_at, disabled_at, password_hash
`

type CreateUserParams struct {
	Handle      string  `json:"handle"`
	Email       *string `json:"email"`
	DisplayName string  `json:"display_name"`
}

// Users (canonical table: users).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Handle, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, handle, email, display_name, created_at, disabled_at, password_hash FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, handle, email, display_name, created_at, disabled_at, password_hash FROM users WHERE handle = $1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, handle, email, display_name, created_at, disabled_at, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, handle, email, display_name, created_at, disabled_at, password_hash FROM users
ORDER BY created_at, id
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
