#!/bin/sh
# shellcheck disable=SC2086  # mode_args re-splitting is intentional: the token
#                            # records are plain text and splitting only over-blocks
# shellcheck disable=SC2016  # case patterns match literal $HOME, not its value
# worker-guard.sh — PreToolUse guard hook for independent Claude Code Workers.
#
# This is the canonical Worker isolation guard, generated by `rddev worker
# spawn` into .rddev/workers/<TASK>/guard/worker-guard.sh and wired into the
# Worker's Claude Code session via worker-settings.json. It is a port of the
# Supervisor's manual .rddev/dispatch harness (T0010); the ported behaviour is
# documented in tasks/decisions.md (L1-20260912-3/9/13/16) and
# specs/orchestrator/worker-permissions.yaml.
#
# What it enforces (every rule has a two-sided regression test in
# tests/worker-guard/guard-regression.sh):
#   - git control-plane subcommands are blocked in *command position* while
#     read-only git stays usable; a forbidden word in an argument (e.g.
#     `grep -n "service" docs/`) is NOT matched, and neither is `echo "git commit"`;
#   - EVERY separator the shell honours starts a new command position: `;`,
#     `|`, `&&`, `||`, `&` and a newline. A verb on its own line is refused
#     exactly as it is refused on the first line, for every rule below that
#     keys off command position. (A newline reaches the tokenizer as a
#     newline: the command text is JSON-decoded, never text-scanned — see
#     json_string below for what a scan did to the `\n` escape);
#   - gh/glab/tea CLIs and privilege escalation (sudo/su/doas/pkexec) are
#     blocked entirely;
#   - Docker socket access is blocked except `docker --version` /
#     `docker compose version` / `docker-compose version`, unless the task was
#     spawned with an explicit per-task Docker grant (POST_WORKER_DOCKER_GRANT=1
#     via rddev worker spawn --docker);
#   - file reads (Read/Grep/Glob/NotebookRead) cannot reach credential stores
#     (~/.config/gh, ~/.ssh, ~/.gnupg, ~/.docker, ~/.aws, ~/.git-credentials,
#     ~/.netrc, ~/.claude), any .env file except .env.example, or the repo's
#     .rddev/ runtime state outside the Worker's own worktree and result dir;
#     the file-writing tools below are held to that same read confinement, so
#     a tool that reads the file it is about to change is refused on the same
#     terms as the Read tool;
#   - writes are confined to the Worker's own worktree, its own result dir and
#     /tmp, whichever tool makes them: shell writes (rm/cp/mv/ln/install/tee
#     and >/>> redirections) and file-writing tool calls (Write/Edit/MultiEdit/
#     NotebookEdit) go through the same normalisation and the same allow-set.
#     ~ / $HOME / ${HOME} are always outside, and an unresolvable $ expansion
#     fails closed;
#   - `printenv <credential-name>` probes are blocked (the variables are
#     already stripped from the environment at spawn — the probe refusal
#     exists so no probe can ever observe a value).
#
# Known limits (by design — this hook is defence in depth, not the only line):
#   - The tokenizer splits mode_args on spaces, so a quoted argument containing
#     a forbidden word in command position can over-block (safe direction).
#     `sh -c '...'` and friends are deliberately treated as opaque (the shell
#     inside would escape the analysis) and are confined by the deny layer +
#     collect-time invariants instead.
#   - Command-position analysis reads the command TEXT. It does not run the
#     shell: `$var`, `${var}` and `$(...)` are not expanded, so a verb that is
#     only spelled out by an expansion (`c=cp; $c x /etc/y`) is not matched,
#     and neither is a command a script or a downloaded file runs. `$` in a
#     *path* is handled on the write side, where an unresolvable expansion
#     fails closed.
#   - The read side is enforced for the file-path TOOLS (Read/Grep/Glob/
#     NotebookRead, plus the file writers, which read what they change), not
#     for shell commands: `cat <credential store>` is not inspected here. That
#     boundary is stated in the Worker contract too
#     (TestTheGuardClaimInTheSystemPromptIsTrue binds the two).
#   - Redirections on a quoted path are conservatively over-blocked when the
#     quote state cannot be resolved; unresolvable $ expansions fail closed.
#   - WHICH tools reach this hook is worker-settings.json's matcher, not this
#     script's business — a tool the matcher does not name is a tool that
#     never arrives here. That seam is where Write/Edit escaped the write
#     envelope until T1219 (they were in permissions.allow, so dontAsk let
#     them run bare, and the matcher never invoked the guard for them). It is
#     now checked from both sides: TestWriteGuardFiles derives the matcher's
#     required contents from permissions.allow, and
#     TestGuardMatcherNamesExactlyTheKnownTools fixes the set in both
#     directions, so a tool that becomes allowed without becoming visible
#     here fails a test instead of silently escaping.
#
# Hook protocol: the tool call JSON arrives on stdin. On a violation the guard
# prints {"decision":"block","reason":...} on stdout, the human-readable
# reason on stderr, and exits 2 (Claude Code reports the block). Otherwise it
# exits 0 silently (allow). A tool call whose JSON cannot be read is REFUSED,
# and so is one whose tool name, command or path field holds something other
# than the string this hook has to read, and so is a Bash call with no command
# string in it: deciding on a document — or a field — the guard could not read
# is exactly the fail-open this file exists to close. (Measured: refusing the
# shape-mismatched field breaks no real call. Over this repo's 54031 recorded
# tool_use calls the fields read here are strings or absent every time.)
# Only an *unknown tool name* exits 0 — no path or command policy applies to
# it, and refusing it would break the Worker contract with a false positive.
#
# Environment (all set by rddev worker spawn):
#   POST_REPO_ROOT         absolute repo root (main checkout)
#   POST_WORKER_TASK_ID    task id (T0010)
#   POST_WORKER_WORKTREE   absolute path of this Worker's worktree
#   POST_WORKER_RESULT_DIR absolute path of this Worker's result dir
#   POST_WORKER_DOCKER_GRANT "1" iff the task carries an explicit Docker grant

set -f # never pathname-expand analysed command words or targets

# block prints the JSON decision and the reason, then exits 2 (deny).
block() {
	reason=$1
	escaped=$(printf '%s' "$reason" | sed 's/\\/\\\\/g; s/"/\\"/g')
	printf '{"decision":"block","reason":"%s"}\n' "$escaped"
	printf 'blocked: %s\n' "$reason" >&2
	exit 2
}

# json_bool_true KEYPATH prints "yes" when the boolean at that dotted path is
# true, and prints "no" when the key is absent or holds false (or null). Exit 0
# when the payload parsed; non-zero when it did not — or when the key holds a
# value that is not a boolean, which is the same "cannot read this field"
# situation from the guard's side and fails closed the same way (a string
# "yes" is not the true the consumer acts on, so guessing it either way is a
# decision taken on bytes the guard could not read).
#
# This parses the tool input with a real JSON decoder instead of scanning the
# raw text. Scanning is wrong in principle: the same document also carries the
# model-controlled `command` string, and duplicate/escaped keys resolve
# differently in a text scan than in the JSON the consumer actually reads.
# (A security review raised this as a fail-open. Testing showed the obvious
# injection - putting the key inside the command text - does NOT work, because
# a quote inside a JSON string is escaped, so the raw key never appears
# contiguously. It is still the wrong shape for a security check, and a
# future serialisation change could make it exploitable, so it is parsed.)
json_bool_true() {
	python3 -c '
import json, sys
try:
    doc = json.load(sys.stdin)
except Exception:
    sys.exit(3)
cur = doc
for part in sys.argv[1].split("."):
    if not isinstance(cur, dict) or part not in cur:
        print("no"); sys.exit(0)
    cur = cur[part]
if cur is not None and not isinstance(cur, bool):
    sys.exit(4)
print("yes" if cur is True else "no")
' "$1"
}

# json_string KEYPATH prints the string at that dotted path in the tool-call
# JSON on stdin, and prints nothing when the key is absent or null. Exit 0 when
# the payload parsed and the field was readable; non-zero when it did not
# parse, or when the field is PRESENT but holds something other than a string.
# Callers fail closed on both, rather than decide on a document — or a field —
# they could not read.
#
# The second arm is not hypothetical: a path check should not rest on the
# encoding of its input, and an expected-string field arriving as an object is
# exactly the shape a serialisation change would produce (and exactly the shape
# the text scan below mis-read: it took the FIRST unescaped `"file_path"` in
# the raw text, so a nested one won). Measured over this repo's 54031 recorded
# tool_use calls (.rddev/workers/*/worker.log): the fields read here are
# strings or absent every time — no legitimate call carries a non-string path,
# command or tool name — so refusing the shape costs nothing real and is the
# same fail-closed direction as the missing contract environment.
#
# It backs every string the guard decides on: tool_name (which chooses the
# policy branch), the path fields of the file tools, and — since T1221 — the
# Bash `command`. The command it replaced was the LAST text scan in this file,
# and the one with the widest blast radius, because every command-position
# rule reads from it.
#
# WHAT THE SCAN DID, MEASURED, so the reason is not just "scanning is wrong in
# principle". `json_field` (removed here) treated a backslash as "take the next
# character literally", which is right for exactly two JSON escapes and wrong
# for the rest:
#
#   {"probe":"a\nb"}      ->  anb       (the \n escape became the letter n)
#   {"probe":"a\tb"}      ->  atb
#   {"probe":"a\\u0041b"} ->  au0041b
#   {"probe":"a\"b"}      ->  a"b       (correct)
#   {"probe":"a\\b"}      ->  a\b       (correct)
#
# A multi-line command reaches this hook the way Claude Code sends it — one
# JSON string, so `true` + newline + `cp /tmp/x /etc/evil` arrives as
# `"true\ncp /tmp/x /etc/evil"` — and the scan decoded that to the single word
# `truencp /tmp/x /etc/evil`. The tokenizer then saw ONE command, whose binary
# is `truencp`, so the write rule, the privilege-escalation rule, the
# control-plane CLIs, git and printenv were all bypassed by pressing Enter.
# The tokenizer was never at fault: fed a real newline it resets command
# position correctly (that is what the regression cases now pin).
#
# Path fields are parsed for the reason run_in_background is parsed: a text
# scan resolves keys differently from the JSON the consumer actually reads.
#
# WHAT WAS MEASURED, so this comment is not wider than the fact. Putting the
# key inside an ESCAPED string literal does NOT fool the scan — a quote inside
# a JSON string is escaped, so `"file_path"` never appears contiguously inside
# Write.content and the scan goes on to find the real key (the run_in_background
# comment above reached the same conclusion about `command`, and it is right).
# What DOES fool it is a key appearing unescaped ahead of the real one, which a
# nested object in a model-controlled field produces:
#
#   {"new_string":{"file_path":"/safe"},"file_path":"/etc/evil"}
#
# reads as /safe to a scan, and /etc/evil is never examined. That payload is
# not producible through today's harness — tool inputs are schema-validated
# before dispatch — so this is a defence against a SERIALISATION CHANGE rather
# than against a live exploit, taken because a path check should not rest on
# the current encoding of its input. The second half is the non-zero exit: an
# unreadable payload — or an expected-string field holding something else — is
# refused, where a text scan would silently yield no path and let the call
# through. Both halves have regression cases.
json_string() {
	python3 -c '
import json, sys
try:
    doc = json.load(sys.stdin)
except Exception:
    sys.exit(3)
cur = doc
for part in sys.argv[1].split("."):
    if not isinstance(cur, dict) or part not in cur:
        print(""); sys.exit(0)
    cur = cur[part]
if cur is not None and not isinstance(cur, str):
    sys.exit(4)
print(cur if isinstance(cur, str) else "")
' "$1"
}

# command_records emits the parsed Bash command as one record per line:
#   BIN:<word>  the first non-assignment word of a command segment — the
#               binary in *command position*: after ; | && || &, and at the
#               start of EVERY LINE, because awk reads one record per line and
#               each record resets `pending` below. That reset is what makes a
#               newline a separator here; the command text reaches this
#               function with real newlines because it was JSON-decoded
#               (json_string), never text-scanned.
#   ARG:<word>  every other word of the segment, in order
#   SEG         end of one segment
# Quoted strings are kept intact: `grep -n "service" docs/` yields no
# forbidden word and `echo "git commit"` is not mistaken for git. `env` is
# followed: its first non-flag, non-assignment argument runs as a command and
# is emitted as BIN too (`env FOO=x git push` must not escape the git check).
command_records() {
	printf '%s\n' "$1" | awk '
	function flush(		w) {
		w = word
		word = ""
		if (w == "") return
		if (skip_env_val) { skip_env_val = 0; print "ARG:" w; return }
		if (env_follow) {
			if (w ~ /^[A-Za-z_][A-Za-z0-9_]*=/) { print "ARG:" w; return }
			if (w ~ /^-/) {
				print "ARG:" w
				# env option flags take a value; consume it so it is not
				# mistaken for the command env runs
				if (w ~ /^-u$|^-i$|^-C$|^--unset$|^--chdir$|^-S$|^--split-string$|^-v$|^--debug$/)
					skip_env_val = 1
				return
			}
			print "BIN:" w
			env_follow = 0
			return
		}
		if (pending) {
			# a VAR=value assignment is not the command; keep looking
			if (w ~ /^[A-Za-z_][A-Za-z0-9_]*=/) return
			print "BIN:" w
			pending = 0
			if (w == "env") env_follow = 1
			return
		}
		print "ARG:" w
	}
	{
		line = $0
		n = length(line)
		pending = 1
		env_follow = 0
		skip_env_val = 0
		word = ""
		quote = ""
		for (i = 1; i <= n; i++) {
			c = substr(line, i, 1)
			if (quote != "") {
				if (c == quote) quote = ""
				else word = word c
				continue
			}
			if (c == "\\") {
				if (i < n) { word = word substr(line, i + 1, 1); i++ }
				continue
			}
			if (c == "\x27" || c == "\"") { quote = c; continue }
			if (c == ";" || c == "|" || c == "&") {
				flush()
				if (c != ";" && substr(line, i + 1, 1) == c) i++ # && or ||
				print "SEG"
				# a new segment starts at command position again
				pending = 1
				env_follow = 0
				skip_env_val = 0
				continue
			}
			if (c == " " || c == "\t") { flush(); continue }
			word = word c
		}
		flush()
		print "SEG"
	}'
}

# resolve_path prints the absolute form of a path the Worker named, or one of
# the markers OUTSIDE / DYNAMIC / UNRESOLVABLE which callers treat as failing
# closed. Relative paths resolve against the Worker's worktree (its shell
# cwd). ~ / $HOME / ${HOME} are always outside the allowed set.
resolve_path() {
	p=$1
	case "$p" in
		~*|*'$HOME'*|*'${HOME}'*) echo "OUTSIDE"; return ;;
		*\`*|*\$*) echo "DYNAMIC"; return ;;
		/*) abs=$p ;;
		*) abs=$POST_WORKER_WORKTREE/$p ;;
	esac
	if command -v realpath >/dev/null 2>&1; then
		realpath -m "$abs" 2>/dev/null || echo "UNRESOLVABLE"
	else
		# canonical host (Ubuntu, docs/64) always has coreutils realpath;
		# fail closed rather than normalise sloppily
		echo "UNRESOLVABLE"
	fi
}

# check_write_target blocks a write whose resolved destination is outside the
# Worker's worktree, its result dir and /tmp (plus the standard /dev sinks).
# It is shared by the shell-write policy and by the file-writing tools, so
# its wording names neither one.
check_write_target() {
	target=$1
	# Fail closed when the contract env is missing: an unset
	# $POST_WORKER_WORKTREE collapses the allow pattern below to `/*`,
	# which would admit every absolute path.
	if [ -z "${POST_WORKER_WORKTREE:-}" ] || [ -z "${POST_WORKER_RESULT_DIR:-}" ]; then
		block "worker contract environment (POST_WORKER_WORKTREE/POST_WORKER_RESULT_DIR) is missing — refusing to decide a file write"
	fi
	t=$(resolve_path "$target")
	case "$t" in
		/dev/null|/dev/stdout|/dev/stderr) return 0 ;;
		/tmp|/tmp/*) return 0 ;;
		"$POST_WORKER_WORKTREE"|"$POST_WORKER_WORKTREE"/*) return 0 ;;
		"$POST_WORKER_RESULT_DIR"|"$POST_WORKER_RESULT_DIR"/*) return 0 ;;
		*) block "write target '$target' resolves to $t, outside this Worker's worktree, its result dir and /tmp — file writes are confined by rddev" ;;
	esac
}

# skip_flag reports whether a collected argument is an option rather than a
# path operand.
skip_flag() {
	case "$1" in
		-*) return 0 ;;
	esac
	return 1
}

# git_policy applies the git subcommand allow/deny matrix. Leading global
# flags (-C <dir>, -c k=v, --no-pager, ...) are skipped first.
git_policy() {
	while [ $# -gt 0 ]; do
		case "$1" in
			-C|-c|--git-dir|--work-tree|--namespace) shift 2; continue ;;
			--no-pager|--paginate|-p|--bare|--no-replace-objects|--literal-pathspecs|--glob-pathspecs|--noglob-pathspecs|--icase-pathspecs) shift; continue ;;
			*) break ;;
		esac
	done
	sub=${1:-}
	[ -n "$sub" ] || return 0
	shift

	case "$sub" in
		commit|push|merge|rebase|tag|cherry-pick|stash|reset|config|init|clone|fetch|pull|am|revert|submodule|worktree)
			block "git $sub is a Git control-plane operation owned exclusively by the Supervisor" ;;
		checkout)
			# only the restore form `git checkout -- <paths>` is allowed;
			# switching branches or creating one moves HEAD away from the
			# recorded baseline and is a control-plane operation
			[ "${1:-}" = "--" ] || block "git checkout is a Git control-plane operation owned exclusively by the Supervisor (only 'git checkout -- <paths>' file restore is allowed)" ;;
		branch)
			# read-only listing forms are allowed; every mutating form is
			# blocked (L1-20260912-9: precise subcommand distinction)
			while [ $# -gt 0 ]; do
				case "$1" in
					-d|-D|--delete|-m|-M|--move|-c|-C|--copy|--edit-description|--set-upstream-to|--set-upstream-to=*|-u|--set-upstream|--unset-upstream|--track|--track=*)
						block "git branch $1 mutates refs — a Git control-plane operation owned exclusively by the Supervisor" ;;
					--contains|--no-contains)
						next=${2:-}
						if [ -n "$next" ]; then
							case "$next" in -*) ;; *)
								block "git branch --contains <value> feeds a ref-deletion loop — a Git control-plane operation owned exclusively by the Supervisor" ;;
							esac
						fi ;;
					--format|--sort|--points-at|--merged|--no-merged)
						# value-taking read-only long flags: the value is data,
						# not a branch name — consume it
						shift ;;
					--*) : ;;
					-*)
						case "$1" in
							-a|-r|-v|-vv|-av|-va|-rv|-vr|-l) : ;;
							*) block "git branch $1 mutates refs — a Git control-plane operation owned exclusively by the Supervisor" ;;
						esac ;;
					*)
						# a bare branch name creates a branch
						block "git branch <name> creates a ref — a Git control-plane operation owned exclusively by the Supervisor" ;;
				esac
				shift
			done ;;
		remote)
			# read-only inspection is allowed; every mutating subcommand is
			# blocked (L1-20260912-9)
			case "${1:-}" in
				""|-v|--verbose|get-url|show) return 0 ;;
				*) block "git remote ${1} mutates the remote configuration — a Git control-plane operation owned exclusively by the Supervisor" ;;
			esac ;;
		status|log|diff|show|rev-parse|ls-files|ls-tree|grep|blame|describe|shortlog|whatchanged|archive|notes|fsck|count-objects|verify-pack|reflog)
			# the read-only allow-list; reflog gains the two mutating verbs
			case "$sub" in
				reflog)
					case "$*" in
						*expire*|*delete*) block "git reflog $* mutates refs — a Git control-plane operation owned exclusively by the Supervisor" ;;
					esac ;;
			esac
			return 0 ;;
		*)
			block "git $sub is not a known read-only git subcommand — Git control-plane operations are owned exclusively by the Supervisor" ;;
	esac
}

# printenv_policy blocks probes of credential variable names. The values are
# stripped from the environment at spawn; the probe itself is refused so no
# canary-style test can ever observe one. Setting a variable via env (e.g.
# `env POST_GITEA_TOKEN=smoke-tok go test`) is legitimate and not matched.
printenv_policy() {
	for a in "$@"; do
		case "$a" in
			GH_TOKEN|GITHUB_TOKEN|GITHUB_PERSONAL_ACCESS_TOKEN|GITHUB_ENTERPRISE_TOKEN|SSH_AUTH_SOCK|GH_CONFIG_DIR|AWS_SECRET_ACCESS_KEY|AWS_ACCESS_KEY_ID|AWS_SESSION_TOKEN|DOCKER_AUTH_CONFIG|DOCKER_HOST)
				block "printenv $a probes a credential variable — credentials are stripped from Worker environments by rddev worker spawn" ;;
		esac
	done
}

# docker_policy blocks Docker socket access unless the task carries an
# explicit per-task grant; version queries never touch the socket and are
# always allowed (the T0000 preflight needs them).
docker_policy() {
	[ "${POST_WORKER_DOCKER_GRANT:-}" = "1" ] && return 0
	case "$*" in
		"docker --version"|"docker -v"|"docker compose version"|"docker-compose version") return 0 ;;
	esac
	block "Docker socket access is reserved for explicitly scoped integration tasks driven by rddev (spawn with --docker); only 'docker --version' / 'docker compose version' are allowed"
}

# write_policy applies the shell write confinement to rm/cp/mv/ln/install/tee
# arguments. rm and tee check every operand; cp/mv/install/ln check the
# destination (the last operand, plus -t/--target-directory values).
write_policy() {
	bin=$1
	shift
	case "$bin" in
		rm|tee)
			for a in "$@"; do
				skip_flag "$a" && continue
				check_write_target "$a"
			done ;;
		cp|mv|install)
			dest=""
			prev=""
			for a in "$@"; do
				case "$a" in
					--target-directory=*) check_write_target "${a#*=}"; dest=$a ;;
					-t?*) check_write_target "${a#-t}"; dest=$a ;;
				esac
				skip_flag "$a" && { prev=$a; continue; }
				case "$prev" in
					-t|--target-directory) check_write_target "$a" ;;
				esac
				dest=$a
				prev=$a
			done
			case "$dest" in
				"") : ;;
				-t|--target-directory|--target-directory=*|-t*)
					# destination was consumed as an option value above
					: ;;
				*) check_write_target "$dest" ;;
			esac ;;
		ln)
			dest=""
			for a in "$@"; do
				skip_flag "$a" && continue
				dest=$a
			done
			[ -n "$dest" ] && check_write_target "$dest" ;;
	esac
}

# redirect_policy scans the raw command text for output redirections and
# confines their targets. fd duplications (2>&1, >&2) are not paths and are
# skipped; a leading quote is stripped so `> "/etc/x"` is still caught.
# Conservative by design: a `>` inside a quoted string is treated as a
# redirection, which can only over-block, never under-block.
redirect_policy() {
	targets=$(printf '%s\n' "$1" | grep -oE '(^|[[:space:]])&?[12]?>>?[[:space:]]*[^[:space:]]+' | awk '{ print $NF }')
	for target in $targets; do
		target=${target#\"}
		target=${target#\'}
		case "$target" in
			"&1"|"&2") continue ;;
		esac
		check_write_target "$target"
	done
}

# read_policy blocks file-read confinement violations. Credential stores and
# .env files are blocked wherever they live; under $HOME nothing else is
# confined; the repo's .rddev/ runtime state is reachable only inside the
# Worker's own worktree and its own result dir.
#
# It backs two callers, so its messages name neither: the Read/Grep/Glob/
# NotebookRead branch, and the file-writing branch (Write/Edit/MultiEdit/
# NotebookEdit read the file they are about to change — the diff returns to
# the model — so they are held to the same confinement). A refusal that said
# "reading" while a Worker was trying to Write would be the half-true claim
# this file already had to fix once.
read_policy() {
	p=$1
	if [ -z "${POST_REPO_ROOT:-}" ] || [ -z "${POST_WORKER_WORKTREE:-}" ] || [ -z "${POST_WORKER_RESULT_DIR:-}" ]; then
		block "worker contract environment (POST_REPO_ROOT/POST_WORKER_WORKTREE/POST_WORKER_RESULT_DIR) is missing — refusing to decide a file read"
	fi
	case "$p" in
		*"/.config/gh"|*"/.config/gh/"*|*"/.ssh"|*"/.ssh/"*|*"/.gnupg"|*"/.gnupg/"*|*"/.docker"|*"/.docker/"*|*"/.aws"|*"/.aws/"*|*"/.git-credentials"|*"/.netrc"|*"/.claude"|*"/.claude/"*)
			block "access to credential store path '$p' is not permitted to Workers" ;;
		*".env"*)
			case "$p" in
				*".env.example") : ;;
				*) block "access to '$p' is not permitted to Workers (.env files hold secrets; .env.example is the allowed template)" ;;
			esac ;;
	esac
	t=$(resolve_path "$p")
	case "$t" in
		OUTSIDE)
			# a $HOME path: the credential stores above are the confined set
			return 0 ;;
		DYNAMIC|UNRESOLVABLE)
			block "cannot resolve read path '$p' (shell expansion) — use a static path" ;;
	esac
	case "$t" in
		"$POST_REPO_ROOT"/.rddev|"$POST_REPO_ROOT"/.rddev/*)
			case "$t" in
				"$POST_WORKER_WORKTREE"|"$POST_WORKER_WORKTREE"/*|"$POST_WORKER_RESULT_DIR"|"$POST_WORKER_RESULT_DIR"/*) return 0 ;;
				*) block "access to '$p' reaches another Worker's runtime state or the dispatch harness — confined by rddev" ;;
			esac ;;
	esac
	return 0
}

# ---------------------------------------------------------------------------
# Main: read the tool call, dispatch on tool_name.

input=$(cat)

# The tool name is DECODED, not scanned. It chooses the policy branch, so a
# value that differs from the one the harness dispatched on is a branch
# mismatch — and the old scan's verdict on a payload it could not read was
# "no tool name", i.e. allow, which is the fail-open arm. An unreadable
# payload is refused instead.
tool_name=$(printf '%s\n' "$input" | json_string tool_name); name_rc=$?
if [ "$name_rc" -ne 0 ]; then
	block "cannot parse the tool-call JSON to determine which tool is being invoked (the payload did not parse, or tool_name is not a string); refusing the call rather than choosing a policy branch from a value that could not be read."
fi
[ -n "$tool_name" ] || exit 0

case "$tool_name" in
	Bash)
		# The command text is decoded too, and this is the field T1221 is
		# about: see json_string for what a text scan did to the `\n` escape
		# of a multi-line command (it welded the second line onto the first,
		# so every command-position rule below saw one unknown word).
		command=$(printf '%s\n' "$input" | json_string tool_input.command); cmd_rc=$?
		if [ "$cmd_rc" -ne 0 ]; then
			block "cannot parse the tool-input JSON to check a shell command (the payload did not parse, or tool_input.command is not a string); refusing the call rather than allowing a command that nothing inspected."
		fi
		if [ -z "$command" ]; then
			# A parsed document with no command string in it is not a Bash
			# call this hook can inspect. The Bash tool requires `command`, so
			# the shape only appears when something is wrong with the payload;
			# allowing it would be the same "no command to inspect, therefore
			# no problem" reasoning the newline hole lived on. (A `command`
			# that is present but NOT a string never reaches here: json_string
			# refuses that shape, so this arm is absent/null/empty only.)
			block "the Bash tool call carries no command string (tool_input.command is absent, null or empty); refusing the call rather than allowing a shell call nothing inspected."
		fi

		# 0) background execution is refused. A Worker that backgrounds its
		# long-running work (a full test suite) and then ends its turn leaves
		# the session with that work still pending: the session exits, the work
		# is never done, and whatever result is on disk describes a state that
		# never completed. This happened twice on T0011 - the first time
		# producing a RESULT that falsely claimed success - so it is refused
		# mechanically rather than requested in prose.
		bg=$(printf '%s\n' "$input" | json_bool_true tool_input.run_in_background); bgrc=$?
		if [ "$bgrc" -ne 0 ]; then
			block "cannot parse the tool-input JSON to check the background-execution rule (the payload did not parse, or run_in_background is not a boolean); refusing the call rather than allowing an unverified background execution."
		fi
		if [ "$bg" = yes ]; then
			block "background execution is not permitted in a Worker: run the command in the foreground and wait for it. A Worker must finish its work inside its own session, never hand it to a background task and exit."
		fi

		# 1) redirection targets, anywhere in the command text
		redirect_policy "$command"

		# 2) command-position analysis. The records go through a temp file
		# rather than a pipeline: a `while read | cmd` loop would run in a
		# subshell and a block() there would be lost.
		records=$(command_records "$command")
		records_file=$(mktemp "${TMPDIR:-/tmp}/worker-guard.XXXXXX") || exit 0
		trap 'rm -f "$records_file"' EXIT HUP INT TERM
		printf '%s\n' "$records" > "$records_file"
		mode=""
		mode_args=""
		while IFS= read -r record; do
			kind=${record%%:*}
			word=${record#*:}
			case "$kind" in
				SEG)
					case "$mode" in
						git) git_policy $mode_args ;;
						printenv) printenv_policy $mode_args ;;
						write) write_policy $mode_args ;;
						docker) docker_policy $mode_args ;;
					esac
					mode=""
					mode_args=""
					continue ;;
				BIN)
					case "$word" in
						sudo|su|doas|pkexec) block "privilege escalation is not permitted to Workers" ;;
						gh|glab|tea|gt) block "gh/gitlab/gitea control-plane CLIs are not available to Workers" ;;
						git) mode="git"; mode_args="" ;;
						docker|docker-compose|podman) mode="docker"; mode_args="$word" ;;
						printenv) mode="printenv"; mode_args="printenv" ;;
						rm|cp|mv|ln|install|tee) mode="write"; mode_args="$word" ;;
					esac
					continue ;;
				ARG)
					case "$mode" in
						git|printenv|write|docker) mode_args="$mode_args $word" ;;
					esac
					continue ;;
			esac
		done < "$records_file"
		rm -f "$records_file"
		exit 0 ;;
	Read|Grep|Glob|NotebookRead)
		for field in file_path path notebook_path pattern; do
			p=$(printf '%s\n' "$input" | json_string "tool_input.$field"); rc=$?
			if [ "$rc" -ne 0 ]; then
				block "cannot parse the tool-input JSON to check a file read (the payload did not parse, or a path field is not a string); refusing the call rather than allowing an unverified read."
			fi
			[ -n "$p" ] && read_policy "$p"
		done
		exit 0 ;;
	Write|Edit|MultiEdit|NotebookEdit)
		# The file-writing tools. They must obey BOTH halves of the envelope
		# Bash is held to, because they can do both: a Write/Edit names a
		# destination (the write half, identical to a shell redirection), and
		# an Edit/NotebookEdit READS the file it is about to change — its diff
		# comes back to the model — so the credential-store/.env/.rddev read
		# confinement applies to it on the same terms as the Read tool.
		#
		# How these tools got here is the reason this branch exists at all:
		# they were in permissions.allow and absent from the matcher, so
		# dontAsk ran them bare and this hook was never invoked (T1219 —
		# reproduced live: a Worker wrote .rddev/runtime/tasks/<TASK>/
		# gate-inputs.json, the record collect judges allowed_scope by).
		for field in file_path notebook_path path; do
			p=$(printf '%s\n' "$input" | json_string "tool_input.$field"); rc=$?
			if [ "$rc" -ne 0 ]; then
				block "cannot parse the tool-input JSON to check a file write (the payload did not parse, or a path field is not a string); refusing the call rather than allowing an unverified write."
			fi
			[ -n "$p" ] || continue
			read_policy "$p"
			check_write_target "$p"
		done
		exit 0 ;;
esac

exit 0
