#!/bin/sh
# shellcheck disable=SC2086  # mode_args re-splitting is intentional: the token
#                            # records are plain text and splitting only over-blocks
# shellcheck disable=SC2016  # case patterns match literal $HOME, not its value
# worker-guard.sh — PreToolUse guard hook for independent Claude Code Workers.
#
# This is the canonical Worker isolation guard, generated by `rddev worker
# spawn` into .rddev/workers/<TASK>/guard/worker-guard.sh and wired into the
# Worker's Claude Code session via worker-settings.json. It is a port of the
# Supervisor's manual .rddev/dispatch harness (T0010); the ported behaviour is
# documented in tasks/decisions.md (L1-20260912-3/9/13/16) and
# specs/orchestrator/worker-permissions.yaml.
#
# What it enforces (every rule has a two-sided regression test in
# tests/worker-guard/guard-regression.sh):
#   - git control-plane subcommands are blocked in *command position* while
#     read-only git stays usable; a forbidden word in an argument (e.g.
#     `grep -n "service" docs/`) is NOT matched, and neither is `echo "git commit"`;
#   - gh/glab/tea CLIs and privilege escalation (sudo/su/doas/pkexec) are
#     blocked entirely;
#   - Docker socket access is blocked except `docker --version` /
#     `docker compose version` / `docker-compose version`, unless the task was
#     spawned with an explicit per-task Docker grant (POST_WORKER_DOCKER_GRANT=1
#     via rddev worker spawn --docker);
#   - file reads (Read/Grep/Glob/NotebookRead) cannot reach credential stores
#     (~/.config/gh, ~/.ssh, ~/.gnupg, ~/.docker, ~/.aws, ~/.git-credentials,
#     ~/.netrc, ~/.claude), any .env file except .env.example, or the repo's
#     .rddev/ runtime state outside the Worker's own worktree and result dir;
#   - shell writes (rm/cp/mv/ln/install/tee and >/>> redirections) are
#     confined to the Worker's own worktree, its own result dir and /tmp;
#     ~ / $HOME / ${HOME} are always outside, and an unresolvable $ expansion
#     fails closed;
#   - `printenv <credential-name>` probes are blocked (the variables are
#     already stripped from the environment at spawn — the probe refusal
#     exists so no probe can ever observe a value).
#
# Known limits (by design — this hook is defence in depth, not the only line):
#   - The tokenizer splits mode_args on spaces, so a quoted argument containing
#     a forbidden word in command position can over-block (safe direction).
#     `sh -c '...'` and friends are deliberately treated as opaque (the shell
#     inside would escape the analysis) and are confined by the deny layer +
#     collect-time invariants instead.
#   - Redirections on a quoted path are conservatively over-blocked when the
#     quote state cannot be resolved; unresolvable $ expansions fail closed.
#
# Hook protocol: the tool call JSON arrives on stdin. On a violation the guard
# prints {"decision":"block","reason":...} on stdout, the human-readable
# reason on stderr, and exits 2 (Claude Code reports the block). Otherwise it
# exits 0 silently (allow). An unparseable or unknown tool call is allowed:
# the permission layer and the collect-time invariants remain as the second
# and third lines of defence, and this hook must never become the one that
# breaks the Worker contract with false positives.
#
# Environment (all set by rddev worker spawn):
#   POST_REPO_ROOT         absolute repo root (main checkout)
#   POST_WORKER_TASK_ID    task id (T0010)
#   POST_WORKER_WORKTREE   absolute path of this Worker's worktree
#   POST_WORKER_RESULT_DIR absolute path of this Worker's result dir
#   POST_WORKER_DOCKER_GRANT "1" iff the task carries an explicit Docker grant

set -f # never pathname-expand analysed command words or targets

# block prints the JSON decision and the reason, then exits 2 (deny).
block() {
	reason=$1
	escaped=$(printf '%s' "$reason" | sed 's/\\/\\\\/g; s/"/\\"/g')
	printf '{"decision":"block","reason":"%s"}\n' "$escaped"
	printf 'blocked: %s\n' "$reason" >&2
	exit 2
}

# json_field extracts the value of a string field from the tool-call JSON on
# stdin (top-level or nested), unescaping \" and \\ so quoted command text
# (`echo "hi"`) survives extraction. These fields carry commands and paths,
# not nested objects, so a string walk is the right tool.
json_field() {
	field=$1
	awk -v f="$field" '
	{
		line = $0
		key = "\"" f "\""
		pos = index(line, key)
		if (pos == 0) next
		rest = substr(line, pos + length(key))
		sub(/^[^:]*:[[:space:]]*/, "", rest)
		if (substr(rest, 1, 1) != "\"") next
		out = ""
		esc = 0
		for (i = 2; i <= length(rest); i++) {
			c = substr(rest, i, 1)
			if (esc) { out = out c; esc = 0; continue }
			if (c == "\\") { esc = 1; continue }
			if (c == "\"") break
			out = out c
		}
		print out
	}'
}

# json_bool_true KEYPATH prints "yes" when the boolean at that dotted path is
# true, and prints "no" when it is absent or false. Exit 0 when the payload
# parsed; non-zero when it did not.
#
# This parses the tool input with a real JSON decoder instead of scanning the
# raw text. Scanning is wrong in principle: the same document also carries the
# model-controlled `command` string, and duplicate/escaped keys resolve
# differently in a text scan than in the JSON the consumer actually reads.
# (A security review raised this as a fail-open. Testing showed the obvious
# injection - putting the key inside the command text - does NOT work, because
# a quote inside a JSON string is escaped, so the raw key never appears
# contiguously. It is still the wrong shape for a security check, and a
# future serialisation change could make it exploitable, so it is parsed.)
json_bool_true() {
	python3 -c '
import json, sys
try:
    doc = json.load(sys.stdin)
except Exception:
    sys.exit(3)
cur = doc
for part in sys.argv[1].split("."):
    if not isinstance(cur, dict) or part not in cur:
        print("no"); sys.exit(0)
    cur = cur[part]
print("yes" if cur is True else "no")
' "$1"
}

# command_records emits the parsed Bash command as one record per line:
#   BIN:<word>  the first non-assignment word of a command segment — the
#               binary in *command position* (after ; | && || &, or the start)
#   ARG:<word>  every other word of the segment, in order
#   SEG         end of one segment
# Quoted strings are kept intact: `grep -n "service" docs/` yields no
# forbidden word and `echo "git commit"` is not mistaken for git. `env` is
# followed: its first non-flag, non-assignment argument runs as a command and
# is emitted as BIN too (`env FOO=x git push` must not escape the git check).
command_records() {
	printf '%s\n' "$1" | awk '
	function flush(		w) {
		w = word
		word = ""
		if (w == "") return
		if (skip_env_val) { skip_env_val = 0; print "ARG:" w; return }
		if (env_follow) {
			if (w ~ /^[A-Za-z_][A-Za-z0-9_]*=/) { print "ARG:" w; return }
			if (w ~ /^-/) {
				print "ARG:" w
				# env option flags take a value; consume it so it is not
				# mistaken for the command env runs
				if (w ~ /^-u$|^-i$|^-C$|^--unset$|^--chdir$|^-S$|^--split-string$|^-v$|^--debug$/)
					skip_env_val = 1
				return
			}
			print "BIN:" w
			env_follow = 0
			return
		}
		if (pending) {
			# a VAR=value assignment is not the command; keep looking
			if (w ~ /^[A-Za-z_][A-Za-z0-9_]*=/) return
			print "BIN:" w
			pending = 0
			if (w == "env") env_follow = 1
			return
		}
		print "ARG:" w
	}
	{
		line = $0
		n = length(line)
		pending = 1
		env_follow = 0
		skip_env_val = 0
		word = ""
		quote = ""
		for (i = 1; i <= n; i++) {
			c = substr(line, i, 1)
			if (quote != "") {
				if (c == quote) quote = ""
				else word = word c
				continue
			}
			if (c == "\\") {
				if (i < n) { word = word substr(line, i + 1, 1); i++ }
				continue
			}
			if (c == "\x27" || c == "\"") { quote = c; continue }
			if (c == ";" || c == "|" || c == "&") {
				flush()
				if (c != ";" && substr(line, i + 1, 1) == c) i++ # && or ||
				print "SEG"
				# a new segment starts at command position again
				pending = 1
				env_follow = 0
				skip_env_val = 0
				continue
			}
			if (c == " " || c == "\t") { flush(); continue }
			word = word c
		}
		flush()
		print "SEG"
	}'
}

# resolve_path prints the absolute form of a path the Worker named, or one of
# the markers OUTSIDE / DYNAMIC / UNRESOLVABLE which callers treat as failing
# closed. Relative paths resolve against the Worker's worktree (its shell
# cwd). ~ / $HOME / ${HOME} are always outside the allowed set.
resolve_path() {
	p=$1
	case "$p" in
		~*|*'$HOME'*|*'${HOME}'*) echo "OUTSIDE"; return ;;
		*\`*|*\$*) echo "DYNAMIC"; return ;;
		/*) abs=$p ;;
		*) abs=$POST_WORKER_WORKTREE/$p ;;
	esac
	if command -v realpath >/dev/null 2>&1; then
		realpath -m "$abs" 2>/dev/null || echo "UNRESOLVABLE"
	else
		# canonical host (Ubuntu, docs/64) always has coreutils realpath;
		# fail closed rather than normalise sloppily
		echo "UNRESOLVABLE"
	fi
}

# check_write_target blocks a shell write whose resolved destination is
# outside the Worker's worktree, its result dir and /tmp (plus the standard
# /dev sinks).
check_write_target() {
	target=$1
	# Fail closed when the contract env is missing: an unset
	# $POST_WORKER_WORKTREE collapses the allow pattern below to `/*`,
	# which would admit every absolute path.
	if [ -z "${POST_WORKER_WORKTREE:-}" ] || [ -z "${POST_WORKER_RESULT_DIR:-}" ]; then
		block "worker contract environment (POST_WORKER_WORKTREE/POST_WORKER_RESULT_DIR) is missing — refusing to decide a shell write"
	fi
	t=$(resolve_path "$target")
	case "$t" in
		/dev/null|/dev/stdout|/dev/stderr) return 0 ;;
		/tmp|/tmp/*) return 0 ;;
		"$POST_WORKER_WORKTREE"|"$POST_WORKER_WORKTREE"/*) return 0 ;;
		"$POST_WORKER_RESULT_DIR"|"$POST_WORKER_RESULT_DIR"/*) return 0 ;;
		*) block "write target '$target' resolves to $t, outside this Worker's worktree, its result dir and /tmp — shell writes are confined by rddev" ;;
	esac
}

# skip_flag reports whether a collected argument is an option rather than a
# path operand.
skip_flag() {
	case "$1" in
		-*) return 0 ;;
	esac
	return 1
}

# git_policy applies the git subcommand allow/deny matrix. Leading global
# flags (-C <dir>, -c k=v, --no-pager, ...) are skipped first.
git_policy() {
	while [ $# -gt 0 ]; do
		case "$1" in
			-C|-c|--git-dir|--work-tree|--namespace) shift 2; continue ;;
			--no-pager|--paginate|-p|--bare|--no-replace-objects|--literal-pathspecs|--glob-pathspecs|--noglob-pathspecs|--icase-pathspecs) shift; continue ;;
			*) break ;;
		esac
	done
	sub=${1:-}
	[ -n "$sub" ] || return 0
	shift

	case "$sub" in
		commit|push|merge|rebase|tag|cherry-pick|stash|reset|config|init|clone|fetch|pull|am|revert|submodule|worktree)
			block "git $sub is a Git control-plane operation owned exclusively by the Supervisor" ;;
		checkout)
			# only the restore form `git checkout -- <paths>` is allowed;
			# switching branches or creating one moves HEAD away from the
			# recorded baseline and is a control-plane operation
			[ "${1:-}" = "--" ] || block "git checkout is a Git control-plane operation owned exclusively by the Supervisor (only 'git checkout -- <paths>' file restore is allowed)" ;;
		branch)
			# read-only listing forms are allowed; every mutating form is
			# blocked (L1-20260912-9: precise subcommand distinction)
			while [ $# -gt 0 ]; do
				case "$1" in
					-d|-D|--delete|-m|-M|--move|-c|-C|--copy|--edit-description|--set-upstream-to|--set-upstream-to=*|-u|--set-upstream|--unset-upstream|--track|--track=*)
						block "git branch $1 mutates refs — a Git control-plane operation owned exclusively by the Supervisor" ;;
					--contains|--no-contains)
						next=${2:-}
						if [ -n "$next" ]; then
							case "$next" in -*) ;; *)
								block "git branch --contains <value> feeds a ref-deletion loop — a Git control-plane operation owned exclusively by the Supervisor" ;;
							esac
						fi ;;
					--format|--sort|--points-at|--merged|--no-merged)
						# value-taking read-only long flags: the value is data,
						# not a branch name — consume it
						shift ;;
					--*) : ;;
					-*)
						case "$1" in
							-a|-r|-v|-vv|-av|-va|-rv|-vr|-l) : ;;
							*) block "git branch $1 mutates refs — a Git control-plane operation owned exclusively by the Supervisor" ;;
						esac ;;
					*)
						# a bare branch name creates a branch
						block "git branch <name> creates a ref — a Git control-plane operation owned exclusively by the Supervisor" ;;
				esac
				shift
			done ;;
		remote)
			# read-only inspection is allowed; every mutating subcommand is
			# blocked (L1-20260912-9)
			case "${1:-}" in
				""|-v|--verbose|get-url|show) return 0 ;;
				*) block "git remote ${1} mutates the remote configuration — a Git control-plane operation owned exclusively by the Supervisor" ;;
			esac ;;
		status|log|diff|show|rev-parse|ls-files|ls-tree|grep|blame|describe|shortlog|whatchanged|archive|notes|fsck|count-objects|verify-pack|reflog)
			# the read-only allow-list; reflog gains the two mutating verbs
			case "$sub" in
				reflog)
					case "$*" in
						*expire*|*delete*) block "git reflog $* mutates refs — a Git control-plane operation owned exclusively by the Supervisor" ;;
					esac ;;
			esac
			return 0 ;;
		*)
			block "git $sub is not a known read-only git subcommand — Git control-plane operations are owned exclusively by the Supervisor" ;;
	esac
}

# printenv_policy blocks probes of credential variable names. The values are
# stripped from the environment at spawn; the probe itself is refused so no
# canary-style test can ever observe one. Setting a variable via env (e.g.
# `env POST_GITEA_TOKEN=smoke-tok go test`) is legitimate and not matched.
printenv_policy() {
	for a in "$@"; do
		case "$a" in
			GH_TOKEN|GITHUB_TOKEN|GITHUB_PERSONAL_ACCESS_TOKEN|GITHUB_ENTERPRISE_TOKEN|SSH_AUTH_SOCK|GH_CONFIG_DIR|AWS_SECRET_ACCESS_KEY|AWS_ACCESS_KEY_ID|AWS_SESSION_TOKEN|DOCKER_AUTH_CONFIG|DOCKER_HOST)
				block "printenv $a probes a credential variable — credentials are stripped from Worker environments by rddev worker spawn" ;;
		esac
	done
}

# docker_policy blocks Docker socket access unless the task carries an
# explicit per-task grant; version queries never touch the socket and are
# always allowed (the T0000 preflight needs them).
docker_policy() {
	[ "${POST_WORKER_DOCKER_GRANT:-}" = "1" ] && return 0
	case "$*" in
		"docker --version"|"docker -v"|"docker compose version"|"docker-compose version") return 0 ;;
	esac
	block "Docker socket access is reserved for explicitly scoped integration tasks driven by rddev (spawn with --docker); only 'docker --version' / 'docker compose version' are allowed"
}

# write_policy applies the shell write confinement to rm/cp/mv/ln/install/tee
# arguments. rm and tee check every operand; cp/mv/install/ln check the
# destination (the last operand, plus -t/--target-directory values).
write_policy() {
	bin=$1
	shift
	case "$bin" in
		rm|tee)
			for a in "$@"; do
				skip_flag "$a" && continue
				check_write_target "$a"
			done ;;
		cp|mv|install)
			dest=""
			prev=""
			for a in "$@"; do
				case "$a" in
					--target-directory=*) check_write_target "${a#*=}"; dest=$a ;;
					-t?*) check_write_target "${a#-t}"; dest=$a ;;
				esac
				skip_flag "$a" && { prev=$a; continue; }
				case "$prev" in
					-t|--target-directory) check_write_target "$a" ;;
				esac
				dest=$a
				prev=$a
			done
			case "$dest" in
				"") : ;;
				-t|--target-directory|--target-directory=*|-t*)
					# destination was consumed as an option value above
					: ;;
				*) check_write_target "$dest" ;;
			esac ;;
		ln)
			dest=""
			for a in "$@"; do
				skip_flag "$a" && continue
				dest=$a
			done
			[ -n "$dest" ] && check_write_target "$dest" ;;
	esac
}

# redirect_policy scans the raw command text for output redirections and
# confines their targets. fd duplications (2>&1, >&2) are not paths and are
# skipped; a leading quote is stripped so `> "/etc/x"` is still caught.
# Conservative by design: a `>` inside a quoted string is treated as a
# redirection, which can only over-block, never under-block.
redirect_policy() {
	targets=$(printf '%s\n' "$1" | grep -oE '(^|[[:space:]])&?[12]?>>?[[:space:]]*[^[:space:]]+' | awk '{ print $NF }')
	for target in $targets; do
		target=${target#\"}
		target=${target#\'}
		case "$target" in
			"&1"|"&2") continue ;;
		esac
		check_write_target "$target"
	done
}

# read_policy blocks file-read confinement violations (Read/Grep/Glob/
# NotebookRead tool calls). Credential stores and .env files are blocked
# wherever they live; under $HOME nothing else is confined; the repo's
# .rddev/ runtime state is readable only inside the Worker's own worktree and
# its own result dir.
read_policy() {
	p=$1
	if [ -z "${POST_REPO_ROOT:-}" ] || [ -z "${POST_WORKER_WORKTREE:-}" ] || [ -z "${POST_WORKER_RESULT_DIR:-}" ]; then
		block "worker contract environment (POST_REPO_ROOT/POST_WORKER_WORKTREE/POST_WORKER_RESULT_DIR) is missing — refusing to decide a file read"
	fi
	case "$p" in
		*"/.config/gh"|*"/.config/gh/"*|*"/.ssh"|*"/.ssh/"*|*"/.gnupg"|*"/.gnupg/"*|*"/.docker"|*"/.docker/"*|*"/.aws"|*"/.aws/"*|*"/.git-credentials"|*"/.netrc"|*"/.claude"|*"/.claude/"*)
			block "reading credential store path '$p' is not permitted to Workers" ;;
		*".env"*)
			case "$p" in
				*".env.example") : ;;
				*) block "reading '$p' is not permitted to Workers (.env files hold secrets; .env.example is the allowed template)" ;;
			esac ;;
	esac
	t=$(resolve_path "$p")
	case "$t" in
		OUTSIDE)
			# a $HOME path: the credential stores above are the confined set
			return 0 ;;
		DYNAMIC|UNRESOLVABLE)
			block "cannot resolve read path '$p' (shell expansion) — use a static path" ;;
	esac
	case "$t" in
		"$POST_REPO_ROOT"/.rddev|"$POST_REPO_ROOT"/.rddev/*)
			case "$t" in
				"$POST_WORKER_WORKTREE"|"$POST_WORKER_WORKTREE"/*|"$POST_WORKER_RESULT_DIR"|"$POST_WORKER_RESULT_DIR"/*) return 0 ;;
				*) block "reading '$p' reaches another Worker's runtime state or the dispatch harness — confined by rddev" ;;
			esac ;;
	esac
	return 0
}

# ---------------------------------------------------------------------------
# Main: read the tool call, dispatch on tool_name.

input=$(cat)

tool_name=$(printf '%s\n' "$input" | json_field tool_name)
[ -n "$tool_name" ] || exit 0

case "$tool_name" in
	Bash)
		command=$(printf '%s\n' "$input" | json_field command)
		[ -n "$command" ] || exit 0

		# 0) background execution is refused. A Worker that backgrounds its
		# long-running work (a full test suite) and then ends its turn leaves
		# the session with that work still pending: the session exits, the work
		# is never done, and whatever result is on disk describes a state that
		# never completed. This happened twice on T0011 - the first time
		# producing a RESULT that falsely claimed success - so it is refused
		# mechanically rather than requested in prose.
		bg=$(printf '%s\n' "$input" | json_bool_true tool_input.run_in_background); bgrc=$?
		if [ "$bgrc" -ne 0 ]; then
			block "cannot parse the tool-input JSON to check the background-execution rule; refusing the call rather than allowing an unverified background execution."
		fi
		if [ "$bg" = yes ]; then
			block "background execution is not permitted in a Worker: run the command in the foreground and wait for it. A Worker must finish its work inside its own session, never hand it to a background task and exit."
		fi

		# 1) redirection targets, anywhere in the command text
		redirect_policy "$command"

		# 2) command-position analysis. The records go through a temp file
		# rather than a pipeline: a `while read | cmd` loop would run in a
		# subshell and a block() there would be lost.
		records=$(command_records "$command")
		records_file=$(mktemp "${TMPDIR:-/tmp}/worker-guard.XXXXXX") || exit 0
		trap 'rm -f "$records_file"' EXIT HUP INT TERM
		printf '%s\n' "$records" > "$records_file"
		mode=""
		mode_args=""
		while IFS= read -r record; do
			kind=${record%%:*}
			word=${record#*:}
			case "$kind" in
				SEG)
					case "$mode" in
						git) git_policy $mode_args ;;
						printenv) printenv_policy $mode_args ;;
						write) write_policy $mode_args ;;
						docker) docker_policy $mode_args ;;
					esac
					mode=""
					mode_args=""
					continue ;;
				BIN)
					case "$word" in
						sudo|su|doas|pkexec) block "privilege escalation is not permitted to Workers" ;;
						gh|glab|tea|gt) block "gh/gitlab/gitea control-plane CLIs are not available to Workers" ;;
						git) mode="git"; mode_args="" ;;
						docker|docker-compose|podman) mode="docker"; mode_args="$word" ;;
						printenv) mode="printenv"; mode_args="printenv" ;;
						rm|cp|mv|ln|install|tee) mode="write"; mode_args="$word" ;;
					esac
					continue ;;
				ARG)
					case "$mode" in
						git|printenv|write|docker) mode_args="$mode_args $word" ;;
					esac
					continue ;;
			esac
		done < "$records_file"
		rm -f "$records_file"
		exit 0 ;;
	Read|Grep|Glob|NotebookRead)
		for field in file_path path notebook_path pattern; do
			p=$(printf '%s\n' "$input" | json_field "$field")
			[ -n "$p" ] && read_policy "$p"
		done
		exit 0 ;;
esac

exit 0
