-- POST canonical database schema — GENERATED, DO NOT EDIT.
--
-- Generated by scripts/gen_schema_snapshot.py from the ordered Up sections of
-- infra/migrations/. The migrations are the canonical history; this file is
-- their snapshot, and `make check-schema-snapshot` fails when the two diverge.
--
-- To change the schema: add a migration, then run
--   python3 scripts/gen_schema_snapshot.py
-- (A Worker's task package states the migration number reserved for it; never
-- choose one from this file's own index — that is how two branches once both
-- created 00017.)
--
-- Sources, in application order:
--   00001_extensions.sql
--   00002_identity.sql
--   00003_projects.sql
--   00004_rsg_state.sql
--   00005_scientific_objects.sql
--   00006_relations.sql
--   00007_evidence.sql
--   00008_blobs.sql
--   00009_issues_pull_requests.sql
--   00010_releases_assets.sql
--   00011_external_contribution.sql
--   00012_events_audit.sql
--   00013_search_projection.sql
--   00014_append_only_enforcement.sql
--   00015_append_only_truncate.sql
--   00016_auth_password.sql
--   00017_profiles.sql
--   00018_organization_governance.sql
--   00019_project_provisioning.sql
--   00020_audit_scopes.sql
--   00024_scientific_object_version_counter.sql


-- ===== 00001_extensions.sql =====

-- Extensions required by the canonical schema (specs/database/postgres.sql).
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ===== 00002_identity.sql =====

-- Identity: users, organizations, memberships (canonical lines 7-32).
CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  handle text UNIQUE NOT NULL,
  email text UNIQUE,
  display_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  disabled_at timestamptz
);

CREATE TABLE organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE organization_memberships (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role text NOT NULL CHECK (role IN ('owner','maintainer','contributor','viewer')),
  affiliation_start date,
  affiliation_end date,
  verified boolean NOT NULL DEFAULT false,
  PRIMARY KEY (organization_id,user_id)
);


-- ===== 00003_projects.sql =====

-- Projects, programs, memberships, policy versions (canonical lines 34-77).
CREATE TABLE programs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, slug)
);

CREATE TABLE projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  program_id uuid REFERENCES programs(id) ON DELETE SET NULL,
  slug text NOT NULL,
  name text NOT NULL,
  purpose text NOT NULL,
  activity_status text NOT NULL DEFAULT 'planning' CHECK (activity_status IN ('planning','active','paused','archived')),
  visibility text NOT NULL CHECK (visibility IN ('public','private')),
  main_frozen boolean NOT NULL DEFAULT false,
  git_repository_external_id text,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id,slug)
);

CREATE TABLE project_memberships (
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role text NOT NULL CHECK (role IN ('owner','maintainer','contributor','viewer')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(project_id,user_id)
);

CREATE TABLE policy_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  version text NOT NULL,
  policy_json jsonb NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((organization_id IS NOT NULL) <> (project_id IS NOT NULL))
);


-- ===== 00004_rsg_state.sql =====

-- RSG state model: branches, project states, state commits
-- (canonical lines 79-117).
--
-- NOTE: creation order differs from the canonical seed file: `branches` is
-- created before `project_states` because project_states references
-- branches(id) inline and PostgreSQL cannot create a table that references a
-- not-yet-existing relation. All constraints are preserved verbatim; only the
-- statement order was made executable. branches.base_state_id is still added
-- as a separate FK constraint via ALTER TABLE, exactly as in the canonical
-- seed (lines 104).
CREATE TABLE branches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  name text NOT NULL,
  visibility text NOT NULL CHECK (visibility IN ('public','private')),
  purpose text,
  git_ref text NOT NULL,
  base_state_id uuid,
  lifecycle_state text NOT NULL DEFAULT 'active' CHECK (lifecycle_state IN ('active','merged','aborted')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,name)
);

CREATE TABLE project_states (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  branch_id uuid REFERENCES branches(id) ON DELETE RESTRICT,
  parent_state_id uuid REFERENCES project_states(id) ON DELETE RESTRICT,
  state_hash text NOT NULL,
  git_commit_sha text,
  manifest_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,state_hash)
);
ALTER TABLE branches ADD CONSTRAINT branches_base_state_fk FOREIGN KEY(base_state_id) REFERENCES project_states(id) ON DELETE RESTRICT;

CREATE TABLE state_commits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  base_state_id uuid REFERENCES project_states(id) ON DELETE RESTRICT,
  result_state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  actor_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  via text NOT NULL CHECK (via IN ('web','api','mcp','claude_code','git_compat','system')),
  message text NOT NULL,
  operation_summary jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00005_scientific_objects.sql =====

-- Scientific objects and their append-only versions (canonical lines 119-144).
CREATE TABLE scientific_objects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  object_type text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE scientific_object_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  object_id uuid NOT NULL REFERENCES scientific_objects(id) ON DELETE RESTRICT,
  version_no integer NOT NULL CHECK(version_no > 0),
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  branch_id uuid REFERENCES branches(id) ON DELETE RESTRICT,
  schema_id text NOT NULL,
  schema_version text NOT NULL,
  title text NOT NULL,
  lifecycle_state text NOT NULL CHECK (lifecycle_state IN ('active','aborted','reopened','superseded')),
  payload jsonb NOT NULL,
  visibility_policy_id uuid,
  integrity_hash text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(object_id,version_no)
);
CREATE INDEX scientific_object_versions_payload_gin ON scientific_object_versions USING gin(payload);


-- ===== 00006_relations.sql =====

-- Relations and their versions (canonical lines 146-166).
CREATE TABLE relations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE relation_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  relation_id uuid NOT NULL REFERENCES relations(id) ON DELETE RESTRICT,
  version_no integer NOT NULL CHECK(version_no > 0),
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  relation_type text NOT NULL,
  source_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  target_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  integrity_hash text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(relation_id,version_no)
);
CREATE INDEX relation_versions_source_idx ON relation_versions(source_object_version_id, relation_type);
CREATE INDEX relation_versions_target_idx ON relation_versions(target_object_version_id, relation_type);


-- ===== 00007_evidence.sql =====

-- Evidence assertions (canonical lines 168-183).
CREATE TABLE evidence_assertions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  target_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  evidence_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  relation_type text NOT NULL CHECK (relation_type IN ('supports','contradicts','consistent_with','inconsistent_with','reproduces','fails_to_reproduce','validates','challenges','contextualizes')),
  evidence_type text NOT NULL,
  scope jsonb NOT NULL DEFAULT '{}'::jsonb,
  directness text NOT NULL DEFAULT 'unknown',
  inference_nature text NOT NULL DEFAULT 'unknown',
  reasoning_note text,
  review_state text NOT NULL DEFAULT 'unreviewed' CHECK(review_state IN ('unreviewed','reviewed','rejected')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00008_blobs.sql =====

-- Blobs and their attachments to scientific object versions
-- (canonical lines 185-202).
CREATE TABLE blobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content_hash text NOT NULL,
  size_bytes bigint NOT NULL CHECK(size_bytes >= 0),
  media_type text,
  storage_key text NOT NULL,
  integrity_state text NOT NULL DEFAULT 'pending' CHECK(integrity_state IN ('pending','verified','failed')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(content_hash,size_bytes)
);
CREATE TABLE blob_attachments (
  blob_id uuid NOT NULL REFERENCES blobs(id) ON DELETE RESTRICT,
  scientific_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  attachment_role text NOT NULL,
  access_level text NOT NULL CHECK(access_level IN ('open','restricted')),
  PRIMARY KEY(blob_id, scientific_object_version_id, attachment_role)
);


-- ===== 00009_issues_pull_requests.sql =====

-- Issues, pull requests, reviews (canonical lines 204-242).
CREATE TABLE issues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  number bigint NOT NULL,
  issue_type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT 'open' CHECK(state IN ('open','in_progress','closed','aborted')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,number)
);

CREATE TABLE pull_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  number bigint NOT NULL,
  source_branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  target_branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  base_state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  proposed_state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT 'open',
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  merged_at timestamptz,
  UNIQUE(project_id,number)
);

CREATE TABLE reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pull_request_id uuid NOT NULL REFERENCES pull_requests(id) ON DELETE RESTRICT,
  reviewer_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  review_kind text NOT NULL CHECK(review_kind IN ('scientific','integrity','rights','ip')),
  decision text NOT NULL CHECK(decision IN ('approved','changes_requested','commented')),
  body text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00010_releases_assets.sql =====

-- Validation results, releases, research assets, publications
-- (canonical lines 244-312).
CREATE TABLE validation_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  gate text NOT NULL CHECK(gate IN ('pr','main','release','asset')),
  status text NOT NULL CHECK(status IN ('passed','failed','warning')),
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE releases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  version text NOT NULL,
  title text NOT NULL,
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  policy_version_id uuid REFERENCES policy_versions(id) ON DELETE RESTRICT,
  manifest jsonb NOT NULL,
  manifest_hash text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,version)
);

CREATE TABLE research_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_type text NOT NULL CHECK(asset_type IN ('dataset','protocol','material_collection','benchmark')),
  slug text NOT NULL,
  title text NOT NULL,
  origin_project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE research_asset_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL REFERENCES research_assets(id) ON DELETE RESTRICT,
  version text NOT NULL,
  source_release_id uuid REFERENCES releases(id) ON DELETE RESTRICT,
  manifest jsonb NOT NULL,
  rights_json jsonb NOT NULL,
  visibility text NOT NULL CHECK(visibility IN ('public','private')),
  integrity_hash text NOT NULL,
  published_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  published_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(asset_id,version)
);
CREATE TABLE asset_lineage (
  parent_asset_version_id uuid NOT NULL REFERENCES research_asset_versions(id) ON DELETE RESTRICT,
  child_asset_version_id uuid NOT NULL REFERENCES research_asset_versions(id) ON DELETE RESTRICT,
  relation_type text NOT NULL CHECK(relation_type IN ('forked_from','derived_from','supersedes')),
  PRIMARY KEY(parent_asset_version_id,child_asset_version_id,relation_type)
);
CREATE TABLE asset_dependencies (
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  asset_version_id uuid NOT NULL REFERENCES research_asset_versions(id) ON DELETE RESTRICT,
  dependency_type text NOT NULL,
  visibility_of_usage text NOT NULL DEFAULT 'private' CHECK(visibility_of_usage IN ('public','private')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(project_id,asset_version_id,dependency_type)
);

CREATE TABLE knowledge_publications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  public_version text NOT NULL,
  rights_json jsonb NOT NULL,
  published_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  published_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(object_version_id,public_version)
);


-- ===== 00011_external_contribution.sql =====

-- External references, contribution ledger events, credit disputes
-- (canonical lines 314-354).
CREATE TABLE external_references (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_type text NOT NULL,
  external_identifier text NOT NULL,
  canonical_url text,
  UNIQUE(source_type,external_identifier)
);
CREATE TABLE external_reference_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_reference_id uuid NOT NULL REFERENCES external_references(id) ON DELETE RESTRICT,
  accessed_at timestamptz NOT NULL,
  upstream_version text,
  metadata jsonb NOT NULL,
  snapshot_hash text NOT NULL,
  blob_id uuid REFERENCES blobs(id) ON DELETE RESTRICT
);

CREATE TABLE contribution_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  organization_id_at_time uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  event_type text NOT NULL,
  role_codes text[] NOT NULL DEFAULT '{}',
  object_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
  accepted_context boolean NOT NULL DEFAULT false,
  released_context boolean NOT NULL DEFAULT false,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE credit_disputes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  opened_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_ref text NOT NULL,
  claim text NOT NULL,
  state text NOT NULL DEFAULT 'open' CHECK(state IN ('open','resolved','rejected')),
  resolution text,
  opened_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);


-- ===== 00012_events_audit.sql =====

-- Domain events, transactional outbox, subscriptions, webhook deliveries,
-- audit log (canonical lines 356-408).
CREATE TABLE research_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  actor_id uuid REFERENCES users(id) ON DELETE RESTRICT,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  visibility text NOT NULL,
  payload jsonb NOT NULL,
  correlation_id text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE outbox_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  correlation_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  attempts integer NOT NULL DEFAULT 0
);

CREATE TABLE subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_type text NOT NULL,
  target_id text NOT NULL,
  event_filters text[] NOT NULL DEFAULT '{}',
  channels text[] NOT NULL DEFAULT '{web}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES research_events(id) ON DELETE RESTRICT,
  endpoint text NOT NULL,
  status text NOT NULL,
  response_code integer,
  attempts integer NOT NULL DEFAULT 0,
  last_attempt_at timestamptz
);

CREATE TABLE audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid REFERENCES users(id) ON DELETE RESTRICT,
  via text NOT NULL,
  action text NOT NULL,
  target_ref text,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  correlation_id text NOT NULL,
  before_summary jsonb,
  after_summary jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00013_search_projection.sql =====

-- Search projection (rebuildable; canonical lines 410-423).
CREATE TABLE search_documents (
  entity_ref text PRIMARY KEY,
  entity_type text NOT NULL,
  visibility text NOT NULL,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  title text NOT NULL,
  content text NOT NULL,
  structured jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedding vector(1536),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX search_documents_fts_idx ON search_documents USING gin(to_tsvector('simple', title || ' ' || content));
CREATE INDEX search_documents_structured_gin ON search_documents USING gin(structured);


-- ===== 00014_append_only_enforcement.sql =====

-- Append-only enforcement (task T0013): the version/history/ledger tables are
-- immutable. An in-place UPDATE or DELETE of an existing row is rejected by
-- the database itself (BEFORE UPDATE OR DELETE row triggers that RAISE
-- EXCEPTION), so no client — application code, psql, a leaked credential — can
-- rewrite or erase history (CLAUDE.md §9, ADR-007, ADR-008, ADR-021,
-- docs/21 §4, docs/46, Master Acceptance Gate A).
--
-- Corrections never mutate a row: they append a new one (abort/reopen,
-- supersede, new version, new state). One shared guard function reports the
-- table name and the forbidden operation (TG_TABLE_NAME / TG_OP) so an
-- operator can act on the error.
--
-- Covered tables (append-only by design; see task result for the full
-- decision and the deliberately exempt tables):
--   scientific_object_versions, relation_versions        version logs
--   project_states, state_commits                        RSG state history
--   releases, research_asset_versions, asset_lineage     release/asset history
--   policy_versions                                      policy versions
--   validation_results                                   gate run records
--   contribution_events, audit_log                       append-only ledgers
--   research_events                                      domain event log
--   external_reference_snapshots                         pinned snapshots
--
-- No existing constraint is changed or dropped; no column semantics are added.

-- +goose StatementBegin
CREATE FUNCTION append_only_guard() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'table % is append-only: % is forbidden (history is immutable; insert a new row instead)',
    TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'P0001';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER scientific_object_versions_append_only
  BEFORE UPDATE OR DELETE ON scientific_object_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER relation_versions_append_only
  BEFORE UPDATE OR DELETE ON relation_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER project_states_append_only
  BEFORE UPDATE OR DELETE ON project_states
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER state_commits_append_only
  BEFORE UPDATE OR DELETE ON state_commits
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER releases_append_only
  BEFORE UPDATE OR DELETE ON releases
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_asset_versions_append_only
  BEFORE UPDATE OR DELETE ON research_asset_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER asset_lineage_append_only
  BEFORE UPDATE OR DELETE ON asset_lineage
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER policy_versions_append_only
  BEFORE UPDATE OR DELETE ON policy_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER validation_results_append_only
  BEFORE UPDATE OR DELETE ON validation_results
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER contribution_events_append_only
  BEFORE UPDATE OR DELETE ON contribution_events
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER audit_log_append_only
  BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_events_append_only
  BEFORE UPDATE OR DELETE ON research_events
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER external_reference_snapshots_append_only
  BEFORE UPDATE OR DELETE ON external_reference_snapshots
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();


-- ===== 00015_append_only_truncate.sql =====

-- Append-only enforcement, part 2 (follow-up to T0013).
--
-- Row-level triggers do NOT fire on TRUNCATE, so the immutability added in
-- 00014 could still be bypassed wholesale with `TRUNCATE <table> CASCADE`,
-- erasing an entire history in one statement. A statement-level BEFORE
-- TRUNCATE trigger closes that hole, reusing the same append_only_guard()
-- function (which reads TG_TABLE_NAME / TG_OP, set for statement-level
-- triggers exactly as for row-level ones).
--
-- Covers the same 13 tables as 00014. If that set changes, both migrations
-- must be extended with a new forward-only migration - never edited in place.

CREATE TRIGGER asset_lineage_no_truncate
  BEFORE TRUNCATE ON asset_lineage FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER audit_log_no_truncate
  BEFORE TRUNCATE ON audit_log FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER contribution_events_no_truncate
  BEFORE TRUNCATE ON contribution_events FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER external_reference_snapshots_no_truncate
  BEFORE TRUNCATE ON external_reference_snapshots FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER policy_versions_no_truncate
  BEFORE TRUNCATE ON policy_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER project_states_no_truncate
  BEFORE TRUNCATE ON project_states FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER relation_versions_no_truncate
  BEFORE TRUNCATE ON relation_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER releases_no_truncate
  BEFORE TRUNCATE ON releases FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_asset_versions_no_truncate
  BEFORE TRUNCATE ON research_asset_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_events_no_truncate
  BEFORE TRUNCATE ON research_events FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER scientific_object_versions_no_truncate
  BEFORE TRUNCATE ON scientific_object_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER state_commits_no_truncate
  BEFORE TRUNCATE ON state_commits FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER validation_results_no_truncate
  BEFORE TRUNCATE ON validation_results FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();


-- ===== 00016_auth_password.sql =====

-- Email+password authentication (T0101): users.password_hash stores the
-- encoded password hash of an email+password account. NULL means the
-- account authenticates via OIDC only — both account kinds share one
-- identity space, and the credential column is deliberately opaque to
-- everything except the authn application layer (the encoding carries its
-- own parameters, so the KDF can be upgraded in place later).
ALTER TABLE users ADD COLUMN password_hash text NULL;

COMMENT ON COLUMN users.password_hash IS
  'argon2id PHC encoding ($argon2id$v=19$m=65536,t=3,p=2$...); NULL = OIDC-only account';


-- ===== 00017_profiles.sql =====

-- Research profile content (T0102): profiles is the 1:1 profile projection
-- for a person identity (docs/21 lists users and profiles as separate
-- canonical tables). The identity facts (handle, display_name, email) stay
-- on users; the profile content starts with bio and is where later profile
-- settings (per-field visibility etc.) will land without touching identity.
--
-- bio is a current projection, deliberately NOT append-only: the owner may
-- edit it (docs/21 §4 — the append-only set is the history/ledger tables).
-- The backfill materializes a row for every existing identity so the 1:1
-- shape holds from the moment the migration lands; stores also create the
-- row atomically with the user (credential store CTE, T0102).
CREATE TABLE profiles (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
  bio text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO profiles (user_id) SELECT id FROM users;


-- ===== 00018_organization_governance.sql =====

-- Organization governance (T0103): organizations.deactivated_at is the
-- only "delete" the domain offers (CLAUDE.md §9.8 — nothing disappears,
-- state only evolves). History keeps referring to deactivated organizations;
-- governance refuses new memberships/role changes on them (enforced by the
-- application layer, checked by tests).
ALTER TABLE organizations ADD COLUMN deactivated_at timestamptz NULL;

COMMENT ON COLUMN organizations.deactivated_at IS
  'soft-delete marker: set when the organization is deactivated by its owner; NULL = active';

-- The membership listing hot path (a user''s organizations) filters and
-- joins on user_id, which the composite PK does not cover from this side.
CREATE INDEX organization_memberships_user_idx ON organization_memberships (user_id);


-- ===== 00019_project_provisioning.sql =====

-- Project creation shell (T0104): provision_status records the GitProvider
-- provisioning state. Every new project starts 'pending'; T0301's Gitea
-- adapter moves it to 'provisioned' (or 'failed'). The column is part of
-- the project row, not a separate queue: the provisioning task derives its
-- work list from provision_status = 'pending'.
ALTER TABLE projects ADD COLUMN provision_status text NOT NULL DEFAULT 'pending'
  CHECK (provision_status IN ('pending', 'provisioned', 'failed'));

COMMENT ON COLUMN projects.provision_status IS
  'GitProvider provisioning state: pending (created, repo not provisioned yet), provisioned (T0301), failed';

-- Personal projects (organization_id IS NULL) are not covered by the
-- UNIQUE (organization_id, slug) constraint — PostgreSQL treats NULLs as
-- distinct there — so their slugs need their own uniqueness rule.
CREATE UNIQUE INDEX projects_personal_slug_idx ON projects (slug) WHERE organization_id IS NULL;


-- ===== 00020_audit_scopes.sql =====

-- Audit log organization scope (T0110): governance events (org.created,
-- org.updated, org.deactivated, org.member.*) are organization-scoped, and
-- the activity query filters by scope. audit_log already carries project_id;
-- the new nullable organization_id gives the organization scope the same
-- shape. The column is appended (ALTER TABLE ADD COLUMN), so it sits after
-- occurred_at in ordinal order.
--
-- Append-only enforcement already covers audit_log (00014 row triggers for
-- UPDATE/DELETE, 00015 statement-level TRUNCATE guard): new rows only, and
-- this column is written once at INSERT like every other column.
ALTER TABLE audit_log ADD COLUMN organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT;

-- Activity queries walk the log newest-first per scope; the composite
-- indexes order by (scope, occurred_at, id) so the keyset page
-- (occurred_at, id) < (before_ts, before_id) rides one index per scope.
CREATE INDEX audit_log_project_occurred_idx ON audit_log (project_id, occurred_at DESC, id DESC);
CREATE INDEX audit_log_organization_occurred_idx ON audit_log (organization_id, occurred_at DESC, id DESC);
CREATE INDEX audit_log_actor_occurred_idx ON audit_log (actor_id, occurred_at DESC, id DESC);


-- ===== 00024_scientific_object_version_counter.sql =====

-- Scientific object version counter (task T0202): current_version_no is both
-- the materialized current head of the append-only version log (docs/21 §5)
-- and the atomic compare-and-swap cell behind expected_version creation. The
-- version rows themselves stay append-only (migrations 00014/00015); this
-- pointer is the one deliberately mutable projection on scientific_objects
-- and is maintained by the repository inside the same transaction that
-- inserts the version row.
ALTER TABLE scientific_objects
  ADD COLUMN current_version_no integer NOT NULL DEFAULT 0
  CHECK (current_version_no >= 0);

-- Backfill from the version log so the pointer matches history on any
-- database where rows were written before this migration.
UPDATE scientific_objects o
   SET current_version_no = v.latest
  FROM (SELECT object_id, max(version_no) AS latest
          FROM scientific_object_versions
         GROUP BY object_id) v
 WHERE v.object_id = o.id;
