-- POST canonical database schema — GENERATED, DO NOT EDIT.
--
-- Generated by scripts/gen_schema_snapshot.py from the ordered Up sections of
-- infra/migrations/. The migrations are the canonical history; this file is
-- their snapshot, and `make check-schema-snapshot` fails when the two diverge.
--
-- To change the schema: add a migration, then run
--   python3 scripts/gen_schema_snapshot.py
-- (A Worker's task package states the migration number reserved for it; never
-- choose one from this file's own index — that is how two branches once both
-- created 00017.)
--
-- Sources, in application order:
--   00001_extensions.sql
--   00002_identity.sql
--   00003_projects.sql
--   00004_rsg_state.sql
--   00005_scientific_objects.sql
--   00006_relations.sql
--   00007_evidence.sql
--   00008_blobs.sql
--   00009_issues_pull_requests.sql
--   00010_releases_assets.sql
--   00011_external_contribution.sql
--   00012_events_audit.sql
--   00013_search_projection.sql
--   00014_append_only_enforcement.sql
--   00015_append_only_truncate.sql
--   00016_auth_password.sql
--   00017_profiles.sql
--   00018_organization_governance.sql
--   00019_project_provisioning.sql
--   00020_audit_scopes.sql
--   00022_git_repository_provisioning.sql
--   00024_scientific_object_version_counter.sql
--   00025_relation_version_counter.sql
--   00026_state_snapshot_indexes.sql
--   00028_branch_lifecycle_guard.sql
--   00031_branch_git_ref_sync.sql
--   00032_git_user_access.sql
--   00033_policy_versioning.sql
--   00034_push_ingestion.sql
--   00035_blob_attachment_state.sql
--   00036_rsg_query_indexes.sql


-- ===== 00001_extensions.sql =====

-- Extensions required by the canonical schema (specs/database/postgres.sql).
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ===== 00002_identity.sql =====

-- Identity: users, organizations, memberships (canonical lines 7-32).
CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  handle text UNIQUE NOT NULL,
  email text UNIQUE,
  display_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  disabled_at timestamptz
);

CREATE TABLE organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE organization_memberships (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role text NOT NULL CHECK (role IN ('owner','maintainer','contributor','viewer')),
  affiliation_start date,
  affiliation_end date,
  verified boolean NOT NULL DEFAULT false,
  PRIMARY KEY (organization_id,user_id)
);


-- ===== 00003_projects.sql =====

-- Projects, programs, memberships, policy versions (canonical lines 34-77).
CREATE TABLE programs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, slug)
);

CREATE TABLE projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  program_id uuid REFERENCES programs(id) ON DELETE SET NULL,
  slug text NOT NULL,
  name text NOT NULL,
  purpose text NOT NULL,
  activity_status text NOT NULL DEFAULT 'planning' CHECK (activity_status IN ('planning','active','paused','archived')),
  visibility text NOT NULL CHECK (visibility IN ('public','private')),
  main_frozen boolean NOT NULL DEFAULT false,
  git_repository_external_id text,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id,slug)
);

CREATE TABLE project_memberships (
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role text NOT NULL CHECK (role IN ('owner','maintainer','contributor','viewer')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(project_id,user_id)
);

CREATE TABLE policy_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  version text NOT NULL,
  policy_json jsonb NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((organization_id IS NOT NULL) <> (project_id IS NOT NULL))
);


-- ===== 00004_rsg_state.sql =====

-- RSG state model: branches, project states, state commits
-- (canonical lines 79-117).
--
-- NOTE: creation order differs from the canonical seed file: `branches` is
-- created before `project_states` because project_states references
-- branches(id) inline and PostgreSQL cannot create a table that references a
-- not-yet-existing relation. All constraints are preserved verbatim; only the
-- statement order was made executable. branches.base_state_id is still added
-- as a separate FK constraint via ALTER TABLE, exactly as in the canonical
-- seed (lines 104).
CREATE TABLE branches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  name text NOT NULL,
  visibility text NOT NULL CHECK (visibility IN ('public','private')),
  purpose text,
  git_ref text NOT NULL,
  base_state_id uuid,
  lifecycle_state text NOT NULL DEFAULT 'active' CHECK (lifecycle_state IN ('active','merged','aborted')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,name)
);

CREATE TABLE project_states (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  branch_id uuid REFERENCES branches(id) ON DELETE RESTRICT,
  parent_state_id uuid REFERENCES project_states(id) ON DELETE RESTRICT,
  state_hash text NOT NULL,
  git_commit_sha text,
  manifest_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,state_hash)
);
ALTER TABLE branches ADD CONSTRAINT branches_base_state_fk FOREIGN KEY(base_state_id) REFERENCES project_states(id) ON DELETE RESTRICT;

CREATE TABLE state_commits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  base_state_id uuid REFERENCES project_states(id) ON DELETE RESTRICT,
  result_state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  actor_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  via text NOT NULL CHECK (via IN ('web','api','mcp','claude_code','git_compat','system')),
  message text NOT NULL,
  operation_summary jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00005_scientific_objects.sql =====

-- Scientific objects and their append-only versions (canonical lines 119-144).
CREATE TABLE scientific_objects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  object_type text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE scientific_object_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  object_id uuid NOT NULL REFERENCES scientific_objects(id) ON DELETE RESTRICT,
  version_no integer NOT NULL CHECK(version_no > 0),
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  branch_id uuid REFERENCES branches(id) ON DELETE RESTRICT,
  schema_id text NOT NULL,
  schema_version text NOT NULL,
  title text NOT NULL,
  lifecycle_state text NOT NULL CHECK (lifecycle_state IN ('active','aborted','reopened','superseded')),
  payload jsonb NOT NULL,
  visibility_policy_id uuid,
  integrity_hash text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(object_id,version_no)
);
CREATE INDEX scientific_object_versions_payload_gin ON scientific_object_versions USING gin(payload);


-- ===== 00006_relations.sql =====

-- Relations and their versions (canonical lines 146-166).
CREATE TABLE relations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE relation_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  relation_id uuid NOT NULL REFERENCES relations(id) ON DELETE RESTRICT,
  version_no integer NOT NULL CHECK(version_no > 0),
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  relation_type text NOT NULL,
  source_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  target_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  integrity_hash text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(relation_id,version_no)
);
CREATE INDEX relation_versions_source_idx ON relation_versions(source_object_version_id, relation_type);
CREATE INDEX relation_versions_target_idx ON relation_versions(target_object_version_id, relation_type);


-- ===== 00007_evidence.sql =====

-- Evidence assertions (canonical lines 168-183).
CREATE TABLE evidence_assertions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  target_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  evidence_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  relation_type text NOT NULL CHECK (relation_type IN ('supports','contradicts','consistent_with','inconsistent_with','reproduces','fails_to_reproduce','validates','challenges','contextualizes')),
  evidence_type text NOT NULL,
  scope jsonb NOT NULL DEFAULT '{}'::jsonb,
  directness text NOT NULL DEFAULT 'unknown',
  inference_nature text NOT NULL DEFAULT 'unknown',
  reasoning_note text,
  review_state text NOT NULL DEFAULT 'unreviewed' CHECK(review_state IN ('unreviewed','reviewed','rejected')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00008_blobs.sql =====

-- Blobs and their attachments to scientific object versions
-- (canonical lines 185-202).
CREATE TABLE blobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content_hash text NOT NULL,
  size_bytes bigint NOT NULL CHECK(size_bytes >= 0),
  media_type text,
  storage_key text NOT NULL,
  integrity_state text NOT NULL DEFAULT 'pending' CHECK(integrity_state IN ('pending','verified','failed')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(content_hash,size_bytes)
);
CREATE TABLE blob_attachments (
  blob_id uuid NOT NULL REFERENCES blobs(id) ON DELETE RESTRICT,
  scientific_object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  attachment_role text NOT NULL,
  access_level text NOT NULL CHECK(access_level IN ('open','restricted')),
  PRIMARY KEY(blob_id, scientific_object_version_id, attachment_role)
);


-- ===== 00009_issues_pull_requests.sql =====

-- Issues, pull requests, reviews (canonical lines 204-242).
CREATE TABLE issues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  number bigint NOT NULL,
  issue_type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT 'open' CHECK(state IN ('open','in_progress','closed','aborted')),
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,number)
);

CREATE TABLE pull_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  number bigint NOT NULL,
  source_branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  target_branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  base_state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  proposed_state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT 'open',
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  merged_at timestamptz,
  UNIQUE(project_id,number)
);

CREATE TABLE reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pull_request_id uuid NOT NULL REFERENCES pull_requests(id) ON DELETE RESTRICT,
  reviewer_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  review_kind text NOT NULL CHECK(review_kind IN ('scientific','integrity','rights','ip')),
  decision text NOT NULL CHECK(decision IN ('approved','changes_requested','commented')),
  body text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00010_releases_assets.sql =====

-- Validation results, releases, research assets, publications
-- (canonical lines 244-312).
CREATE TABLE validation_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  gate text NOT NULL CHECK(gate IN ('pr','main','release','asset')),
  status text NOT NULL CHECK(status IN ('passed','failed','warning')),
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE releases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  version text NOT NULL,
  title text NOT NULL,
  state_id uuid NOT NULL REFERENCES project_states(id) ON DELETE RESTRICT,
  policy_version_id uuid REFERENCES policy_versions(id) ON DELETE RESTRICT,
  manifest jsonb NOT NULL,
  manifest_hash text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id,version)
);

CREATE TABLE research_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_type text NOT NULL CHECK(asset_type IN ('dataset','protocol','material_collection','benchmark')),
  slug text NOT NULL,
  title text NOT NULL,
  origin_project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE research_asset_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL REFERENCES research_assets(id) ON DELETE RESTRICT,
  version text NOT NULL,
  source_release_id uuid REFERENCES releases(id) ON DELETE RESTRICT,
  manifest jsonb NOT NULL,
  rights_json jsonb NOT NULL,
  visibility text NOT NULL CHECK(visibility IN ('public','private')),
  integrity_hash text NOT NULL,
  published_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  published_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(asset_id,version)
);
CREATE TABLE asset_lineage (
  parent_asset_version_id uuid NOT NULL REFERENCES research_asset_versions(id) ON DELETE RESTRICT,
  child_asset_version_id uuid NOT NULL REFERENCES research_asset_versions(id) ON DELETE RESTRICT,
  relation_type text NOT NULL CHECK(relation_type IN ('forked_from','derived_from','supersedes')),
  PRIMARY KEY(parent_asset_version_id,child_asset_version_id,relation_type)
);
CREATE TABLE asset_dependencies (
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  asset_version_id uuid NOT NULL REFERENCES research_asset_versions(id) ON DELETE RESTRICT,
  dependency_type text NOT NULL,
  visibility_of_usage text NOT NULL DEFAULT 'private' CHECK(visibility_of_usage IN ('public','private')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(project_id,asset_version_id,dependency_type)
);

CREATE TABLE knowledge_publications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  object_version_id uuid NOT NULL REFERENCES scientific_object_versions(id) ON DELETE RESTRICT,
  public_version text NOT NULL,
  rights_json jsonb NOT NULL,
  published_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  published_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(object_version_id,public_version)
);


-- ===== 00011_external_contribution.sql =====

-- External references, contribution ledger events, credit disputes
-- (canonical lines 314-354).
CREATE TABLE external_references (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_type text NOT NULL,
  external_identifier text NOT NULL,
  canonical_url text,
  UNIQUE(source_type,external_identifier)
);
CREATE TABLE external_reference_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_reference_id uuid NOT NULL REFERENCES external_references(id) ON DELETE RESTRICT,
  accessed_at timestamptz NOT NULL,
  upstream_version text,
  metadata jsonb NOT NULL,
  snapshot_hash text NOT NULL,
  blob_id uuid REFERENCES blobs(id) ON DELETE RESTRICT
);

CREATE TABLE contribution_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  organization_id_at_time uuid REFERENCES organizations(id) ON DELETE RESTRICT,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  event_type text NOT NULL,
  role_codes text[] NOT NULL DEFAULT '{}',
  object_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
  accepted_context boolean NOT NULL DEFAULT false,
  released_context boolean NOT NULL DEFAULT false,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE credit_disputes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  opened_by uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_ref text NOT NULL,
  claim text NOT NULL,
  state text NOT NULL DEFAULT 'open' CHECK(state IN ('open','resolved','rejected')),
  resolution text,
  opened_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);


-- ===== 00012_events_audit.sql =====

-- Domain events, transactional outbox, subscriptions, webhook deliveries,
-- audit log (canonical lines 356-408).
CREATE TABLE research_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  actor_id uuid REFERENCES users(id) ON DELETE RESTRICT,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  visibility text NOT NULL,
  payload jsonb NOT NULL,
  correlation_id text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE outbox_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  correlation_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  attempts integer NOT NULL DEFAULT 0
);

CREATE TABLE subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_type text NOT NULL,
  target_id text NOT NULL,
  event_filters text[] NOT NULL DEFAULT '{}',
  channels text[] NOT NULL DEFAULT '{web}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES research_events(id) ON DELETE RESTRICT,
  endpoint text NOT NULL,
  status text NOT NULL,
  response_code integer,
  attempts integer NOT NULL DEFAULT 0,
  last_attempt_at timestamptz
);

CREATE TABLE audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid REFERENCES users(id) ON DELETE RESTRICT,
  via text NOT NULL,
  action text NOT NULL,
  target_ref text,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  correlation_id text NOT NULL,
  before_summary jsonb,
  after_summary jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);


-- ===== 00013_search_projection.sql =====

-- Search projection (rebuildable; canonical lines 410-423).
CREATE TABLE search_documents (
  entity_ref text PRIMARY KEY,
  entity_type text NOT NULL,
  visibility text NOT NULL,
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  title text NOT NULL,
  content text NOT NULL,
  structured jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedding vector(1536),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX search_documents_fts_idx ON search_documents USING gin(to_tsvector('simple', title || ' ' || content));
CREATE INDEX search_documents_structured_gin ON search_documents USING gin(structured);


-- ===== 00014_append_only_enforcement.sql =====

-- Append-only enforcement (task T0013): the version/history/ledger tables are
-- immutable. An in-place UPDATE or DELETE of an existing row is rejected by
-- the database itself (BEFORE UPDATE OR DELETE row triggers that RAISE
-- EXCEPTION), so no client — application code, psql, a leaked credential — can
-- rewrite or erase history (CLAUDE.md §9, ADR-007, ADR-008, ADR-021,
-- docs/21 §4, docs/46, Master Acceptance Gate A).
--
-- Corrections never mutate a row: they append a new one (abort/reopen,
-- supersede, new version, new state). One shared guard function reports the
-- table name and the forbidden operation (TG_TABLE_NAME / TG_OP) so an
-- operator can act on the error.
--
-- Covered tables (append-only by design; see task result for the full
-- decision and the deliberately exempt tables):
--   scientific_object_versions, relation_versions        version logs
--   project_states, state_commits                        RSG state history
--   releases, research_asset_versions, asset_lineage     release/asset history
--   policy_versions                                      policy versions
--   validation_results                                   gate run records
--   contribution_events, audit_log                       append-only ledgers
--   research_events                                      domain event log
--   external_reference_snapshots                         pinned snapshots
--
-- No existing constraint is changed or dropped; no column semantics are added.

-- +goose StatementBegin
CREATE FUNCTION append_only_guard() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'table % is append-only: % is forbidden (history is immutable; insert a new row instead)',
    TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'P0001';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER scientific_object_versions_append_only
  BEFORE UPDATE OR DELETE ON scientific_object_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER relation_versions_append_only
  BEFORE UPDATE OR DELETE ON relation_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER project_states_append_only
  BEFORE UPDATE OR DELETE ON project_states
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER state_commits_append_only
  BEFORE UPDATE OR DELETE ON state_commits
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER releases_append_only
  BEFORE UPDATE OR DELETE ON releases
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_asset_versions_append_only
  BEFORE UPDATE OR DELETE ON research_asset_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER asset_lineage_append_only
  BEFORE UPDATE OR DELETE ON asset_lineage
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER policy_versions_append_only
  BEFORE UPDATE OR DELETE ON policy_versions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER validation_results_append_only
  BEFORE UPDATE OR DELETE ON validation_results
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER contribution_events_append_only
  BEFORE UPDATE OR DELETE ON contribution_events
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER audit_log_append_only
  BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_events_append_only
  BEFORE UPDATE OR DELETE ON research_events
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER external_reference_snapshots_append_only
  BEFORE UPDATE OR DELETE ON external_reference_snapshots
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();


-- ===== 00015_append_only_truncate.sql =====

-- Append-only enforcement, part 2 (follow-up to T0013).
--
-- Row-level triggers do NOT fire on TRUNCATE, so the immutability added in
-- 00014 could still be bypassed wholesale with `TRUNCATE <table> CASCADE`,
-- erasing an entire history in one statement. A statement-level BEFORE
-- TRUNCATE trigger closes that hole, reusing the same append_only_guard()
-- function (which reads TG_TABLE_NAME / TG_OP, set for statement-level
-- triggers exactly as for row-level ones).
--
-- Covers the same 13 tables as 00014. If that set changes, both migrations
-- must be extended with a new forward-only migration - never edited in place.

CREATE TRIGGER asset_lineage_no_truncate
  BEFORE TRUNCATE ON asset_lineage FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER audit_log_no_truncate
  BEFORE TRUNCATE ON audit_log FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER contribution_events_no_truncate
  BEFORE TRUNCATE ON contribution_events FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER external_reference_snapshots_no_truncate
  BEFORE TRUNCATE ON external_reference_snapshots FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER policy_versions_no_truncate
  BEFORE TRUNCATE ON policy_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER project_states_no_truncate
  BEFORE TRUNCATE ON project_states FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER relation_versions_no_truncate
  BEFORE TRUNCATE ON relation_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER releases_no_truncate
  BEFORE TRUNCATE ON releases FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_asset_versions_no_truncate
  BEFORE TRUNCATE ON research_asset_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER research_events_no_truncate
  BEFORE TRUNCATE ON research_events FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER scientific_object_versions_no_truncate
  BEFORE TRUNCATE ON scientific_object_versions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER state_commits_no_truncate
  BEFORE TRUNCATE ON state_commits FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER validation_results_no_truncate
  BEFORE TRUNCATE ON validation_results FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();


-- ===== 00016_auth_password.sql =====

-- Email+password authentication (T0101): users.password_hash stores the
-- encoded password hash of an email+password account. NULL means the
-- account authenticates via OIDC only — both account kinds share one
-- identity space, and the credential column is deliberately opaque to
-- everything except the authn application layer (the encoding carries its
-- own parameters, so the KDF can be upgraded in place later).
ALTER TABLE users ADD COLUMN password_hash text NULL;

COMMENT ON COLUMN users.password_hash IS
  'argon2id PHC encoding ($argon2id$v=19$m=65536,t=3,p=2$...); NULL = OIDC-only account';


-- ===== 00017_profiles.sql =====

-- Research profile content (T0102): profiles is the 1:1 profile projection
-- for a person identity (docs/21 lists users and profiles as separate
-- canonical tables). The identity facts (handle, display_name, email) stay
-- on users; the profile content starts with bio and is where later profile
-- settings (per-field visibility etc.) will land without touching identity.
--
-- bio is a current projection, deliberately NOT append-only: the owner may
-- edit it (docs/21 §4 — the append-only set is the history/ledger tables).
-- The backfill materializes a row for every existing identity so the 1:1
-- shape holds from the moment the migration lands; stores also create the
-- row atomically with the user (credential store CTE, T0102).
CREATE TABLE profiles (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
  bio text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO profiles (user_id) SELECT id FROM users;


-- ===== 00018_organization_governance.sql =====

-- Organization governance (T0103): organizations.deactivated_at is the
-- only "delete" the domain offers (CLAUDE.md §9.8 — nothing disappears,
-- state only evolves). History keeps referring to deactivated organizations;
-- governance refuses new memberships/role changes on them (enforced by the
-- application layer, checked by tests).
ALTER TABLE organizations ADD COLUMN deactivated_at timestamptz NULL;

COMMENT ON COLUMN organizations.deactivated_at IS
  'soft-delete marker: set when the organization is deactivated by its owner; NULL = active';

-- The membership listing hot path (a user''s organizations) filters and
-- joins on user_id, which the composite PK does not cover from this side.
CREATE INDEX organization_memberships_user_idx ON organization_memberships (user_id);


-- ===== 00019_project_provisioning.sql =====

-- Project creation shell (T0104): provision_status records the GitProvider
-- provisioning state. Every new project starts 'pending'; T0301's Gitea
-- adapter moves it to 'provisioned' (or 'failed'). The column is part of
-- the project row, not a separate queue: the provisioning task derives its
-- work list from provision_status = 'pending'.
ALTER TABLE projects ADD COLUMN provision_status text NOT NULL DEFAULT 'pending'
  CHECK (provision_status IN ('pending', 'provisioned', 'failed'));

COMMENT ON COLUMN projects.provision_status IS
  'GitProvider provisioning state: pending (created, repo not provisioned yet), provisioned (T0301), failed';

-- Personal projects (organization_id IS NULL) are not covered by the
-- UNIQUE (organization_id, slug) constraint — PostgreSQL treats NULLs as
-- distinct there — so their slugs need their own uniqueness rule.
CREATE UNIQUE INDEX projects_personal_slug_idx ON projects (slug) WHERE organization_id IS NULL;


-- ===== 00020_audit_scopes.sql =====

-- Audit log organization scope (T0110): governance events (org.created,
-- org.updated, org.deactivated, org.member.*) are organization-scoped, and
-- the activity query filters by scope. audit_log already carries project_id;
-- the new nullable organization_id gives the organization scope the same
-- shape. The column is appended (ALTER TABLE ADD COLUMN), so it sits after
-- occurred_at in ordinal order.
--
-- Append-only enforcement already covers audit_log (00014 row triggers for
-- UPDATE/DELETE, 00015 statement-level TRUNCATE guard): new rows only, and
-- this column is written once at INSERT like every other column.
ALTER TABLE audit_log ADD COLUMN organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT;

-- Activity queries walk the log newest-first per scope; the composite
-- indexes order by (scope, occurred_at, id) so the keyset page
-- (occurred_at, id) < (before_ts, before_id) rides one index per scope.
CREATE INDEX audit_log_project_occurred_idx ON audit_log (project_id, occurred_at DESC, id DESC);
CREATE INDEX audit_log_organization_occurred_idx ON audit_log (organization_id, occurred_at DESC, id DESC);
CREATE INDEX audit_log_actor_occurred_idx ON audit_log (actor_id, occurred_at DESC, id DESC);


-- ===== 00022_git_repository_provisioning.sql =====

-- GitProvider repository provisioning (T0301): the canonical record of the
-- platform→GitProvider (Gitea) repository mapping and the push-webhook HMAC
-- secret.
--
-- projects.git_repository_external_id (00003) is filled with the
-- GitProvider-side repository reference ("<owner>/<name>") once the
-- repository exists; the CHECK keeps the row honest — a project can never
-- report provisioned without the external reference.
--
-- Deliberately NOT added to projects: the failure reason. The canonical
-- store records the STATE (provision_status = 'failed', 00019) and the
-- job loop's structured logs carry the redacted reason — a projects column
-- would drag every project read path into the provisioning concern (and
-- sqlc's project queries select whole rows).
--
-- The webhook secret is also NOT a projects column: it is a credential
-- (docs/55 SECRET class), so it lives in its own table, is read only by
-- internal/gitprovider's own queries, and never rides the project
-- read/write paths or any API payload. One row per project IS the
-- project→repo 1:1 invariant at the storage layer (primary key on
-- project_id), with UNIQUE (owner, name) backing the name-derivation rule.
ALTER TABLE projects ADD CONSTRAINT projects_provision_consistent
  CHECK (provision_status <> 'provisioned' OR git_repository_external_id IS NOT NULL);

CREATE TABLE git_repository_provisions (
  project_id uuid PRIMARY KEY REFERENCES projects(id) ON DELETE RESTRICT,
  owner text NOT NULL,
  name text NOT NULL,
  gitea_repo_id bigint NOT NULL,
  webhook_id bigint NOT NULL,
  webhook_secret text NOT NULL,
  provisioned_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (owner, name)
);

COMMENT ON TABLE git_repository_provisions IS
  'The platform→GitProvider repository mapping (T0301): one row per provisioned project (project→repo 1:1). Product domain objects never read Gitea state; this table is the platform-side record of the provider-side facts.';

COMMENT ON COLUMN git_repository_provisions.webhook_secret IS
  'HMAC secret of the push webhook (docs/55 SECRET). Written at provisioning, read only by internal/gitprovider (T0305 push verification); never exposed through the API.';


-- ===== 00024_scientific_object_version_counter.sql =====

-- Scientific object version counter (task T0202): current_version_no is both
-- the materialized current head of the append-only version log (docs/21 §5)
-- and the atomic compare-and-swap cell behind expected_version creation. The
-- version rows themselves stay append-only (migrations 00014/00015); this
-- pointer is the one deliberately mutable projection on scientific_objects
-- and is maintained by the repository inside the same transaction that
-- inserts the version row.
ALTER TABLE scientific_objects
  ADD COLUMN current_version_no integer NOT NULL DEFAULT 0
  CHECK (current_version_no >= 0);

-- Backfill from the version log so the pointer matches history on any
-- database where rows were written before this migration.
UPDATE scientific_objects o
   SET current_version_no = v.latest
  FROM (SELECT object_id, max(version_no) AS latest
          FROM scientific_object_versions
         GROUP BY object_id) v
 WHERE v.object_id = o.id;


-- ===== 00025_relation_version_counter.sql =====

-- Relation version counter (task T0203): current_version_no is both the
-- materialized current head of the append-only relation_versions log
-- (docs/21 §5) and the atomic compare-and-swap cell behind expected_version
-- creation, exactly as 00024 does for scientific objects (T0202). The
-- version rows themselves stay append-only (migrations 00014/00015); this
-- pointer is the one deliberately mutable projection on relations and is
-- maintained by the repository inside the same transaction that inserts the
-- version row.
ALTER TABLE relations
  ADD COLUMN current_version_no integer NOT NULL DEFAULT 0
  CHECK (current_version_no >= 0);

-- Backfill from the version log so the pointer matches history on any
-- database where rows were written before this migration.
UPDATE relations r
   SET current_version_no = v.latest
  FROM (SELECT relation_id, max(version_no) AS latest
          FROM relation_versions
         GROUP BY relation_id) v
 WHERE v.relation_id = r.id;

-- The query-by-type paths (relations of a project filtered by relation
-- type) join relation_versions to relations on the project boundary;
-- relations.project_id had no index (the canonical seed indexes only the
-- relation_versions endpoints).
CREATE INDEX relations_project_idx ON relations(project_id);


-- ===== 00026_state_snapshot_indexes.sql =====

-- State snapshot projection indexes (task T0204). The two projection shapes
-- of the state model (docs/21 §5, docs/07 §7) are:
--
--   1. reading a state's direct members — the scientific object versions and
--      relation versions whose state_id equals the state (the transition each
--      row was created in); and
--   2. walking a branch's state lineage — the project_states chain and the
--      state_commits history, both filtered by branch_id.
--
-- All four projections are rebuildable from the canonical append-only
-- history; these indexes are performance-only, no semantic content.

CREATE INDEX scientific_object_versions_state_idx
  ON scientific_object_versions (state_id);

CREATE INDEX relation_versions_state_idx
  ON relation_versions (state_id);

CREATE INDEX project_states_branch_created_idx
  ON project_states (branch_id, created_at, id);

CREATE INDEX state_commits_branch_created_idx
  ON state_commits (branch_id, created_at, id);


-- ===== 00028_branch_lifecycle_guard.sql =====

-- Branch lifecycle invariants (task T0205): once a research branch is
-- merged or aborted its history is immutable (docs/43: "active → merged |
-- aborted；merged/aborted history immutable"). Enforced by the database
-- itself, for ANY update path — application code, psql, a leaked
-- credential:
--
--   1. the head pointer (branches.base_state_id, the docs/21 §5 "branch
--      current state" projection) must not move on a closed branch —
--      CommitState's compare-and-swap already guards it
--      (queries/rsg.sql UpdateBranchBaseState requires lifecycle_state =
--      'active'), this trigger makes the invariant unconditional;
--   2. the lifecycle itself is terminal: a merged/aborted branch never
--      transitions to another lifecycle (no merged→active, no merged→
--      aborted). The app-side CAS (SetBranchLifecycle requires the active
--      state) is the normal path; this trigger is the backstop.
--
-- branches is deliberately NOT covered by the append-only guards of
-- 00014: it is a mutable row by design (head projection, lifecycle).
-- This is the targeted constraint instead. No existing constraint is
-- changed or dropped; no column semantics are added.

-- +goose StatementBegin
CREATE FUNCTION branch_lifecycle_guard() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.lifecycle_state <> 'active' AND NEW.lifecycle_state IS DISTINCT FROM OLD.lifecycle_state THEN
    RAISE EXCEPTION 'branch lifecycle is terminal: a % branch cannot move to % (docs/43: active -> merged | aborted only)',
      OLD.lifecycle_state, NEW.lifecycle_state
      USING ERRCODE = 'P0001';
  END IF;
  IF OLD.lifecycle_state <> 'active' AND NEW.base_state_id IS DISTINCT FROM OLD.base_state_id THEN
    RAISE EXCEPTION 'branch head is immutable on a % branch (merged/aborted history is immutable, docs/43)',
      OLD.lifecycle_state
      USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER branch_lifecycle_guard_trigger
  BEFORE UPDATE ON branches
  FOR EACH ROW EXECUTE FUNCTION branch_lifecycle_guard();

-- Branches are listed per project in creation order
-- (ListBranchesByProject); performance-only index, same discipline as
-- 00026 — the UNIQUE(project_id, name) constraint does not cover the
-- ordering.
CREATE INDEX branches_project_created_idx
  ON branches (project_id, created_at, id);


-- ===== 00031_branch_git_ref_sync.sql =====

-- Semantic branch ↔ Git ref consistency (T0303): the canonical mapping
-- between a branches row and its provider-side ref, and the invariants
-- that make "semantic branch 与 Git ref 一致" unconditional.
--
-- The ref name is DERIVED, never stored twice as an independent fact:
-- branches.git_ref = 'refs/heads/' || name is enforced by
-- branch_git_ref_guard for ANY write path (application code, psql, a leaked
-- credential) — the same discipline as 00028's lifecycle guard. The
-- application service derives the same value on creation
-- (branches.Service.Create), so existing writers are unaffected.
--
-- One mapping row per branches row, created by branch_git_ref_map —
-- branch creation and the mapping can never drift apart, no matter which
-- path inserts the branch.
--
-- Sync state machine (git_branch_refs.sync_state), driven by
-- internal/gitprovider's BranchRefSyncer (the boot sweep plus redelivered
-- jobs re-attempt, the same bounded-retry policy as T0301 provisioning):
--
--   pending → synced | failed | closing      row awaits its ref
--   synced → failed | closing                ref exists, head recorded
--   failed → synced | closing | closed | failed   last attempt failed; retryable
--   closing → closed | failed                branch closed; ref deletion pending
--   closed                                   terminal: ref deleted, final head recorded
--
-- The direction is carried by the row itself: close_requested_at set (or
-- sync_state = 'closing') means "delete the ref"; otherwise "ensure the ref
-- exists". git_branch_ref_guard enforces the machine for ANY update path.
--
-- Ref strategy on branch close (docs/43: active → merged | aborted): the
-- provider ref is DELETED in both cases, after its final head sha is
-- recorded in head_sha (the reconstruction pointer). The semantic history
-- is unaffected — branches / project_states / state_commits stay immutable
-- (00028) — and docs/46 retention applies to scientific history, not to
-- git ref pointers: a dangling research ref must not keep accepting pushes
-- once the semantic path is closed. The deletion is asynchronous:
-- branch_git_ref_close marks the row 'closing' and the syncer performs the
-- provider call; a provider outage leaves the row in the retry backlog.
--
-- main is mapped too (one row per branch, no exceptions). The syncer never
-- creates or deletes refs/heads/main on purpose: for main the fork point
-- resolves to the repository's default branch, which in an empty
-- repository does not exist — so main's row waits (retryable 'failed')
-- until T0302 creates the ref, then adopts it and records the head.
-- main's ref lifecycle belongs to T0302 (initial commit + protection) and
-- the T0406 merge service, not to this table's syncer.

CREATE TABLE git_branch_refs (
  branch_id uuid PRIMARY KEY REFERENCES branches(id) ON DELETE RESTRICT,
  git_ref text NOT NULL,
  -- fork_sha: the provider-side commit the ref was created at — the base
  -- state's project_states.git_commit_sha when recorded (T0305 fills those
  -- on ingestion), otherwise the repository's default branch was used (the
  -- pre-T0305 fallback; every state is an ancestor of the accepted head in
  -- the normal flow).
  fork_sha text,
  -- head_sha: the ref's last known tip, written by the syncer at create,
  -- adopt and close time. On close it is the final head recorded BEFORE
  -- the ref is deleted — the pointer that keeps the closed path
  -- reconstructable. T0305 keeps it fresh on push ingestion.
  head_sha text,
  sync_state text NOT NULL DEFAULT 'pending'
    CHECK (sync_state IN ('pending','synced','failed','closing','closed')),
  close_requested_at timestamptz,
  synced_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE git_branch_refs IS
  'The semantic branch → GitProvider ref mapping and sync record (T0303): one row per branches row (maintained by trigger), the provider-side fork/head commits, and the sync state machine that keeps semantic branch and Git ref consistent. Provider-side calls are internal/gitprovider''s alone; every other product path may only read head_sha.';

COMMENT ON COLUMN git_branch_refs.head_sha IS
  'Last known provider-side tip of the ref; on close, the final head recorded before deletion (the reconstruction pointer — docs/46 retention applies to semantic history; a closed git ref must not keep accepting pushes).';

-- ---------------------------------------------------------------------------
-- branch_git_ref_guard: the branches-side invariants.
--   1. git_ref is DERIVED — it must always equal 'refs/heads/' || name
--      (the 1:1 mapping the acceptance criterion names);
--   2. the branch name is immutable: the git ref is the branch's address,
--      so renaming would be a new branch (V1 has no rename path; a future
--      rename feature changes this migration deliberately, not by accident).
-- ---------------------------------------------------------------------------
-- +goose StatementBegin
CREATE FUNCTION branch_git_ref_guard() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.git_ref <> 'refs/heads/' || NEW.name THEN
    RAISE EXCEPTION 'branch git_ref must be refs/heads/<name>: % does not name %',
      NEW.git_ref, NEW.name
      USING ERRCODE = 'P0001';
  END IF;
  IF TG_OP = 'UPDATE' AND NEW.name IS DISTINCT FROM OLD.name THEN
    RAISE EXCEPTION 'branch name is immutable: the git ref is the branch address, renaming is a new branch'
      USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER branch_git_ref_guard_trigger
  BEFORE INSERT OR UPDATE ON branches
  FOR EACH ROW EXECUTE FUNCTION branch_git_ref_guard();

-- branch_git_ref_map: every branch row gets its mapping row, so the sync
-- backlog is self-maintaining — a branch that exists but is unmapped is
-- impossible, whatever path inserted it. A branch born closed (lifecycle
-- already merged/aborted at insert) starts in 'closing': its ref must be
-- removed, never created.
-- +goose StatementBegin
CREATE FUNCTION branch_git_ref_map() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.lifecycle_state IN ('merged','aborted') THEN
    INSERT INTO git_branch_refs (branch_id, git_ref, sync_state, close_requested_at)
    VALUES (NEW.id, NEW.git_ref, 'closing', now());
  ELSE
    INSERT INTO git_branch_refs (branch_id, git_ref)
    VALUES (NEW.id, NEW.git_ref);
  END IF;
  RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER branch_git_ref_map_trigger
  AFTER INSERT ON branches
  FOR EACH ROW EXECUTE FUNCTION branch_git_ref_map();

-- branch_git_ref_close: the abort/merge ref strategy's storage half — when
-- the semantic lifecycle closes (00028's guard enforces the active →
-- merged | aborted direction itself), the mapping row moves to 'closing':
-- the syncer then records the final head and deletes the provider ref.
-- The lifecycle transition commits first; the provider call happens later
-- in the job loop, so a provider outage can never roll back a semantic
-- merge.
-- +goose StatementBegin
CREATE FUNCTION branch_git_ref_close() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.lifecycle_state = 'active' AND NEW.lifecycle_state IN ('merged','aborted') THEN
    UPDATE git_branch_refs
       SET sync_state = 'closing', close_requested_at = now(), updated_at = now()
     WHERE branch_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER branch_git_ref_close_trigger
  AFTER UPDATE OF lifecycle_state ON branches
  FOR EACH ROW EXECUTE FUNCTION branch_git_ref_close();

-- git_branch_ref_guard: the mapping-row invariants — the stored git_ref
-- matches the branch's derived ref (backstop for the guard above and for
-- the backfill below), the sync state machine only moves forward, and
-- 'closed' is terminal (a deleted ref's row never reopens).
-- +goose StatementBegin
CREATE FUNCTION git_branch_ref_guard() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  want text;
BEGIN
  SELECT 'refs/heads/' || name INTO want FROM branches WHERE id = NEW.branch_id;
  IF want IS NULL OR NEW.git_ref <> want THEN
    RAISE EXCEPTION 'git_branch_refs.git_ref must name its branch: % does not name branch %',
      NEW.git_ref, NEW.branch_id
      USING ERRCODE = 'P0001';
  END IF;
  IF TG_OP = 'INSERT' AND NEW.sync_state = 'closed' THEN
    RAISE EXCEPTION 'a mapping row is born with work to do: closed is only reached through closing'
      USING ERRCODE = 'P0001';
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF NEW.git_ref IS DISTINCT FROM OLD.git_ref THEN
      RAISE EXCEPTION 'git_branch_refs.git_ref is immutable'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'closed' THEN
      RAISE EXCEPTION 'closed is terminal: a deleted ref''s row does not reopen'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'pending' AND NEW.sync_state NOT IN ('synced','failed','closing') THEN
      RAISE EXCEPTION 'pending may only move to synced, failed or closing'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'synced' AND NEW.sync_state NOT IN ('failed','closing') THEN
      RAISE EXCEPTION 'synced may only move to failed or closing'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'failed' AND NEW.sync_state NOT IN ('synced','closing','failed','closed') THEN
      RAISE EXCEPTION 'failed may only retry, reach synced, close, or reach closed'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'closing' AND NEW.sync_state NOT IN ('closed','failed') THEN
      RAISE EXCEPTION 'closing may only reach closed or fail back for retry'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER git_branch_ref_guard_trigger
  BEFORE INSERT OR UPDATE ON git_branch_refs
  FOR EACH ROW EXECUTE FUNCTION git_branch_ref_guard();

-- Backfill: branches that predate this migration get their mapping row,
-- derived from the name (never copied from a possibly drifted git_ref).
-- Closed branches (merged/aborted) are born 'closing' with a close
-- timestamp, mirroring branch_git_ref_map above: their refs must be
-- removed by the sweep, never created — a dangling ref must not keep
-- accepting pushes once the semantic path is closed, and no close trigger
-- can ever fire for those terminal rows again (00028). Live branches start
-- 'pending': the next startup sweep adopts or creates every ref.
INSERT INTO git_branch_refs (branch_id, git_ref, sync_state, close_requested_at)
SELECT id, 'refs/heads/' || name,
       CASE WHEN lifecycle_state IN ('merged','aborted') THEN 'closing' ELSE 'pending' END,
       CASE WHEN lifecycle_state IN ('merged','aborted') THEN now() ELSE NULL END
FROM branches;

-- The sync backlog is the hot query (boot sweep + redelivered jobs); a
-- partial index keeps the terminal rows out of it. Same discipline as
-- 00026/00028 performance indexes.
CREATE INDEX git_branch_refs_sync_backlog_idx
  ON git_branch_refs (sync_state)
  WHERE sync_state IN ('pending','failed','closing');


-- ===== 00032_git_user_access.sql =====

-- Git user access (T0304): scoped git tokens, revocation and the
-- platform→GitProvider repo access mapping.
--
-- Product identity is never Gitea identity (ADR-019): a platform user who
-- wants to use a real git client gets
--
--   1. a provider-side shadow account (git_user_identities, login
--      "u-<user uuid>" — deterministic, like the repository naming rule
--      in 00022), created token-only: the platform generates an
--      unguessable password at creation and discards it, so the account
--      is usable exclusively through tokens the platform mints;
--   2. one repo access grant per project (git_repo_access): the shadow
--      account becomes a collaborator on the project's provisioned
--      repository with a permission derived from the platform role
--      (viewer → read, contributor/maintainer/owner → write);
--   3. scoped access tokens minted per grant (git_access_tokens): the
--      token carries the narrowest provider scopes (read:repository,
--      or +write:repository) and the collaborator grant above decides
--      which repository the account can reach — that pair
--      (collaborator grant + scoped token) is the "scoped git token"
--      of docs/16 §2 identity mapping. NOTE: a Gitea token is an
--      INSTANCE-scoped capability — it can reach any repository the
--      account can see, a public one included; the platform's tokens
--      are project-scoped in effect only because every platform
--      repository is private. A public-repository feature must revisit
--      this premise.
--
-- Revocation has two levels, and both keep their history (domain
-- invariant 8: nothing disappears, state only evolves):
--
--   - token revocation: the provider-side token is deleted and the row
--     moves to status 'revoked' with revoked_at — the credential dies,
--     the audit trail stays;
--   - access revocation: the collaborator grant is removed provider-side
--     (every token of that user on that repository dies with it) and
--     git_repo_access.revoked_at records when.
--
-- The token VALUE is never stored anywhere on the platform (docs/55
-- SECRET class): Gitea returns it exactly once at mint time, the API
-- hands it to the user exactly once, and only the provider-side token id
-- (gitea_token_id) is kept for revocation. Nothing here can be read back
-- into a credential.

CREATE TABLE git_user_identities (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
  gitea_username text UNIQUE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE git_user_identities IS
  'The platform→GitProvider user identity mapping (T0304): one shadow Gitea account per platform user (login "u-<user uuid>"). The account is token-only; the platform discards its creation password, so every credential the user ever receives is a scoped token from git_access_tokens.';

CREATE TABLE git_repo_access (
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  permission text NOT NULL CHECK (permission IN ('read','write')),
  granted_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  PRIMARY KEY (project_id, user_id),
  CHECK (revoked_at IS NULL OR revoked_at >= granted_at)
);

COMMENT ON TABLE git_repo_access IS
  'The repo access mapping (T0304): which platform user holds which Git-layer permission on which project''s provisioned repository. The provider-side enforcement is the collaborator membership this row mirrors; revoking access sets revoked_at (nothing disappears, domain invariant 8).';

COMMENT ON COLUMN git_repo_access.permission IS
  'Git-layer permission derived from the platform role: read (viewer) or write (contributor/maintainer/owner). Never wider than the platform role — Git access is a projection of platform membership, not a parallel permission system.';

CREATE TABLE git_access_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  gitea_username text NOT NULL REFERENCES git_user_identities(gitea_username) ON DELETE RESTRICT,
  token_name text NOT NULL,
  gitea_token_id bigint NOT NULL,
  scope text NOT NULL CHECK (scope IN ('read','write')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked')),
  issued_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  CHECK (revoked_at IS NULL OR revoked_at >= issued_at),
  CHECK (status = 'active' OR revoked_at IS NOT NULL)
);

COMMENT ON TABLE git_access_tokens IS
  'Issued scoped git tokens (T0304): one row per minted provider-side access token. The token value itself is never stored (docs/55 SECRET — Gitea shows it once); gitea_token_id is the revocation handle. Rows are never deleted: revocation flips status and sets revoked_at.';

COMMENT ON COLUMN git_access_tokens.scope IS
  'The Gitea scope set the token was minted with: read (read:repository) or write (read:repository + write:repository). Bounded by the user''s collaborator grants — a token can only reach repositories the user holds a git_repo_access row for.';


-- ===== 00033_policy_versioning.sql =====

-- T0603 policy versioning (docs/12 §5): per-scope version uniqueness and
-- the version shape guard. policy_versions itself is append-only
-- (00014/00015 reject UPDATE/DELETE/TRUNCATE at the database): a policy
-- never mutates in place, a change is always a NEW version row, so old
-- versions stay queryable by construction. Each scope line now also has
-- a unique version string — a version number is never reused, not even
-- across a gap.
CREATE UNIQUE INDEX policy_versions_org_version_idx
  ON policy_versions (organization_id, version)
  WHERE organization_id IS NOT NULL;

CREATE UNIQUE INDEX policy_versions_project_version_idx
  ON policy_versions (project_id, version)
  WHERE project_id IS NOT NULL;

-- The version string is a required, bounded label (the app layer allows
-- [A-Za-z0-9._-], this guard only enforces the shape that belongs in the
-- database itself).
ALTER TABLE policy_versions
  ADD CONSTRAINT policy_versions_version_check
  CHECK (char_length(version) BETWEEN 1 AND 64);


-- ===== 00034_push_ingestion.sql =====

-- Push ingestion (T0305): the canonical record of every verified push
-- webhook delivery, the inspected changed-file set, and the candidate
-- semantic diff derived from known scientific manifests (docs/16 §4:
-- webhook → inspect changed paths/manifests → validate known scientific
-- manifests → generate candidate RSG diff).
--
-- Idempotency is the acceptance criterion "重复 webhook 不重复 state":
-- the dedupe key is (gitea_repo_id, git_ref, after_sha) — the provider's
-- own per-attempt delivery id (X-Gitea-Delivery) is regenerated on every
-- redelivery (checked against the running instance), so it cannot dedupe;
-- the pushed head commit is the stable identity of the push's content.
-- Two deliveries of the same push therefore collide on the key and the
-- whole ingestion (changes, candidates, head pointer, state row) is a
-- no-op — INSERT ... ON CONFLICT DO NOTHING inside one transaction.
--
-- Consequence, by design: a force-push that returns a ref to a commit
-- whose tree was already ingested is skipped too — the state at that head
-- already exists, so nothing new to record.
--
-- The ref's head pointer is GUARDED, not a free fact of the push, in
-- both advance paths:
--   * a push whose before names the current head advances only while the
--     pointer is still there — head_sha = before_sha — so a delivery
--     whose before no longer matches is refused and the row marks
--     head_skip_reason = 'stale_before';
--   * a creation push (before is zeros) advances only while the ref is
--     still unborn — head_sha IS NULL — or already at the pushed head; a
--     creation delivery that arrives after the ref gained a head (a
--     later sync, or a newer push) is refused and the row marks
--     head_skip_reason = 'stale_creation'.
-- A refused advance still records the delivery in full (the audit rows
-- are facts of the delivery); only the pointer is held. An older push
-- whose first attempt 503'd and whose redelivery arrives after a newer
-- push was ingested therefore can never rewind the pointer past the
-- newer head, in either path. An exact duplicate is a complete no-op
-- including the pointer. Residual provider/state drift that no push can
-- express is T0309's reconciliation job, not this table's.
--
-- project_states: every pushed branch head is also recorded as a state
-- row (append-only, 00014-guarded — the provider commit arrives WITH the
-- row, never by UPDATE), so a later branch creation can fork its provider
-- ref at the base state's git_commit_sha (T0303's fork-point resolution)
-- and the branch's state history includes its git pushes. The state hash
-- is content-derived: sha256 over the canonical JSON {"git_commit_sha":
-- "<after>"} — the git-compat state identity, distinct from the domain's
-- transition hashes by construction (it hashes the pinned commit, not a
-- parent + operations pair).

CREATE TABLE git_push_ingestions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- The provider's per-attempt delivery id (X-Gitea-Delivery), for
  -- correlating with the provider's delivery log only — NOT the dedupe
  -- key (redeliveries mint a new one).
  delivery_id text,
  gitea_repo_id bigint NOT NULL,
  -- The canonical project, resolved from git_repository_provisions at
  -- ingestion time. NULL when the repository is not provisioned (a
  -- delivery for a repository this platform does not own — recorded for
  -- audit, mapped to no branch and no state).
  project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
  branch_name text NOT NULL,
  git_ref text NOT NULL,
  before_sha text NOT NULL,
  after_sha text NOT NULL,
  -- The provider's own commit count (may exceed the delivered commit
  -- list — the provider truncates it; the authoritative changed-path set
  -- comes from the git diff, never from the list).
  commit_count integer NOT NULL DEFAULT 0,
  -- Provider login of the pusher (not mapped to a platform user — T0304
  -- owns identity mapping).
  pusher text,
  -- The delivered commit list as the provider sent it (already bounded
  -- by the provider), for audit; the ingestion pipeline does not consume
  -- it.
  commits jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- Why the head-pointer advance was refused for this delivery, when it
  -- was: 'stale_before' means git_branch_refs.head_sha no longer equalled
  -- before_sha when the delivery arrived — a stale redelivery of an older
  -- push (its first attempt failed before recording anything, and a newer
  -- push was ingested in between), or a ref that was never synced to the
  -- claimed base. 'stale_creation' means the delivery created the ref
  -- (before is zeros) but the ref already carried a head this push did
  -- not create — a creation push whose first attempt 503'd and whose
  -- redelivery arrived after a later sync or a newer push set the
  -- pointer. The refusal is recorded, never silent: the audit rows of
  -- the delivery are kept, only the pointer is not moved. NULL when the
  -- advance happened (or there was no pointer to guard).
  head_skip_reason text CHECK (head_skip_reason IS NULL OR head_skip_reason IN ('stale_before', 'stale_creation')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (gitea_repo_id, git_ref, after_sha)
);

COMMENT ON TABLE git_push_ingestions IS
  'The canonical record of every accepted push webhook delivery (T0305): one row per distinct pushed head per ref per repository. The dedupe key (gitea_repo_id, git_ref, after_sha) makes redelivered webhooks a no-op — the acceptance criterion 重复 webhook 不重复 state. The head pointer advance is guarded: it happens only when the pointer is still where the push started, and a refused advance is recorded in head_skip_reason, never silently dropped. Rows are append-only (guard below).';

-- git_push_changes: the inspection result — every changed path of the
-- push, classified. semantic_manifest means the file''s content validated
-- against a known scientific schema; everything else is unstructured
-- (T0306 builds the branch completeness flag on this).
CREATE TABLE git_push_changes (
  ingestion_id uuid NOT NULL REFERENCES git_push_ingestions(id) ON DELETE RESTRICT,
  path text NOT NULL,
  change_kind text NOT NULL CHECK (change_kind IN ('added','modified','removed')),
  file_kind text NOT NULL CHECK (file_kind IN ('semantic_manifest','unstructured')),
  -- The matched schema id for semantic_manifest files (the registry''s
  -- canonical $id, e.g. https://open-rd.example/schemas/material.schema.json —
  -- the shape the validation surface stores); NULL for unstructured.
  schema_id text,
  -- sha256 hex of the file content the classification inspected (the
  -- pushed content for added/modified, the pre-push content for removed);
  -- NULL for unstructured files (never read) and oversize files.
  content_sha256 text,
  PRIMARY KEY (ingestion_id, path)
);

COMMENT ON TABLE git_push_changes IS
  'The inspected changed-file set of one ingested push (T0305): path, change kind and the manifest classification (semantic_manifest vs unstructured). The authoritative path set comes from the git diff — the provider payload''s commit list is truncated (checked against the running instance).';

-- git_push_semantic_candidates: the candidate RSG diff — one row per
-- changed manifest file whose content matched a known scientific schema.
-- The candidate is the PROPOSAL the push implies (create/update/delete of
-- the manifest''s content), not an applied semantic change: applying it
-- requires the semantic validation pipeline (T0207 machinery); until then
-- it stays status = ''candidate''. T0306 derives the branch completeness
-- flag from candidates vs unstructured changes.
CREATE TABLE git_push_semantic_candidates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ingestion_id uuid NOT NULL REFERENCES git_push_ingestions(id) ON DELETE RESTRICT,
  path text NOT NULL,
  change_kind text NOT NULL CHECK (change_kind IN ('added','modified','removed')),
  schema_id text NOT NULL,
  -- The manifest content the candidate proposes, bounded (the
  -- ingestion reads at most 1 MiB per file).
  candidate jsonb NOT NULL,
  -- candidate is the only state T0305 writes; later tasks move rows to
  -- validated (semantic validation passed), applied (the RSG transition
  -- committed) or rejected (validation failed).
  status text NOT NULL DEFAULT 'candidate' CHECK (status IN ('candidate','validated','applied','rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ingestion_id, path)
);

COMMENT ON TABLE git_push_semantic_candidates IS
  'The candidate semantic diff of one ingested push (T0305): per changed manifest file, the proposed content and its matched schema, awaiting the semantic validation pipeline. Never an applied RSG change by itself.';

-- The ingestion record and the inspection result are append-only facts
-- (docs/21 §4, 00014's discipline): a delivery once recorded is never
-- rewritten — the dedupe no-op and the T0309 reconciliation both depend
-- on it.
CREATE TRIGGER git_push_ingestions_append_only
  BEFORE UPDATE OR DELETE ON git_push_ingestions
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER git_push_changes_append_only
  BEFORE UPDATE OR DELETE ON git_push_changes
  FOR EACH ROW EXECUTE FUNCTION append_only_guard();

-- The TRUNCATE halves (00015's discipline: row triggers do not fire on
-- TRUNCATE) — the push record is history, not even wholesale erasure is a
-- legal update path.
CREATE TRIGGER git_push_ingestions_no_truncate
  BEFORE TRUNCATE ON git_push_ingestions FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER git_push_changes_no_truncate
  BEFORE TRUNCATE ON git_push_changes FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

CREATE TRIGGER git_push_semantic_candidates_no_truncate
  BEFORE TRUNCATE ON git_push_semantic_candidates FOR EACH STATEMENT
  EXECUTE FUNCTION append_only_guard();

-- Candidate rows are content-immutable but their status transitions
-- (candidate → validated | applied | rejected, the validation pipeline's
-- later tasks). The guard pins everything except the status: the proposed
-- content of a delivery is a fact of that delivery, and a candidate row is
-- never deleted (its ingestion is append-only).
-- +goose StatementBegin
CREATE FUNCTION git_push_semantic_candidate_guard() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'git_push_semantic_candidates rows are never deleted: a candidate is a fact of its delivery'
      USING ERRCODE = 'P0001';
  END IF;
  IF NEW.ingestion_id IS DISTINCT FROM OLD.ingestion_id
     OR NEW.path IS DISTINCT FROM OLD.path
     OR NEW.change_kind IS DISTINCT FROM OLD.change_kind
     OR NEW.schema_id IS DISTINCT FROM OLD.schema_id
     OR NEW.candidate IS DISTINCT FROM OLD.candidate THEN
    RAISE EXCEPTION 'git_push_semantic_candidates content is immutable: only status transitions'
      USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER git_push_semantic_candidate_guard_trigger
  BEFORE UPDATE OR DELETE ON git_push_semantic_candidates
  FOR EACH ROW EXECUTE FUNCTION git_push_semantic_candidate_guard();

-- The head-pointer refresh (T0303 assigned it to T0305): 00031's
-- git_branch_ref_guard forbids ANY update that does not move sync_state —
-- the syncer was the only writer when it was written. Push ingestion must
-- keep head_sha fresh without being a state-machine transition, so the
-- guard is REPLACED with the same machine plus a fast path: an update
-- that changes NOTHING but the tip pointer (head_sha; the guard itself
-- maintains updated_at) is allowed in every state except 'closed'
-- (terminal — a deleted ref's row does not reopen, its final head is
-- already recorded). The fast path is a WHITELIST over every other
-- column — to_jsonb(NEW) and to_jsonb(OLD) compared with head_sha and
-- updated_at removed — so a column added to this table later is covered
-- automatically (a fixed enumeration would let the next new column slip
-- through, as it let branch_id and created_at). The transition rules are
-- otherwise copied verbatim from 00031.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION git_branch_ref_guard() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  want text;
BEGIN
  SELECT 'refs/heads/' || name INTO want FROM branches WHERE id = NEW.branch_id;
  IF want IS NULL OR NEW.git_ref <> want THEN
    RAISE EXCEPTION 'git_branch_refs.git_ref must name its branch: % does not name branch %',
      NEW.git_ref, NEW.branch_id
      USING ERRCODE = 'P0001';
  END IF;
  IF TG_OP = 'INSERT' AND NEW.sync_state = 'closed' THEN
    RAISE EXCEPTION 'a mapping row is born with work to do: closed is only reached through closing'
      USING ERRCODE = 'P0001';
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF NEW.git_ref IS DISTINCT FROM OLD.git_ref THEN
      RAISE EXCEPTION 'git_branch_refs.git_ref is immutable'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'closed' THEN
      RAISE EXCEPTION 'closed is terminal: a deleted ref''s row does not reopen'
        USING ERRCODE = 'P0001';
    END IF;
    IF to_jsonb(NEW) - 'head_sha' - 'updated_at' = to_jsonb(OLD) - 'head_sha' - 'updated_at' THEN
      -- T0305 head-pointer refresh: the tip moved, nothing else did.
      NEW.updated_at = now();
      RETURN NEW;
    END IF;
    IF OLD.sync_state = 'pending' AND NEW.sync_state NOT IN ('synced','failed','closing') THEN
      RAISE EXCEPTION 'pending may only move to synced, failed or closing'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'synced' AND NEW.sync_state NOT IN ('failed','closing') THEN
      RAISE EXCEPTION 'synced may only move to failed or closing'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'failed' AND NEW.sync_state NOT IN ('synced','closing','failed','closed') THEN
      RAISE EXCEPTION 'failed may only retry, reach synced, close, or reach closed'
        USING ERRCODE = 'P0001';
    END IF;
    IF OLD.sync_state = 'closing' AND NEW.sync_state NOT IN ('closed','failed') THEN
      RAISE EXCEPTION 'closing may only reach closed or fail back for retry'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
-- +goose StatementEnd


-- ===== 00035_blob_attachment_state.sql =====

-- Blob attachments carry the state they were created in (T0206). The domain
-- contract names blob attachments among the state members whose state_id
-- column makes a state's content enumerable from its id alone
-- (internal/domain/state.go), but 00008 created blob_attachments without the
-- column. Without it the manifest export (ListManifestBlobRefs) can only
-- filter on the owning object version's state, so an attachment made in a
-- later state would appear in earlier states' manifests and move their
-- hashes — a state's hash must be a pure function of the state's own
-- recorded content, so the attachment's own state is the only column the
-- export may filter on.
--
-- Existing rows are backfilled from the owning object version's state_id —
-- the only defensible source available. This is an approximation for
-- pre-existing rows, not a claim about when they were attached: an
-- attachment created in state S for a version that lives in an ancestor
-- state is recorded under the ancestor's state. New attachments (AttachBlob)
-- always write the committing state, so the approximation applies only to
-- rows predating this migration.
ALTER TABLE blob_attachments
  ADD COLUMN state_id uuid REFERENCES project_states(id) ON DELETE RESTRICT;
UPDATE blob_attachments ba
SET state_id = sov.state_id
FROM scientific_object_versions sov
WHERE sov.id = ba.scientific_object_version_id;
ALTER TABLE blob_attachments
  ALTER COLUMN state_id SET NOT NULL;

-- The manifest export's blob-ref filter (ListManifestBlobRefs) walks this
-- column on every export; the index keeps it an indexed lineage lookup
-- instead of a per-export seq scan (same shape as the version tables'
-- state indexes from 00026).
CREATE INDEX blob_attachments_state_idx ON blob_attachments(state_id);


-- ===== 00036_rsg_query_indexes.sql =====

-- RSG query surface index (T0209). The query API's candidate scan is
-- project-scoped with the object-type filter as the index's second
-- column; the relations-by-project scan already uses the
-- relations_project_idx created by migration 00025. Performance-only, no
-- semantic content — every shape remains rebuildable from the canonical
-- append-only history.

CREATE INDEX scientific_objects_project_type_idx
  ON scientific_objects (project_id, object_type);
