/** Synthetic, seed-demo-only identities. Never use these credentials outside POST's demo database. */
export const DEMO_ACCOUNTS = [
  {
    email: "demo.owner@example.invalid",
    password: "seed-demo-owner-pw-1",
    name: "Demo Owner",
    role: "Project lead",
    organization: "Demo MOF Lab",
    project: "MOF-X humidity separation",
  },
  {
    email: "demo.curator@example.invalid",
    password: "seed-demo-curator-pw-1",
    name: "Lin Qiao",
    role: "Data curator",
    organization: "Demo MOF Lab",
    project: "Published datasets and protocol",
  },
  {
    email: "demo.experimenter@example.invalid",
    password: "seed-demo-experimenter-pw-1",
    name: "Mei Chen",
    role: "Experimental scientist",
    organization: "Demo MOF Lab",
    project: "Adsorption campaigns",
  },
  {
    email: "demo.computational@example.invalid",
    password: "seed-demo-computational-pw-1",
    name: "Arun Rao",
    role: "Computational scientist",
    organization: "Northbridge Computational Materials Center",
    project: "MOF-Y transferability study",
  },
  {
    email: "demo.replication@example.invalid",
    password: "seed-demo-replication-pw-1",
    name: "Eva Lin",
    role: "Replication lead",
    organization: "Westhaven University Adsorption Group",
    project: "Independent MOF-X replication",
  },
  {
    email: "demo.reviewer@example.invalid",
    password: "seed-demo-reviewer-pw-1",
    name: "Noah Zhou",
    role: "Benchmark reviewer and contributor",
    organization: "Westhaven University Adsorption Group",
    project: "Benchmark review",
  },
  {
    email: "demo.viewer@example.invalid",
    password: "seed-demo-viewer-pw-1",
    name: "Ava Wu",
    role: "Read-only observer",
    organization: "Northbridge Computational Materials Center",
    project: "Public research and asset pages",
  },
  {
    email: "demo.external@example.invalid",
    password: "seed-demo-external-pw-1",
    name: "Demo External",
    role: "External collaborator",
    organization: "Demo External Group",
    project: "Forked independent replication",
  },
] as const;
