#!/usr/bin/env bash
#
# sqlc generation drift check (task T0005).
#
# The generated code under internal/persistence/sqlc is CHECKED IN. This check
# proves the checked-in code matches what sqlc v1.31.1 actually produces from
# the current queries (internal/persistence/queries) and schema
# (infra/migrations): it snapshots the checked-in files, regenerates in place,
# diffs the two, and restores the snapshot — so the check never mutates the
# working tree and works both before and after commit.
#
# Usage:
#   tests/integration/check-sqlc-drift.sh            passing mode: exit 0 iff
#                                                    zero drift
#   tests/integration/check-sqlc-drift.sh --demo-fail  failing mode: inject a
#                                                    probe query, show the
#                                                    check failing with the
#                                                    diff, restore the tree
#                                                    (exit 0 if detection
#                                                    demonstrably works)
#
# Requirements: sqlc on PATH or in $SQLC_BIN, bash, diff.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

GEN_DIR="internal/persistence/sqlc"

SQLC_BIN="${SQLC_BIN:-$(command -v sqlc || true)}"
if [[ -z "$SQLC_BIN" ]]; then
  echo "error: sqlc not found on PATH (install: go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1)" >&2
  exit 1
fi

SNAPSHOT="$(mktemp -d)"
trap 'rm -rf "$SNAPSHOT"' EXIT
cp -r "$GEN_DIR" "$SNAPSHOT/sqlc"

check_drift() {
  local desc="$1" # "verify" or "demo"
  "$SQLC_BIN" generate
  if diff -r "$SNAPSHOT/sqlc" "$GEN_DIR" >/dev/null 2>&1; then
    echo "DRIFT CHECK [$desc]: clean — checked-in generated code matches generator output"
    return 0
  fi
  echo "DRIFT CHECK [$desc]: FAILED — regeneration differs from checked-in code:" >&2
  diff -r "$SNAPSHOT/sqlc" "$GEN_DIR" >&2 || true
  return 1
}

if [[ "${1:-}" == "--demo-fail" ]]; then
  echo "== failing-mode demonstration: injecting a probe query =="
  PROBE="internal/persistence/queries/users.sql"
  cp "$PROBE" "$SNAPSHOT/users.sql"
  trap 'mv "$SNAPSHOT/users.sql" "$PROBE"; "$SQLC_BIN" generate; rm -rf "$SNAPSHOT"' EXIT
  printf '\n-- name: DriftProbeQuery :one\nSELECT 42 AS answer;\n' >> "$PROBE"
  if check_drift "demo"; then
    echo "UNEXPECTED: drift check passed despite injected drift" >&2
    exit 1
  fi
  echo "== expected failure observed above: the drift check detects the injected query =="
  echo "== tree restored and regenerated by the EXIT trap =="
  exit 0
fi

check_drift "verify"
