#!/usr/bin/env python3
"""Generate the canonical schema snapshot from the migration history.

`specs/database/postgres.sql` used to be a hand-maintained seed that the
migrations were supposed to be a "faithful decomposition" of. In practice the
seed froze while the migrations moved: by the end of P1 it was five migrations
behind, and `infra/migrations/README.md` itself documents that the seed is not
even executable (it creates `project_states` before `branches`, which
PostgreSQL rejects). A canonical artifact that silently lags is worse than no
canonical artifact, because it is trusted.

So the direction is inverted: THE MIGRATIONS ARE THE CANONICAL HISTORY, and
this file is the generated snapshot of them. It is derived, byte-for-byte, from
the ordered Up sections — no database needed, no judgement, no drift.

  python3 scripts/gen_schema_snapshot.py           # write the snapshot
  python3 scripts/gen_schema_snapshot.py --check   # fail when it is stale

Exit codes: 0 ok; 1 stale (--check) or unreadable input; 2 usage error.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def paths(root):
    """The migration directory and snapshot under root (--root makes the whole
    mechanism fixture-testable without touching the real tree)."""
    return root / "infra" / "migrations", root / "specs" / "database" / "postgres.sql"

USAGE_ERROR = 2

HEADER = """\
-- POST canonical database schema — GENERATED, DO NOT EDIT.
--
-- Generated by scripts/gen_schema_snapshot.py from the ordered Up sections of
-- infra/migrations/. The migrations are the canonical history; this file is
-- their snapshot, and `make check-schema-snapshot` fails when the two diverge.
--
-- To change the schema: add a migration, then run
--   python3 scripts/gen_schema_snapshot.py
-- (A Worker's task package states the migration number reserved for it; never
-- choose one from this file's own index — that is how two branches once both
-- created 00017.)
--
-- Sources, in application order:
"""

UP = "-- +goose Up"
DOWN = "-- +goose Down"


def up_section(text):
    """The Up section of one migration, without the goose Down section."""
    if UP not in text:
        raise ValueError("no '-- +goose Up' marker")
    body = text.split(UP, 1)[1]
    if DOWN in body:
        body = body.split(DOWN, 1)[0]
    return body.strip("\n")


def build(root):
    MIGRATIONS, _ = paths(root)
    files = sorted(p for p in MIGRATIONS.glob("*.sql"))
    if not files:
        raise ValueError(f"no migrations under {MIGRATIONS}")
    parts = [HEADER]
    for p in files:
        parts.append(f"--   {p.name}\n")
    for p in files:
        parts.append(f"\n\n-- ===== {p.name} =====\n\n")
        parts.append(up_section(p.read_text()))
        parts.append("\n")
    return "".join(parts)


def main(argv):
    ap = argparse.ArgumentParser(add_help=False)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--root", default=str(ROOT))
    ap.add_argument("-h", "--help", action="store_true")
    args, extra = ap.parse_known_args(argv)
    if args.help or extra:
        print(__doc__)
        return 0 if args.help else USAGE_ERROR

    root = Path(args.root)
    MIGRATIONS, SNAPSHOT = paths(root)
    try:
        want = build(root)
    except (OSError, ValueError) as exc:
        print(f"gen-schema-snapshot: {exc}", file=sys.stderr)
        return 1

    if args.check:
        have = SNAPSHOT.read_text() if SNAPSHOT.exists() else ""
        if have == want:
            n = len(list(MIGRATIONS.glob("*.sql")))
            print(f"schema snapshot: current ({n} migrations)")
            return 0
        print(
            "schema snapshot: STALE — specs/database/postgres.sql is not the "
            "ordered migrations.\nThe migrations are canonical; the snapshot "
            "is derived. Regenerate it:\n"
            "  python3 scripts/gen_schema_snapshot.py",
            file=sys.stderr,
        )
        return 1

    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(want)
    n = len(list(MIGRATIONS.glob("*.sql")))
    try:
        shown = SNAPSHOT.relative_to(root)
    except ValueError:  # --root outside the repository (fixtures)
        shown = SNAPSHOT
    print(f"schema snapshot: wrote {shown} from {n} migrations")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
