#!/usr/bin/env python3
"""Progress view regenerator (T0008): rebuild the machine-generated section
of tasks/progress.md from tasks/task_status.json + tasks/tasks.json.

tasks/progress.md carries hand-written governance narrative that must never
be rewritten; only the section between the markers

    <!-- AUTO-PROGRESS:BEGIN ... -->
    ...
    <!-- AUTO-PROGRESS:END -->

is machine-owned. Default mode rewrites exactly that section (appending it,
markers included, when progress.md has none yet). --check fails (exit 1)
when the section exists but is stale, and only prints a notice when it does
not exist yet. Everything else in the file is left byte-identical.

Usage:
  python3 scripts/update_progress.py [--root DIR] [--check] [--stamp STAMP]

Exit codes: 0 = up to date / updated; 1 = stale (--check) or state files
unusable; 2 = usage error.
"""
import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import speclib

USAGE_ERROR = 2
BEGIN_MARK = "<!-- AUTO-PROGRESS:BEGIN — generated by " \
            "scripts/update_progress.py, do not hand-edit -->"
END_MARK = "<!-- AUTO-PROGRESS:END -->"
STATUS_ORDER = ("todo", "ready", "running", "worker_failed", "verification",
                "rejected", "blocked", "accepted", "merged")


def fail_usage(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(USAGE_ERROR)


def parse_args(argv):
    p = argparse.ArgumentParser(
        prog="scripts/update_progress.py",
        description="Regenerate the auto section of tasks/progress.md from "
                    "task_status.json")
    p.add_argument("--root", default=str(speclib.default_root()),
                   help="repository root (default: parent of scripts/)")
    p.add_argument("--check", action="store_true",
                   help="fail when the auto section is stale instead of "
                        "rewriting it")
    p.add_argument("--stamp", default=None,
                   help="fixed generation timestamp (test determinism)")
    return p.parse_args(argv)


def now_stamp():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_tasks(root):
    """Returns (tasks_by_id, status_by_id) or exits with a clear error."""
    tpath = root / speclib.DEFAULT_TASKS_REL
    spath = root / "tasks/task_status.json"
    if not tpath.is_file() or not spath.is_file():
        print(f"error: need {speclib.DEFAULT_TASKS_REL} and "
              f"tasks/task_status.json under {root}", file=sys.stderr)
        sys.exit(USAGE_ERROR)
    try:
        tlist = speclib.load_json(tpath).get("tasks", [])
        status = speclib.load_json(spath).get("tasks", {})
    except (OSError, json.JSONDecodeError) as exc:
        print(f"error: reading task state: {exc}", file=sys.stderr)
        sys.exit(USAGE_ERROR)
    tasks = {t.get("id"): t for t in tlist if isinstance(t, dict)}
    if not tasks:
        print("error: no tasks found in tasks/tasks.json", file=sys.stderr)
        sys.exit(USAGE_ERROR)
    return tasks, status


def render_section(tasks, status, stamp):
    lines = [BEGIN_MARK, "", "## 任务状态自动总览", "",
             f"生成时间：{stamp}", ""]
    counts = {s: sum(1 for v in status.values()
                     if isinstance(v, dict) and v.get("status") == s)
              for s in STATUS_ORDER}
    total = sum(counts.values())
    dist = " · ".join(f"{s} {counts[s]}" for s in STATUS_ORDER)
    lines.append(f"状态分布：{dist}（合计 {total}/{len(tasks)} 个任务）")
    lines.append("")
    lines.append("| Task | 标题 | 阶段 | 状态 | 开始 | 完成 | 验收 | 合并 |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for tid in sorted(tasks):
        t = tasks[tid]
        st = status.get(tid, {}) if isinstance(status.get(tid), dict) else {}
        title = str(t.get("title", "")).replace("|", "\\|")
        phase = str(t.get("phase", ""))
        lines.append(
            f"| {tid} | {title} | {phase} | {st.get('status', 'MISSING')} "
            f"| {st.get('started_at') or ''} | {st.get('completed_at') or ''} "
            f"| {st.get('accepted_by_supervisor_at') or ''} "
            f"| {st.get('merged_at') or ''} |")
    lines.append("")
    lines.append(END_MARK)
    return "\n".join(lines) + "\n"


def split_section(text):
    """Returns (before, section_or_None, after). The section includes one
    trailing newline when present, so a just-written file compares equal."""
    b = text.find(BEGIN_MARK)
    e = text.find(END_MARK)
    if b == -1 or e == -1 or e <= b:
        return text, None, ""
    e_end = e + len(END_MARK)
    if text[e_end:e_end + 1] == "\n":
        e_end += 1
    return text[:b], text[b:e_end], text[e_end:]


def main(argv):
    args = parse_args(argv)
    root = Path(args.root)
    stamp = args.stamp or now_stamp()
    tasks, status = load_tasks(root)
    rendered = render_section(tasks, status, stamp)

    ppath = root / "tasks/progress.md"
    if not ppath.is_file():
        print(f"error: {ppath} not found", file=sys.stderr)
        return 1
    text = ppath.read_text(encoding="utf-8")
    before, current, after = split_section(text)

    if args.check:
        if current is None:
            print("notice: tasks/progress.md has no auto section yet — "
                  "run without --check once to seed it")
            return 0
        if current == rendered:
            print("progress view up to date")
            return 0
        print("progress view is stale: run scripts/update_progress.py "
              "(or make progress) to regenerate the auto section",
              file=sys.stderr)
        return 1

    # after.lstrip("\n"): exactly one trailing newline survives — rendered
    # already ends with one, and keeping the old trailing blanks would make
    # the second run non-idempotent.
    updated = (before.rstrip("\n") + "\n\n" + rendered + after.lstrip("\n")
               if current is None else before + rendered + after.lstrip("\n"))
    if updated == text:
        print("progress view already up to date")
        return 0
    ppath.write_text(updated, encoding="utf-8")
    print(f"progress view regenerated in {ppath} "
          f"({'seeded' if current is None else 'rewritten'}, {stamp})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
