package domain

import (
	"crypto/rand"
	"fmt"
	"strings"
)

// PID is a persistent identifier: 26 lowercase Crockford base32 characters
// (128 bits of randomness, no padding), URL-safe and unambiguous in print
// (the Crockford alphabet drops i, l, o, u).
//
// A pid is generated once, at the moment the entity it names comes into
// existence, and never changes: it is NOT derived from the slug, the
// title, the owning organization, the version label, or any other
// revisable attribute — an identifier derived from a revisable attribute
// is not persistent, and every URL built from it would break on the first
// rename (migration 00064's acceptance: asset ID 不随 slug/org 变化).
//
// It lives in internal/domain rather than beside either of the two tables
// that carry one because it is one vocabulary with two homes:
// research_assets.pid (00064) and knowledge_publications.pid (00083) are
// the same identifier format, enforced by the same CHECK and generated by
// this one function. The format has exactly one definition — this package
// — and internal/assets keeps its asset-flavoured names as thin aliases so
// that the two callers cannot drift apart the first time one side changes
// (the reasoning 00064 gives for leaving the origin ref's kind:value shape
// in one place).
type PID string

// PIDAlphabet is the Crockford base32 set, lowercase: 0-9 and a-z
// without i, l, o, u. It is the alphabet the CHECK constraints in
// migrations 00064 and 00083 spell as a character class, and ValidPID's
// ranges are it. Exported because it IS the format: a test that pins the
// encoding (internal/assets/pid_test.go) reads the same string the
// generator writes from, rather than a second copy of it.
const PIDAlphabet = "0123456789abcdefghjkmnpqrstvwxyz"

// PIDLen is the fixed pid length: 16 random bytes = 128 bits, encoded in
// base32 = ceil(128/5) = 26 characters, no padding. Exported for the same
// reason as PIDAlphabet.
const PIDLen = 26

// NewPID returns a fresh random persistent identifier, generated with
// crypto/rand (stdlib — identity generation must not depend on any
// external service, and the application layer never invents its own
// encoding). The only error is an exhausted entropy source.
//
// Encoding: the 128 bits are read MSB-first as 5-bit groups, exactly like
// RFC 4648 base32 without padding — the final group holds the last 3 bits
// zero-extended. Each group i spans the bit positions 5i..5i+4; a 16-bit
// window starting at the group's byte keeps the extraction branch-free
// (the window's low byte is zero past the buffer, which is the padding
// rule itself).
func NewPID() (PID, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("domain: generate pid: %w", err)
	}
	var sb strings.Builder
	sb.Grow(PIDLen)
	for i := 0; i < PIDLen; i++ {
		bit := i * 5
		byteIdx := bit / 8
		shift := uint(bit % 8) // the group's start inside its byte
		var win uint16 = uint16(b[byteIdx]) << 8
		if byteIdx+1 < len(b) {
			win |= uint16(b[byteIdx+1])
		}
		// The group's highest bit sits at window position 15-shift, so
		// the group is the 5 bits starting there: window >> (11-shift).
		sb.WriteByte(PIDAlphabet[(win>>(11-shift))&0x1f])
	}
	return PID(sb.String()), nil
}

// Valid reports whether p has the exact pid shape: 26 lowercase Crockford
// base32 characters. It is the Go mirror of the database's
// research_assets_pid_format and knowledge_publications_pid_format CHECKs.
func (p PID) Valid() bool { return ValidPID(string(p)) }

// ValidPID reports whether s has the exact pid shape. Uppercase input is
// rejected: pids are emitted lowercase, and accepting case variants of one
// identity creates lookalike ambiguity — exactly what the Crockford
// alphabet exists to avoid.
func ValidPID(s string) bool {
	if len(s) != PIDLen {
		return false
	}
	for _, r := range s {
		switch {
		case r >= '0' && r <= '9', r >= 'a' && r <= 'h', r >= 'j' && r <= 'k', r >= 'm' && r <= 'n', r >= 'p' && r <= 't', r >= 'v' && r <= 'z':
		default:
			return false
		}
	}
	return true
}
